// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

// Removes the keywords of protoschema-jsonschema's output that reject values
// protovalidate accepts. The generated modules pass in the table of what to
// remove; this module only knows how to find the nodes.

/** Fix drops keywords from one node of a field, e.g. `{ at: "items", drop: ["pattern"] }`. */
export type Fix = { at?: "items" | "propertyNames" | "additionalProperties"; drop: readonly string[] };

/** FieldFixes are the fixes of one field. `alias` is its proto name, e.g. "host_name", when it differs from the JSON name. */
export type FieldFixes = { alias?: string; fixes: readonly Fix[] };

/** Fixes maps a def id to its fields, keyed by JSON name; "" is the def itself. */
export type Fixes = Readonly<Record<string, Readonly<Record<string, FieldFixes>>>>;

type Node = { [keyword: string]: unknown };

/**
 * loosenWith returns a copy of the bundle with every fix applied. The bundle
 * itself is never mutated: every importer of a JSON module shares one object.
 * A def or field the bundle lacks is skipped.
 */
export function loosenWith<T>(fixes: Fixes, bundle: T): T {
  const copy = JSON.parse(JSON.stringify(bundle)) as T;
  const defs = (copy as { $defs?: Record<string, unknown> }).$defs ?? {};

  for (const [id, fields] of Object.entries(fixes)) {
    const def = defs[id];
    if (!isNode(def)) continue;

    for (const [name, field] of Object.entries(fields)) {
      for (const node of fieldNodes(def, name, field.alias)) {
        for (const fix of field.fixes) {
          const target = fix.at === undefined ? node : node[fix.at];
          if (isNode(target)) drop(target, fix.drop);
        }
      }
    }
  }
  return copy;
}

// fieldNodes finds a field under its JSON name in properties, and in every
// patternProperties entry `^(a|b)$` that names it: the lenient alias, the proto
// name, and a field upstream moved there for `// jsonschema:hide`.
function fieldNodes(def: Node, name: string, alias: string | undefined): Node[] {
  if (name === "") return [def];

  const nodes = [child(def.properties, name)];
  const patterns = def.patternProperties;
  if (isNode(patterns)) {
    for (const [key, node] of Object.entries(patterns)) {
      const names = /^\^\((.*)\)\$$/.exec(key)?.[1]?.split("|") ?? [];
      if (names.includes(name) || (alias !== undefined && names.includes(alias))) nodes.push(node);
    }
  }
  return nodes.filter(isNode);
}

// drop deletes the keywords from the node and from every anyOf branch below it.
function drop(node: Node, keywords: readonly string[]): void {
  for (const keyword of keywords) delete node[keyword];

  if (!Array.isArray(node.anyOf)) return;
  for (const branch of node.anyOf) {
    if (isNode(branch)) drop(branch, keywords);
  }
}

function child(parent: unknown, key: string): unknown {
  return isNode(parent) ? parent[key] : undefined;
}

function isNode(value: unknown): value is Node {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
