// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

import { z } from "zod/v3";

// The well-known types, in the canonical protojson form protobuf-es's toJson
// emits and its *Json types describe.

const int64 = /^-?[0-9]+$/;
const uint64 = /^[0-9]+$/;
const double = z.union([z.number(), z.enum(["NaN", "Infinity", "-Infinity"])]);

export const timestampZod = z.string();
export const durationZod = z.string();
export const fieldMaskZod = z.string();

// Zod 3 has no z.json(); z.lazy is what lets the schema refer to itself.
export const valueZod = z.lazy(() =>
  z.union([z.string(), z.number().finite(), z.boolean(), z.null(), z.array(valueZod), z.record(z.string(), valueZod)]),
);
export const structZod = z.record(z.string(), valueZod);
export const listValueZod = z.array(valueZod);
export const nullValueZod = z.null();

// An empty Any is written as {}, so "@type" is optional.
export const anyZod = z.object({ "@type": z.string().optional() }).passthrough();
export const emptyZod = z.strictObject({});

export const boolValueZod = z.boolean();
export const bytesValueZod = z.string();
export const doubleValueZod = double;
export const floatValueZod = double;
export const int32ValueZod = z.number().int();
export const int64ValueZod = z.string().regex(int64);
export const stringValueZod = z.string();
export const uInt32ValueZod = z.number().int();
export const uInt64ValueZod = z.string().regex(uint64);
