// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/catalog/v1/product.proto

import { z } from "zod/v3";
import { fieldMaskZod, timestampZod } from "../../../strict/wkt.zod3.js";
import { moneyZod, paginationZod } from "../../common/v1/common.zod3.js";

/**
 * ProductStatus is the lifecycle state of a product.
 *
 * shop.catalog.v1.ProductStatus, as protojson writes it: the member's name.
 */
export declare const productStatusZod: z.ZodEnum<["PRODUCT_STATUS_UNSPECIFIED", "PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"]>;

/**
 * Product is the catalog resource.
 *
 * The composable schema of shop.catalog.v1.Product: every field carries its own rules, so
 * `productZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in productZod.
 */
export declare const productZodObject: z.ZodObject<{
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.ZodOptional<z.ZodString>;
  /**
   * string.max_len = 32
   * string.min_len = 3
   * string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$
   *
   * Checked by protovalidate: string.max_len, string.min_len, string.pattern.
   */
  sku: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_len = 200
   * string.min_len = 1
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  name: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_len = 4096
   *
   * Checked by protovalidate: string.max_len.
   */
  description: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  price: typeof moneyZod;
  discountPrice: z.ZodOptional<typeof moneyZod>;
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  status: z.ZodOptional<z.ZodEnum<["PRODUCT_STATUS_UNSPECIFIED", "PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"]>>;
  /**
   * repeated.items.string.max_len = 40
   * repeated.items.string.min_len = 1
   * repeated.items.string.pattern = ^[a-z0-9-]+$
   * repeated.max_items = 20
   * repeated.unique = true
   *
   * Carried by Zod: repeated.max_items.
   * Checked by protovalidate: repeated.items.string.max_len, repeated.items.string.min_len, repeated.items.string.pattern, repeated.unique.
   */
  tags: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /**
   * map.max_pairs = 16
   *
   * Checked by protovalidate: map.max_pairs.
   */
  labels: z.ZodOptional<z.ZodEffects<z.ZodRecord<z.ZodString, z.ZodString>>>;
  /**
   * cel[product.created_by_email]: this.size() == 0 || this.isEmail()
   *   message: if set, created_by_email must be a valid email address
   *   refs: this
   *   calls: _==_, _||_, isEmail, size
   *
   * Checked by protovalidate: cel[product.created_by_email].
   */
  createdByEmail: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  createdAt: z.ZodOptional<typeof timestampZod>;
  updatedAt: z.ZodOptional<typeof timestampZod>;
  publishedAt: z.ZodOptional<typeof timestampZod>;
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  version: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.Product. Adds what protovalidate checks on the whole message:
 *   cel[product.discount_below_price]
 *   cel[product.draft_not_published]
 *   the rules of id, sku, name, status, tags, labels, created_by_email, version when absent: protojson omits a zero value
 */
export declare const productZod: z.ZodEffects<typeof productZodObject>;

/**
 * CreateProductRequest creates a new product.
 *
 * The composable schema of shop.catalog.v1.CreateProductRequest: every field carries its own rules, so
 * `createProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in createProductRequestZod.
 */
export declare const createProductRequestZodObject: z.ZodObject<{
  /**
   * required
   *
   * Carried by Zod: required.
   */
  product: typeof productZod;
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  idempotencyKey: z.ZodOptional<z.ZodString>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.CreateProductRequest. Adds what protovalidate checks on the whole message:
 *   cel[create_product.no_read_only_fields]
 */
export declare const createProductRequestZod: z.ZodEffects<typeof createProductRequestZodObject>;

/**
 * CreateProductResponse returns the stored product.
 *
 * The composable schema of shop.catalog.v1.CreateProductResponse: every field carries its own rules, so
 * `createProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in createProductResponseZod.
 */
export declare const createProductResponseZodObject: z.ZodObject<{
  product: z.ZodOptional<typeof productZod>;
}, "strict">;

/** Full validation of shop.catalog.v1.CreateProductResponse: the message has no rule beyond its fields'. */
export declare const createProductResponseZod: typeof createProductResponseZodObject;

/**
 * GetProductRequest looks a product up by id or by SKU.
 *
 * The composable schema of shop.catalog.v1.GetProductRequest: every field carries its own rules, so
 * `getProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in getProductRequestZod.
 */
export declare const getProductRequestZodObject: z.ZodObject<{
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.ZodOptional<z.ZodString>;
  /**
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  sku: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.GetProductRequest. Adds what protovalidate checks on the whole message:
 *   required oneof key: exactly one of id, sku
 */
export declare const getProductRequestZod: z.ZodEffects<typeof getProductRequestZodObject>;

/**
 * GetProductResponse returns a single product.
 *
 * The composable schema of shop.catalog.v1.GetProductResponse: every field carries its own rules, so
 * `getProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in getProductResponseZod.
 */
export declare const getProductResponseZodObject: z.ZodObject<{
  product: z.ZodOptional<typeof productZod>;
}, "strict">;

/** Full validation of shop.catalog.v1.GetProductResponse: the message has no rule beyond its fields'. */
export declare const getProductResponseZod: typeof getProductResponseZodObject;

/**
 * ListProductsRequest pages through the catalog.
 *
 * The composable schema of shop.catalog.v1.ListProductsRequest: every field carries its own rules, so
 * `listProductsRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in listProductsRequestZod.
 */
export declare const listProductsRequestZodObject: z.ZodObject<{
  /**
   * required
   *
   * Carried by Zod: required.
   */
  pagination: typeof paginationZod;
  /**
   * repeated.items.enum.defined_only = true
   * repeated.items.enum.not_in = [0]
   *
   * Carried by Zod: repeated.items.enum.defined_only, repeated.items.enum.not_in.
   */
  statuses: z.ZodOptional<z.ZodArray<z.ZodEnum<["PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"]>>>;
  /**
   * string.max_len = 200
   * string.min_len = 1
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  nameContains: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  minPrice: z.ZodOptional<typeof moneyZod>;
  maxPrice: z.ZodOptional<typeof moneyZod>;
  /**
   * string.in = [, name, sku, created_at, price]
   *
   * Carried by Zod: string.in.
   */
  orderBy: z.ZodOptional<z.ZodEnum<["", "name", "sku", "created_at", "price"]>>;
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  orderDirection: z.ZodOptional<z.ZodEnum<["SORT_DIRECTION_UNSPECIFIED", "SORT_DIRECTION_ASC", "SORT_DIRECTION_DESC"]>>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.ListProductsRequest. Adds what protovalidate checks on the whole message:
 *   cel[list_products.price_bounds]
 *   the rules of order_by, order_direction when absent: protojson omits a zero value
 */
export declare const listProductsRequestZod: z.ZodEffects<typeof listProductsRequestZodObject>;

/**
 * ListProductsResponse is one page of products.
 *
 * The composable schema of shop.catalog.v1.ListProductsResponse: every field carries its own rules, so
 * `listProductsResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in listProductsResponseZod.
 */
export declare const listProductsResponseZodObject: z.ZodObject<{
  products: z.ZodOptional<z.ZodArray<typeof productZod>>;
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  totalSize: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  nextPageToken: z.ZodOptional<z.ZodString>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.ListProductsResponse. Adds what protovalidate checks on the whole message:
 *   the rules of total_size when absent: protojson omits a zero value
 */
export declare const listProductsResponseZod: z.ZodEffects<typeof listProductsResponseZodObject>;

/**
 * UpdateProductRequest performs a partial update.
 *
 * The composable schema of shop.catalog.v1.UpdateProductRequest: every field carries its own rules, so
 * `updateProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in updateProductRequestZod.
 */
export declare const updateProductRequestZodObject: z.ZodObject<{
  /**
   * required
   *
   * Carried by Zod: required.
   */
  product: typeof productZod;
  updateMask: z.ZodOptional<typeof fieldMaskZod>;
}, "strict">;

/**
 * Full validation of shop.catalog.v1.UpdateProductRequest. Adds what protovalidate checks on the whole message:
 *   cel[update_product.id_present]
 */
export declare const updateProductRequestZod: z.ZodEffects<typeof updateProductRequestZodObject>;

/**
 * UpdateProductResponse returns the stored product.
 *
 * The composable schema of shop.catalog.v1.UpdateProductResponse: every field carries its own rules, so
 * `updateProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in updateProductResponseZod.
 */
export declare const updateProductResponseZodObject: z.ZodObject<{
  product: z.ZodOptional<typeof productZod>;
}, "strict">;

/** Full validation of shop.catalog.v1.UpdateProductResponse: the message has no rule beyond its fields'. */
export declare const updateProductResponseZod: typeof updateProductResponseZodObject;

/**
 * DeleteProductRequest removes a product.
 *
 * The composable schema of shop.catalog.v1.DeleteProductRequest: every field carries its own rules, so
 * `deleteProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in deleteProductRequestZod.
 */
export declare const deleteProductRequestZodObject: z.ZodObject<{
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  id: z.ZodString;
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  expectedVersion: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/** Full validation of shop.catalog.v1.DeleteProductRequest: the message has no rule beyond its fields'. */
export declare const deleteProductRequestZod: typeof deleteProductRequestZodObject;

/**
 * DeleteProductResponse is intentionally empty.
 *
 * The composable schema of shop.catalog.v1.DeleteProductResponse: every field carries its own rules, so
 * `deleteProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in deleteProductResponseZod.
 */
export declare const deleteProductResponseZodObject: z.ZodObject<{
}, "strict">;

/** Full validation of shop.catalog.v1.DeleteProductResponse: the message has no rule beyond its fields'. */
export declare const deleteProductResponseZod: typeof deleteProductResponseZodObject;
