// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

// Removes the keywords of protoschema-jsonschema's output that reject values
// protovalidate accepts. The generated modules pass in the table of what to
// remove; this module only knows how to find the nodes.

/** Fix drops keywords from one node of a field, e.g. `{ at: "items", drop: ["pattern"] }`. */
export type Fix = { at?: "items" | "propertyNames" | "additionalProperties"; drop: readonly string[] };

/** FieldFixes are the fixes of one field. `alias` is its proto name, e.g. "host_name", when it differs from the JSON name. */
export type FieldFixes = { alias?: string; fixes: readonly Fix[] };

/** Fixes maps a def id to its fields, keyed by JSON name; "" is the def itself. */
export type Fixes = Readonly<Record<string, Readonly<Record<string, FieldFixes>>>>;

type Node = { [keyword: string]: unknown };

/**
 * loosenWith returns a copy of the bundle with every fix applied. The bundle
 * itself is never mutated: every importer of a JSON module shares one object.
 * A def or field the bundle lacks is skipped.
 */
export function loosenWith<T>(fixes: Fixes, bundle: T): T {
  const copy = JSON.parse(JSON.stringify(bundle)) as T;
  const defs = (copy as { $defs?: Record<string, unknown> }).$defs ?? {};

  for (const [id, fields] of Object.entries(fixes)) {
    const def = defs[id];
    if (!isNode(def)) continue;

    for (const [name, field] of Object.entries(fields)) {
      for (const node of fieldNodes(def, name, field.alias)) {
        for (const fix of field.fixes) {
          const target = fix.at === undefined ? node : node[fix.at];
          if (isNode(target)) drop(target, fix.drop);
        }
      }
    }
  }
  return copy;
}

// fieldNodes finds a field under its JSON name in properties, and in every
// patternProperties entry `^(a|b)$` that names it: the lenient alias, the proto
// name, and a field upstream moved there for `// jsonschema:hide`.
function fieldNodes(def: Node, name: string, alias: string | undefined): Node[] {
  if (name === "") return [def];

  const nodes = [child(def.properties, name)];
  const patterns = def.patternProperties;
  if (isNode(patterns)) {
    for (const [key, node] of Object.entries(patterns)) {
      const names = /^\^\((.*)\)\$$/.exec(key)?.[1]?.split("|") ?? [];
      if (names.includes(name) || (alias !== undefined && names.includes(alias))) nodes.push(node);
    }
  }
  return nodes.filter(isNode);
}

// drop deletes the keywords from the node and from every anyOf branch below it.
function drop(node: Node, keywords: readonly string[]): void {
  for (const keyword of keywords) delete node[keyword];

  if (!Array.isArray(node.anyOf)) return;
  for (const branch of node.anyOf) {
    if (isNode(branch)) drop(branch, keywords);
  }
}

function child(parent: unknown, key: string): unknown {
  return isNode(parent) ? parent[key] : undefined;
}

function isNode(value: unknown): value is Node {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * The keywords protoschema-jsonschema writes that reject values protovalidate accepts, by
 * $defs id and field. Each entry names the rule or shape that makes its keyword wrong.
 */
export const fixesTable: Fixes = {
  "example.v1.User.jsonschema.json": {
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
    // string.pattern
    "displayName": { alias: "display_name", fixes: [{ drop: ["pattern"] }] },
  },
  "google.protobuf.BytesValue.jsonschema.json": {
    // bytes: base64 pattern rejects URL-safe
    "": { fixes: [{ drop: ["pattern"] }] },
  },
  "google.protobuf.Duration.jsonschema.json": {
    // google.protobuf.Duration: format is ISO 8601, protojson writes "1.5s"
    "": { fixes: [{ drop: ["format"] }] },
  },
  "shop.catalog.v1.Product.jsonschema.json": {
    // string.pattern
    "sku": { fixes: [{ drop: ["pattern"] }] },
    // repeated.items.string.pattern
    "tags": { fixes: [{ at: "items", drop: ["pattern"] }] },
  },
  "shop.common.v1.LabelSet.jsonschema.json": {
    // map.keys.string.pattern
    "labels": { fixes: [{ at: "propertyNames", drop: ["pattern"] }] },
  },
  "shop.coverage.v1.AmbiguityCoverage.jsonschema.json": {
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
    // ignore = IGNORE_ALWAYS: protovalidate never evaluates the message
    "uncheckedDetail": { alias: "unchecked_detail", fixes: [{ drop: ["$ref"] }] },
    // repeated.items.ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "optionalTags": { alias: "optional_tags", fixes: [{ at: "items", drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
  },
  "shop.coverage.v1.CollectionRuleCoverage.jsonschema.json": {
    // map.keys.string.pattern
    "counters": { fixes: [{ at: "propertyNames", drop: ["pattern"] }] },
  },
  "shop.coverage.v1.NumericRuleCoverage.jsonschema.json": {
    // float.gte
    // float.lte
    "ratio": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "maximum", "minimum"] }] },
  },
  "shop.coverage.v1.PresenceRuleCoverage.jsonschema.json": {
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "skipWhenEmpty": { alias: "skip_when_empty", fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
  },
  "shop.coverage.v1.ScalarRuleCoverage.jsonschema.json": {
    // bytes: base64 pattern rejects URL-safe
    "payload": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "signature": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "remoteIp": { alias: "remote_ip", fixes: [{ drop: ["pattern"] }] },
  },
  "shop.coverage.v1.StringRuleCoverage.jsonschema.json": {
    // string.pattern
    "pattern": { fixes: [{ drop: ["pattern"] }] },
    // string.contains
    // string.prefix
    // string.suffix
    "affixes": { fixes: [{ drop: ["pattern"] }] },
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
    // string.hostname
    "hostname": { fixes: [{ drop: ["pattern"] }] },
    // string.uri
    "uri": { fixes: [{ drop: ["pattern"] }] },
    // string.uri_ref
    "uriRef": { alias: "uri_ref", fixes: [{ drop: ["pattern"] }] },
    // string.ipv6
    "ipv6": { fixes: [{ drop: ["format"] }] },
    // string.ip
    "ip": { fixes: [{ drop: ["pattern"] }] },
    // string.ip_prefix
    "ipPrefix": { alias: "ip_prefix", fixes: [{ drop: ["pattern"] }] },
    // string.host_and_port
    "hostAndPort": { alias: "host_and_port", fixes: [{ drop: ["pattern"] }] },
  },
  "shop.inventory.v1.ContactPoint.jsonschema.json": {
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
    // string.pattern
    "phone": { fixes: [{ drop: ["pattern"] }] },
  },
  "shop.inventory.v1.StockMovement.jsonschema.json": {
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "purchaseOrderId": { alias: "purchase_order_id", fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "customerOrderId": { alias: "customer_order_id", fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
  },
  "shop.inventory.v1.Warehouse.Address.jsonschema.json": {
    // string.pattern
    "countryCode": { alias: "country_code", fixes: [{ drop: ["pattern"] }] },
  },
  "shop.schema.v1.BytesCoverage.jsonschema.json": {
    // bytes: base64 pattern rejects URL-safe
    "raw": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "exactLen": { alias: "exact_len", fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "minLen": { alias: "min_len", fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "maxLen": { alias: "max_len", fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "pattern": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "prefix": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "ip": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "uuid": { fixes: [{ drop: ["pattern"] }] },
    // bytes: base64 pattern rejects URL-safe
    "requiredBlob": { alias: "required_blob", fixes: [{ drop: ["pattern"] }] },
  },
  "shop.schema.v1.CollectionCoverage.jsonschema.json": {
    // repeated.items.string.uri
    "links": { fixes: [{ at: "items", drop: ["pattern"] }] },
    // map.values.string.uri
    "labels": { fixes: [{ at: "additionalProperties", drop: ["pattern"] }] },
    // map<bool, _>: JSON keys are strings
    "flags": { fixes: [{ drop: ["propertyNames"] }] },
  },
  "shop.schema.v1.FormatCoverage.jsonschema.json": {
    // string.hostname
    "hostname": { fixes: [{ drop: ["pattern"] }] },
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
    // string.ip
    "ip": { fixes: [{ drop: ["pattern"] }] },
    // string.ipv6
    "ipv6": { fixes: [{ drop: ["format"] }] },
    // string.uri
    "uri": { fixes: [{ drop: ["pattern"] }] },
    // string.uri_ref
    "uriRef": { alias: "uri_ref", fixes: [{ drop: ["pattern"] }] },
    // string.address
    "address": { fixes: [{ drop: ["pattern"] }] },
    // string.host_and_port
    "hostAndPort": { alias: "host_and_port", fixes: [{ drop: ["pattern"] }] },
    // string.ip_with_prefixlen
    "ipWithPrefixlen": { alias: "ip_with_prefixlen", fixes: [{ drop: ["pattern"] }] },
    // string.ipv6_with_prefixlen
    "ipv6WithPrefixlen": { alias: "ipv6_with_prefixlen", fixes: [{ drop: ["pattern"] }] },
    // string.ip_prefix
    "ipPrefix": { alias: "ip_prefix", fixes: [{ drop: ["pattern"] }] },
    // string.ipv4_prefix
    "ipv4Prefix": { alias: "ipv4_prefix", fixes: [{ drop: ["pattern"] }] },
    // string.ipv6_prefix
    "ipv6Prefix": { alias: "ipv6_prefix", fixes: [{ drop: ["pattern"] }] },
    // string.well_known_regex
    "headerName": { alias: "header_name", fixes: [{ drop: ["pattern"] }] },
    // string.hostname
    "hiddenHost": { alias: "hidden_host", fixes: [{ drop: ["pattern"] }] },
  },
  "shop.schema.v1.IgnoreCoverage.jsonschema.json": {
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "email": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "threshold": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // repeated.items.ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "ids": { fixes: [{ at: "items", drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // map.values.ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "codes": { fixes: [{ at: "additionalProperties", drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
  },
  "shop.schema.v1.ImplicitCoverage.jsonschema.json": {
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
  },
  "shop.schema.v1.MessageOneofCoverage.jsonschema.json": {
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "code": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "tags": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
    // ignore = IGNORE_IF_ZERO_VALUE: upstream writes the keywords anyway
    "color": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "format", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "pattern"] }] },
  },
  "shop.schema.v1.NumberCoverage.jsonschema.json": {
    // float.lte
    "capped": { fixes: [{ drop: ["enum", "exclusiveMaximum", "exclusiveMinimum", "maximum", "minimum"] }] },
  },
  "shop.schema.v1.OneofCoverage.jsonschema.json": {
    // string.email
    "email": { fixes: [{ drop: ["format"] }] },
  },
  "shop.schema.v1.StringContentCoverage.jsonschema.json": {
    // string.len_bytes
    "lenBytes": { alias: "len_bytes", fixes: [{ drop: ["maxLength"] }] },
    // string.pattern
    "patternInlineFlag": { alias: "pattern_inline_flag", fixes: [{ drop: ["pattern"] }] },
    // string.pattern
    "patternNonSpace": { alias: "pattern_non_space", fixes: [{ drop: ["pattern"] }] },
    // string.prefix
    "prefix": { fixes: [{ drop: ["pattern"] }] },
    // string.suffix
    "suffix": { fixes: [{ drop: ["pattern"] }] },
    // string.contains
    "contains": { fixes: [{ drop: ["pattern"] }] },
    // string.prefix
    // string.suffix
    "prefixAndSuffix": { alias: "prefix_and_suffix", fixes: [{ drop: ["pattern"] }] },
    // string.pattern
    "uuidPattern": { alias: "uuid_pattern", fixes: [{ drop: ["pattern"] }] },
    // string.prefix
    "escaped": { fixes: [{ drop: ["pattern"] }] },
  },
  "shop.schema.v1.TreeNode.jsonschema.json": {
    // ignore = IGNORE_ALWAYS: protovalidate never evaluates the message
    "skipped": { fixes: [{ drop: ["$ref"] }] },
  },
};

/**
 * Copies a protoschema-jsonschema bundle without the keywords in fixesTable. The import is
 * never mutated: every importer of a JSON module shares the same object.
 */
export function loosen<T>(bundle: T): T {
  return loosenWith(fixesTable, bundle);
}
