// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

// Removes the keywords of protoschema-jsonschema's output that reject values
// protovalidate accepts. The generated modules pass in the table of what to
// remove; this module only knows how to find the nodes.

/** Fix drops keywords from one node of a field, e.g. `{ at: "items", drop: ["pattern"] }`. */
export type Fix = { at?: "items" | "propertyNames" | "additionalProperties"; drop: readonly string[] };

/** FieldFixes are the fixes of one field. `alias` is its proto name, e.g. "host_name", when it differs from the JSON name. */
export type FieldFixes = { alias?: string; fixes: readonly Fix[] };

/** Fixes maps a def id to its fields, keyed by JSON name; "" is the def itself. */
export type Fixes = Readonly<Record<string, Readonly<Record<string, FieldFixes>>>>;

/**
 * loosenWith returns a copy of the bundle with every fix applied. The bundle
 * itself is never mutated: every importer of a JSON module shares one object.
 * A def or field the bundle lacks is skipped.
 */
export declare function loosenWith<T>(fixes: Fixes, bundle: T): T;

/**
 * The keywords protoschema-jsonschema writes that reject values protovalidate accepts, by
 * $defs id and field. Each entry names the rule or shape that makes its keyword wrong.
 */
export declare const fixesTable: Fixes;

/**
 * Copies a protoschema-jsonschema bundle without the keywords in fixesTable. The import is
 * never mutated: every importer of a JSON module shares the same object.
 */
export declare function loosen<T>(bundle: T): T;
