// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

import { createMutableRegistry, fromJson } from "@bufbuild/protobuf";
import { nestedTypes } from "@bufbuild/protobuf/reflect";
import { CompilationError, createValidator } from "@bufbuild/protovalidate";

// Zod refinements that run protovalidate-es and report its violations as
// issues. Nothing here imports zod: the context is only asked for addIssue,
// which both majors share, so one module serves the zod and zod3 targets.

// protovalidate plans each message type once, so one validator serves all.
const validator = createValidator();

// Every type an imported .zod.js module declares, so fromJson can decode a
// google.protobuf.Any that packs one of them. Filled by register() at import.
const registry = createMutableRegistry();
const registered = new Set();

/**
 * register adds a file's types, and its dependencies', to the registry fromJson
 * decodes a google.protobuf.Any with. Each generated module calls it once for
 * its own file.
 */
export function register(file) {
  if (registered.has(file.name)) return;
  registered.add(file.name);
  for (const dependency of file.dependencies) register(dependency);
  for (const type of nestedTypes(file)) {
    if (type.kind !== "service") registry.add(type);
  }
}

// A required key is already enforced by the Zod object.
const requiredRule = "required";

// What message() knows of the refinements nearer a value: the native rules of
// every field field() checks, and every message type message() checks. Filled
// as the generated modules build their schemas, before any value is parsed.
const refined = new Map();
const checked = new Set();

/**
 * field checks one field on its own: the message is built with only that field
 * set, and only the violations on the field itself, its list items or its map
 * entries are kept. `name` is the proto field name; `native` lists the rule
 * paths ("string.min_len") the Zod schema already checks.
 */
export function field(desc, name, native = []) {
  const target = desc.fields.find((f) => f.name === name);
  if (target === undefined) {
    throw new Error(`${desc.typeName} has no field ${name}`);
  }
  refined.set(target, native);

  return (value, ctx) => {
    const msg = decode(desc, { [target.jsonName]: value });
    if (typeof msg === "string") return report(ctx, msg);

    // An evaluation error is message()'s to report: every other field of this
    // sparse message holds its zero value, which a rule elsewhere may not expect.
    const result = validator.validate(desc, msg);
    if (result.kind !== "invalid") return;

    for (const v of result.violations) {
      const [head, ...rest] = v.field;

      // A path into a nested message belongs to that message's own schema.
      if (head !== target || !rest.every(isSubscript)) continue;
      if (native.includes(rulePath(v))) continue;

      ctx.addIssue({ code: "custom", message: v.message, path: toJsonPath(rest), params: { ruleId: v.ruleId } });
    }
  };
}

/**
 * message checks what spans the whole message: message CEL, oneofs, and the
 * zero value of every absent field, which protojson omits but protovalidate
 * still validates. Present fields are left to their own schema, unless a rule
 * elsewhere kept field() from evaluating them.
 */
export function message(desc) {
  checked.add(desc);

  return (value, ctx) => {
    const input = value;
    const msg = decode(desc, input);
    if (typeof msg === "string") return reportDecode(desc, input, msg, ctx);

    for (const v of violations(validator.validate(desc, msg), ctx)) {
      const head = v.field[0];

      if (head?.kind === "field") {
        if (rulePath(v) === requiredRule) continue;
        if (input[head.jsonName] !== undefined && !unreported(desc, head, v, input[head.jsonName])) continue;
      }

      ctx.addIssue({ code: "custom", message: v.message, path: toJsonPath(v.field), params: { ruleId: v.ruleId } });
    }
  };
}

// unreported tells whether a violation on a present field is one field()
// checks but could not report: its sparse message failed to evaluate, because
// a rule elsewhere does not expect the zero value of another field.
function unreported(desc, f, v, value) {
  const native = refined.get(f);
  if (native === undefined || native.includes(rulePath(v)) || !v.field.slice(1).every(isSubscript)) return false;

  const msg = decode(desc, { [f.jsonName]: value });
  return typeof msg !== "string" && validator.validate(desc, msg).kind === "error";
}

// decode decodes the JSON the way protojson does, or returns why it cannot: a
// malformed value, two members of one oneof.
function decode(desc, json) {
  try {
    return fromJson(desc, json, { registry });
  } catch (e) {
    return e instanceof Error ? e.message : String(e);
  }
}

// reportDecode reports why a whole message does not decode, at the field that
// causes it, and not at all when a refinement nearer the value reports it:
// field() for a field it checks, message() for a nested message. With no one
// field to blame, as when two members of one oneof are set, it goes on the
// message.
function reportDecode(desc, input, reason, ctx) {
  const culprit = desc.fields.find(
    (f) => input[f.jsonName] !== undefined && typeof decode(desc, { [f.jsonName]: input[f.jsonName] }) === "string",
  );
  if (culprit === undefined) return report(ctx, reason);
  if (refined.has(culprit) || (culprit.message !== undefined && checked.has(culprit.message))) return;
  report(ctx, reason, [culprit.jsonName]);
}

// The fromJson failure that says nothing about the value: an Any packs a type
// no imported module registered. The server, whose registry has it, decides.
const unregistered = /is not in the type registry/;

// report adds a decode failure as one issue. A value this module cannot decode
// for want of a type is not checked at all: under-narrowing is the safe
// direction.
function report(ctx, reason, path = []) {
  if (!unregistered.test(reason)) ctx.addIssue({ code: "custom", message: reason, path });
}

// violations are a result's violations, with an evaluation error as one issue.
// A compilation error, such as a predefined rule whose extension this module
// was not given, says nothing about the value, and is not checked either.
function violations(result, ctx) {
  if (result.kind === "error") {
    if (!(result.error instanceof CompilationError)) ctx.addIssue({ code: "custom", message: result.error.message });
    return [];
  }
  return result.violations ?? [];
}

function isSubscript(s) {
  return s.kind === "list_sub" || s.kind === "map_sub";
}

// rulePath names the violated rule by its proto field names, e.g.
// "repeated.items.string.min_len"; "cel" for a CEL rule.
function rulePath(v) {
  return v.rule
    .filter((s) => s.kind === "field")
    .map((s) => s.name)
    .join(".");
}

// toJsonPath spells a protovalidate path the way the JSON is written: JSON
// names, oneofs flattened, list indexes as numbers, map keys as strings.
function toJsonPath(path) {
  return path.flatMap((s) => {
    switch (s.kind) {
      case "list_sub":
        return [s.index];
      case "map_sub":
        return [String(s.key)];
      case "oneof":
        return [];
      default:
        return [s.jsonName];
    }
  });
}
