// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

import { z } from "zod";

// The well-known types, in the canonical protojson form protobuf-es's toJson
// emits and its *Json types describe.

export declare const timestampZod: z.ZodString;
export declare const durationZod: z.ZodString;
export declare const fieldMaskZod: z.ZodString;

export declare const valueZod: z.ZodJSONSchema;
export declare const structZod: z.ZodRecord<z.ZodString, z.ZodJSONSchema>;
export declare const listValueZod: z.ZodArray<z.ZodJSONSchema>;
export declare const nullValueZod: z.ZodNull;

// An empty Any is written as {}, so "@type" is optional.
export declare const anyZod: z.ZodObject<{ "@type": z.ZodOptional<z.ZodString> }, z.core.$loose>;
export declare const emptyZod: z.ZodObject<{}, z.core.$strict>;

export declare const boolValueZod: z.ZodBoolean;
export declare const bytesValueZod: z.ZodString;
export declare const doubleValueZod: z.ZodUnion<
  readonly [z.ZodNumber, z.ZodEnum<{ NaN: "NaN"; Infinity: "Infinity"; "-Infinity": "-Infinity" }>]
>;
export declare const floatValueZod: typeof doubleValueZod;
export declare const int32ValueZod: z.ZodNumber;
export declare const int64ValueZod: z.ZodString;
export declare const stringValueZod: z.ZodString;
export declare const uInt32ValueZod: z.ZodNumber;
export declare const uInt64ValueZod: z.ZodString;
