// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: shop/catalog/v1/product.proto

import type { Narrow, Require, Uuid } from "../../../strict/types";
import type { CreateProductRequest, CreateProductResponse, DeleteProductRequest, DeleteProductResponse, GetProductRequest, GetProductResponse, ListProductsRequest, ListProductsResponse, Product, ProductStatus, UpdateProductRequest, UpdateProductResponse } from "./product_pb";
import { CatalogService, CreateProductRequestSchema, CreateProductResponseSchema, DeleteProductRequestSchema, DeleteProductResponseSchema, GetProductRequestSchema, GetProductResponseSchema, ListProductsRequestSchema, ListProductsResponseSchema, ProductSchema, UpdateProductRequestSchema, UpdateProductResponseSchema } from "./product_pb";
import type { MoneyStrict, SortDirectionStrict } from "../../common/v1/common.strict";
import type { GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";

/**
 * ProductStatus is the lifecycle state of a product.
 *
 * Without PRODUCT_STATUS_UNSPECIFIED, the member protobuf numbers 0, which this overlay
 * reads as "unset" rather than a value. No buf.validate rule says so; the
 * convention that names it <ENUM>_UNSPECIFIED does.
 */
export type ProductStatusStrict = Exclude<ProductStatus, 0>;

/**
 * Product is the catalog resource.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[product.discount_below_price]
 *     !has(this.discount_price) || this.discount_price.units < this.price.units
 *     message: discount_price must be lower than price
 *   cel[product.draft_not_published]
 *     this.status != 3 || !has(this.published_at)
 *     message: a draft product cannot have published_at set
 *   sku
 *     string.max_len = 32
 *     string.min_len = 3
 *     string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$
 *   name
 *     string.max_len = 200
 *     string.min_len = 1
 *   description
 *     string.max_len = 4096
 *   tags
 *     repeated.items.string.max_len = 40
 *     repeated.items.string.min_len = 1
 *     repeated.items.string.pattern = ^[a-z0-9-]+$
 *     repeated.max_items = 20
 *     repeated.unique = true
 *   labels
 *     map.max_pairs = 16
 *   created_by_email
 *     cel[product.created_by_email]: this.size() == 0 || this.isEmail()
 *       message: if set, created_by_email must be a valid email address
 *       refs: this
 *       calls: _==_, _||_, isEmail, size
 *   version
 *     int64.gte = 0
 */
export type ProductStrict = Require<Narrow<Product, {
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  id: Uuid;
  /**
   * required
   *
   * Carried into the type: required.
   */
  price: MoneyStrict;
  discountPrice: MoneyStrict;
  /** enum.defined_only = true */
  status: ProductStatusStrict;
}>, "price">;

/**
 * Every field of shop.catalog.v1.Product the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const ProductOutputOnlyFields = [
  "id",
  "created_by_email",
  "created_at",
  "created_at.seconds",
  "created_at.nanos",
  "updated_at",
  "updated_at.seconds",
  "updated_at.nanos",
  "published_at",
  "published_at.seconds",
  "published_at.nanos",
  "version",
] as const;

/**
 * CreateProductRequest creates a new product.
 *
 * Carried into the type: cel[create_product.no_read_only_fields].
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[create_product.no_read_only_fields]
 *     this.product.version == 0
 *     message: read-only fields (id, created_at, updated_at, version) must not be set
 */
export type CreateProductRequestStrict = Require<Narrow<CreateProductRequest, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  product: Narrow<ProductStrict, { id: ProductStrict["id"] & ""; createdAt: never; updatedAt: never; }>;
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  idempotencyKey: Uuid;
}>, "product">;

/**
 * Every field of shop.catalog.v1.CreateProductRequest the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const CreateProductRequestOutputOnlyFields = [
  "product.id",
  "product.created_by_email",
  "product.created_at",
  "product.created_at.seconds",
  "product.created_at.nanos",
  "product.updated_at",
  "product.updated_at.seconds",
  "product.updated_at.nanos",
  "product.published_at",
  "product.published_at.seconds",
  "product.published_at.nanos",
  "product.version",
] as const;

/** CreateProductResponse returns the stored product. */
export type CreateProductResponseStrict = Narrow<CreateProductResponse, {
  product: ProductStrict;
}>;

/**
 * Every field of shop.catalog.v1.CreateProductResponse the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const CreateProductResponseOutputOnlyFields = [
  "product.id",
  "product.created_by_email",
  "product.created_at",
  "product.created_at.seconds",
  "product.created_at.nanos",
  "product.updated_at",
  "product.updated_at.seconds",
  "product.updated_at.nanos",
  "product.published_at",
  "product.published_at.seconds",
  "product.published_at.nanos",
  "product.version",
] as const;

/** GetProductRequest looks a product up by id or by SKU. */
export type GetProductRequestStrict = Narrow<GetProductRequest, {
  /**
   * required oneof key: exactly one of id, sku
   * id: string.uuid = true
   * sku: string.min_len = 3
   */
  key: Exclude<GetProductRequest["key"], { case: undefined }>;
}>;

/** GetProductResponse returns a single product. */
export type GetProductResponseStrict = Narrow<GetProductResponse, {
  product: ProductStrict;
}>;

/**
 * Every field of shop.catalog.v1.GetProductResponse the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const GetProductResponseOutputOnlyFields = [
  "product.id",
  "product.created_by_email",
  "product.created_at",
  "product.created_at.seconds",
  "product.created_at.nanos",
  "product.updated_at",
  "product.updated_at.seconds",
  "product.updated_at.nanos",
  "product.published_at",
  "product.published_at.seconds",
  "product.published_at.nanos",
  "product.version",
] as const;

/**
 * ListProductsRequest pages through the catalog.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[list_products.price_bounds]
 *     has(this.min_price) == has(this.max_price)
 *     message: min_price and max_price must be set together
 *   name_contains
 *     string.max_len = 200
 *     string.min_len = 1
 *   order_by
 *     string.in = [, name, sku, created_at, price]
 */
export type ListProductsRequestStrict = Require<Narrow<ListProductsRequest, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  pagination: NonNullable<ListProductsRequest["pagination"]>;
  /**
   * repeated.items.enum.defined_only = true
   * repeated.items.enum.not_in = [0]
   */
  statuses: ProductStatusStrict[];
  minPrice: MoneyStrict;
  maxPrice: MoneyStrict;
  /** enum.defined_only = true */
  orderDirection: SortDirectionStrict;
}>, "pagination">;

/**
 * ListProductsResponse is one page of products.
 *
 * Left to runtime validation, having no type equivalent:
 *   total_size
 *     int64.gte = 0
 */
export type ListProductsResponseStrict = Narrow<ListProductsResponse, {
  products: ProductStrict[];
}>;

/**
 * UpdateProductRequest performs a partial update.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[update_product.id_present]
 *     this.product.id != ""
 *     message: product.id is required for an update
 */
export type UpdateProductRequestStrict = Require<Narrow<UpdateProductRequest, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  product: ProductStrict;
}>, "product">;

/**
 * Every field of shop.catalog.v1.UpdateProductRequest the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const UpdateProductRequestOutputOnlyFields = [
  "product.id",
  "product.created_by_email",
  "product.created_at",
  "product.created_at.seconds",
  "product.created_at.nanos",
  "product.updated_at",
  "product.updated_at.seconds",
  "product.updated_at.nanos",
  "product.published_at",
  "product.published_at.seconds",
  "product.published_at.nanos",
  "product.version",
] as const;

/** UpdateProductResponse returns the stored product. */
export type UpdateProductResponseStrict = Narrow<UpdateProductResponse, {
  product: ProductStrict;
}>;

/**
 * Every field of shop.catalog.v1.UpdateProductResponse the server assigns: those declared
 * `(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the
 * server owns the whole subtree. Dotted proto paths, so they can be subtracted from
 * a google.protobuf.FieldMask.
 */
export const UpdateProductResponseOutputOnlyFields = [
  "product.id",
  "product.created_by_email",
  "product.created_at",
  "product.created_at.seconds",
  "product.created_at.nanos",
  "product.updated_at",
  "product.updated_at.seconds",
  "product.updated_at.nanos",
  "product.published_at",
  "product.published_at.seconds",
  "product.published_at.nanos",
  "product.version",
] as const;

/**
 * DeleteProductRequest removes a product.
 *
 * Left to runtime validation, having no type equivalent:
 *   expected_version
 *     int64.gte = 0
 */
export type DeleteProductRequestStrict = Narrow<DeleteProductRequest, {
  /**
   * required
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  id: Uuid;
}>;

/** DeleteProductResponse is intentionally empty. */
export type DeleteProductResponseStrict = DeleteProductResponse;

/**
 * Describes shop.catalog.v1.Product, reporting ProductStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const ProductStrictSchema =
  ProductSchema as GenMessage<Product, { validType: ProductStrict }>;

/**
 * Describes shop.catalog.v1.CreateProductRequest, reporting CreateProductRequestStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const CreateProductRequestStrictSchema =
  CreateProductRequestSchema as GenMessage<CreateProductRequest, { validType: CreateProductRequestStrict }>;

/**
 * Describes shop.catalog.v1.CreateProductResponse, reporting CreateProductResponseStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const CreateProductResponseStrictSchema =
  CreateProductResponseSchema as GenMessage<CreateProductResponse, { validType: CreateProductResponseStrict }>;

/**
 * Describes shop.catalog.v1.GetProductRequest, reporting GetProductRequestStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const GetProductRequestStrictSchema =
  GetProductRequestSchema as GenMessage<GetProductRequest, { validType: GetProductRequestStrict }>;

/**
 * Describes shop.catalog.v1.GetProductResponse, reporting GetProductResponseStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const GetProductResponseStrictSchema =
  GetProductResponseSchema as GenMessage<GetProductResponse, { validType: GetProductResponseStrict }>;

/**
 * Describes shop.catalog.v1.ListProductsRequest, reporting ListProductsRequestStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const ListProductsRequestStrictSchema =
  ListProductsRequestSchema as GenMessage<ListProductsRequest, { validType: ListProductsRequestStrict }>;

/**
 * Describes shop.catalog.v1.ListProductsResponse, reporting ListProductsResponseStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const ListProductsResponseStrictSchema =
  ListProductsResponseSchema as GenMessage<ListProductsResponse, { validType: ListProductsResponseStrict }>;

/**
 * Describes shop.catalog.v1.UpdateProductRequest, reporting UpdateProductRequestStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const UpdateProductRequestStrictSchema =
  UpdateProductRequestSchema as GenMessage<UpdateProductRequest, { validType: UpdateProductRequestStrict }>;

/**
 * Describes shop.catalog.v1.UpdateProductResponse, reporting UpdateProductResponseStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const UpdateProductResponseStrictSchema =
  UpdateProductResponseSchema as GenMessage<UpdateProductResponse, { validType: UpdateProductResponseStrict }>;

/**
 * Describes shop.catalog.v1.DeleteProductRequest, reporting DeleteProductRequestStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const DeleteProductRequestStrictSchema =
  DeleteProductRequestSchema as GenMessage<DeleteProductRequest, { validType: DeleteProductRequestStrict }>;

type CatalogServiceStrictDescriptor = GenService<{
  /** Create a new product. */
  createProduct: {
    methodKind: "unary";
    input: typeof CreateProductRequestStrictSchema;
    output: typeof CreateProductResponseStrictSchema;
  },
  /** Fetch a single product. */
  getProduct: {
    methodKind: "unary";
    input: typeof GetProductRequestStrictSchema;
    output: typeof GetProductResponseStrictSchema;
  },
  /** Page through products. */
  listProducts: {
    methodKind: "unary";
    input: typeof ListProductsRequestStrictSchema;
    output: typeof ListProductsResponseStrictSchema;
  },
  /** Partially update a product. */
  updateProduct: {
    methodKind: "unary";
    input: typeof UpdateProductRequestStrictSchema;
    output: typeof UpdateProductResponseStrictSchema;
  },
  /** Delete a product. */
  deleteProduct: {
    methodKind: "unary";
    input: typeof DeleteProductRequestStrictSchema;
    output: typeof DeleteProductResponseSchema;
  },
}>;

/**
 * CatalogService manages products.
 * The same service descriptor protoc-gen-es generated, retyped so every method reports
 * the strict input and output types.
 */
export const CatalogServiceStrict =
  CatalogService as CatalogServiceStrictDescriptor;

