# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/catalog/v1/product.proto
"""buf.validate rules for shop/catalog/v1/product.proto.

One typing.Annotated alias per constrained field, over the type
protoc-gen-python already declared. The message classes stay in
shop.catalog.v1.product_pb2; import them from there.

A rule with an annotated_types equivalent is carried as that constructor,
which pydantic, msgspec and beartype enforce. The rest are metadata strings,
left to protovalidate at runtime.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated

from annotated_types import Ge, MaxLen, MinLen

from google.protobuf import timestamp_pb2 as _google_protobuf_timestamp_pb2
from shop.common.v1 import common_pb2 as _shop_common_v1_common_pb2
from shop.catalog.v1.product_pb2 import Product, ProductStatus

# ProductStatus is the lifecycle state of a product.
# Without PRODUCT_STATUS_UNSPECIFIED, the member protobuf numbers 0, which this overlay
# reads as "unset" rather than a value. No buf.validate rule says so; the
# convention that names it <ENUM>_UNSPECIFIED does.
ProductStatusStrict = Annotated[
    ProductStatus,
    Ge(1),
]

# Product is the catalog resource.
# cel[product.discount_below_price]: !has(this.discount_price) || this.discount_price.units < this.price.units
#   message: discount_price must be lower than price
#   refs: discount_price, price, this, units
#   calls: !_, _<_, _||_
# cel[product.draft_not_published]: this.status != 3 || !has(this.published_at)
#   message: a draft product cannot have published_at set
#   refs: published_at, status, this
#   calls: !_, _!=_, _||_
ProductId = Annotated[
    str,
    "google.api.field_behavior = OUTPUT_ONLY",
    "string.uuid = true",
]
ProductSku = Annotated[
    str,
    MaxLen(32),
    MinLen(3),
    "string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$",
]
ProductName = Annotated[
    str,
    MaxLen(200),
    MinLen(1),
]
ProductDescription = Annotated[
    str,
    MaxLen(4096),
]
ProductPrice = Annotated[
    _shop_common_v1_common_pb2.Money,
    "required",
]
ProductStatus_ = Annotated[
    ProductStatusStrict,
    "enum.defined_only = true",
]
ProductTags = Annotated[
    Sequence[str],
    "repeated.items.string.max_len = 40",
    "repeated.items.string.min_len = 1",
    "repeated.items.string.pattern = ^[a-z0-9-]+$",
    MaxLen(20),
    "repeated.unique = true",
]
ProductLabels = Annotated[
    Mapping[str, str],
    MaxLen(16),
]
ProductCreatedByEmail = Annotated[
    str,
    "google.api.field_behavior = OUTPUT_ONLY",
    "cel[product.created_by_email]: this.size() == 0 || this.isEmail()",
    "  message: if set, created_by_email must be a valid email address",
    "  refs: this",
    "  calls: _==_, _||_, isEmail, size",
]
ProductCreatedAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "google.api.field_behavior = OUTPUT_ONLY",
]
ProductUpdatedAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "google.api.field_behavior = OUTPUT_ONLY",
]
ProductPublishedAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "google.api.field_behavior = OUTPUT_ONLY",
]
ProductVersion = Annotated[
    int,
    "google.api.field_behavior = OUTPUT_ONLY",
    Ge(0),
]

# Every field of shop.catalog.v1.Product the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
ProductOutputOnlyFields = (
    "id",
    "created_by_email",
    "created_at",
    "created_at.seconds",
    "created_at.nanos",
    "updated_at",
    "updated_at.seconds",
    "updated_at.nanos",
    "published_at",
    "published_at.seconds",
    "published_at.nanos",
    "version",
)

# CreateProductRequest creates a new product.
# cel[create_product.no_read_only_fields]: this.product.id == '' && !has(this.product.created_at) && !has(this.product.updated_at) && this.product.version == 0
#   message: read-only fields (id, created_at, updated_at, version) must not be set
#   refs: created_at, id, product, this, updated_at, version
#   calls: !_, _&&_, _==_
CreateProductRequestProduct = Annotated[
    Product,
    "required",
]
CreateProductRequestIdempotencyKey = Annotated[
    str,
    "string.uuid = true",
]

# Every field of shop.catalog.v1.CreateProductRequest the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
CreateProductRequestOutputOnlyFields = (
    "product.id",
    "product.created_by_email",
    "product.created_at",
    "product.created_at.seconds",
    "product.created_at.nanos",
    "product.updated_at",
    "product.updated_at.seconds",
    "product.updated_at.nanos",
    "product.published_at",
    "product.published_at.seconds",
    "product.published_at.nanos",
    "product.version",
)

# CreateProductResponse returns the stored product.
# Every field of shop.catalog.v1.CreateProductResponse the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
CreateProductResponseOutputOnlyFields = (
    "product.id",
    "product.created_by_email",
    "product.created_at",
    "product.created_at.seconds",
    "product.created_at.nanos",
    "product.updated_at",
    "product.updated_at.seconds",
    "product.updated_at.nanos",
    "product.published_at",
    "product.published_at.seconds",
    "product.published_at.nanos",
    "product.version",
)

# GetProductRequest looks a product up by id or by SKU.
# required oneof key: exactly one of id, sku
GetProductRequestId = Annotated[
    str,
    "string.uuid = true",
]
GetProductRequestSku = Annotated[
    str,
    MinLen(3),
]

# GetProductResponse returns a single product.
# Every field of shop.catalog.v1.GetProductResponse the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
GetProductResponseOutputOnlyFields = (
    "product.id",
    "product.created_by_email",
    "product.created_at",
    "product.created_at.seconds",
    "product.created_at.nanos",
    "product.updated_at",
    "product.updated_at.seconds",
    "product.updated_at.nanos",
    "product.published_at",
    "product.published_at.seconds",
    "product.published_at.nanos",
    "product.version",
)

# ListProductsRequest pages through the catalog.
# cel[list_products.price_bounds]: has(this.min_price) == has(this.max_price)
#   message: min_price and max_price must be set together
#   refs: max_price, min_price, this
#   calls: _==_
ListProductsRequestPagination = Annotated[
    _shop_common_v1_common_pb2.Pagination,
    "required",
]
ListProductsRequestStatuses = Annotated[
    Sequence[ProductStatusStrict],
    "repeated.items.enum.defined_only = true",
    "repeated.items.enum.not_in = [0]",
]
ListProductsRequestNameContains = Annotated[
    str,
    MaxLen(200),
    MinLen(1),
]
ListProductsRequestOrderBy = Annotated[
    str,
    "string.in = [, name, sku, created_at, price]",
]
ListProductsRequestOrderDirection = Annotated[
    _shop_common_v1_common_pb2.SortDirection,
    "enum.defined_only = true",
]

# ListProductsResponse is one page of products.
ListProductsResponseTotalSize = Annotated[
    int,
    Ge(0),
]

# UpdateProductRequest performs a partial update.
# cel[update_product.id_present]: this.product.id != ''
#   message: product.id is required for an update
#   refs: id, product, this
#   calls: _!=_
UpdateProductRequestProduct = Annotated[
    Product,
    "required",
]

# Every field of shop.catalog.v1.UpdateProductRequest the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
UpdateProductRequestOutputOnlyFields = (
    "product.id",
    "product.created_by_email",
    "product.created_at",
    "product.created_at.seconds",
    "product.created_at.nanos",
    "product.updated_at",
    "product.updated_at.seconds",
    "product.updated_at.nanos",
    "product.published_at",
    "product.published_at.seconds",
    "product.published_at.nanos",
    "product.version",
)

# UpdateProductResponse returns the stored product.
# Every field of shop.catalog.v1.UpdateProductResponse the server assigns: those declared
# (google.api.field_behavior) = OUTPUT_ONLY and everything under one, since the
# server owns the whole subtree. Dotted proto paths, so they can be subtracted from
# a google.protobuf.FieldMask.
UpdateProductResponseOutputOnlyFields = (
    "product.id",
    "product.created_by_email",
    "product.created_at",
    "product.created_at.seconds",
    "product.created_at.nanos",
    "product.updated_at",
    "product.updated_at.seconds",
    "product.updated_at.nanos",
    "product.published_at",
    "product.published_at.seconds",
    "product.published_at.nanos",
    "product.version",
)

# DeleteProductRequest removes a product.
DeleteProductRequestId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
DeleteProductRequestExpectedVersion = Annotated[
    int,
    Ge(0),
]

# DeleteProductResponse is intentionally empty.

