# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/catalog/v1/product.proto
"""buf.validate rules for shop/catalog/v1/product.proto.

Types come from shop.catalog.v1.product_pb2 and are re-exported here, so one
import gives a caller both the message class and its annotated field types.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated

from shop.common.v1 import common_pb2 as _shop_common_v1_common_pb2
from shop.catalog.v1.product_pb2 import (
    CreateProductRequest as CreateProductRequest,
    CreateProductResponse as CreateProductResponse,
    DeleteProductRequest as DeleteProductRequest,
    DeleteProductResponse as DeleteProductResponse,
    GetProductRequest as GetProductRequest,
    GetProductResponse as GetProductResponse,
    ListProductsRequest as ListProductsRequest,
    ListProductsResponse as ListProductsResponse,
    Product as Product,
    ProductStatus as ProductStatus,
    UpdateProductRequest as UpdateProductRequest,
    UpdateProductResponse as UpdateProductResponse,
)

# Product is the catalog resource.
# cel[product.discount_below_price]: !has(this.discount_price) || this.discount_price.units < this.price.units
#   message: discount_price must be lower than price
#   refs: discount_price, price, this, units
#   calls: !_, _<_, _||_
# cel[product.draft_not_published]: this.status != 3 || !has(this.published_at)
#   message: a draft product cannot have published_at set
#   refs: published_at, status, this
#   calls: !_, _!=_, _||_
ProductId = Annotated[
    str,
    "string.uuid = true",
]
ProductSku = Annotated[
    str,
    "string.max_len = 32",
    "string.min_len = 3",
    "string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$",
]
ProductName = Annotated[
    str,
    "string.max_len = 200",
    "string.min_len = 1",
]
ProductDescription = Annotated[
    str,
    "string.max_len = 4096",
]
ProductPrice = Annotated[
    _shop_common_v1_common_pb2.Money,
    "required",
]
ProductStatus_ = Annotated[
    ProductStatus,
    "enum.defined_only = true",
]
ProductTags = Annotated[
    Sequence[str],
    "repeated.items.string.max_len = 40",
    "repeated.items.string.min_len = 1",
    "repeated.items.string.pattern = ^[a-z0-9-]+$",
    "repeated.max_items = 20",
    "repeated.unique = true",
]
ProductLabels = Annotated[
    Mapping[str, str],
    "map.max_pairs = 16",
]
ProductCreatedByEmail = Annotated[
    str,
    "cel[product.created_by_email]: this.size() == 0 || this.isEmail()",
    "  message: if set, created_by_email must be a valid email address",
    "  refs: this",
    "  calls: _==_, _||_, isEmail, size",
]
ProductVersion = Annotated[
    int,
    "int64.gte = 0",
]

# CreateProductRequest creates a new product.
# cel[create_product.no_read_only_fields]: this.product.id == '' && !has(this.product.created_at) && !has(this.product.updated_at) && this.product.version == 0
#   message: read-only fields (id, created_at, updated_at, version) must not be set
#   refs: created_at, id, product, this, updated_at, version
#   calls: !_, _&&_, _==_
CreateProductRequestProduct = Annotated[
    Product,
    "required",
]
CreateProductRequestIdempotencyKey = Annotated[
    str,
    "string.uuid = true",
]

# CreateProductResponse returns the stored product.

# GetProductRequest looks a product up by id or by SKU.
# required oneof key: exactly one of id, sku
GetProductRequestId = Annotated[
    str,
    "string.uuid = true",
]
GetProductRequestSku = Annotated[
    str,
    "string.min_len = 3",
]

# GetProductResponse returns a single product.

# ListProductsRequest pages through the catalog.
# cel[list_products.price_bounds]: has(this.min_price) == has(this.max_price)
#   message: min_price and max_price must be set together
#   refs: max_price, min_price, this
#   calls: _==_
ListProductsRequestPagination = Annotated[
    _shop_common_v1_common_pb2.Pagination,
    "required",
]
ListProductsRequestStatuses = Annotated[
    Sequence[ProductStatus],
    "repeated.items.enum.defined_only = true",
    "repeated.items.enum.not_in = [0]",
]
ListProductsRequestNameContains = Annotated[
    str,
    "string.max_len = 200",
    "string.min_len = 1",
]
ListProductsRequestOrderBy = Annotated[
    str,
    "string.in = [, name, sku, created_at, price]",
]
ListProductsRequestOrderDirection = Annotated[
    _shop_common_v1_common_pb2.SortDirection,
    "enum.defined_only = true",
]

# ListProductsResponse is one page of products.
ListProductsResponseTotalSize = Annotated[
    int,
    "int64.gte = 0",
]

# UpdateProductRequest performs a partial update.
# cel[update_product.id_present]: this.product.id != ''
#   message: product.id is required for an update
#   refs: id, product, this
#   calls: _!=_
UpdateProductRequestProduct = Annotated[
    Product,
    "required",
]

# UpdateProductResponse returns the stored product.

# DeleteProductRequest removes a product.
DeleteProductRequestId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
DeleteProductRequestExpectedVersion = Annotated[
    int,
    "int64.gte = 0",
]

# DeleteProductResponse is intentionally empty.

