// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: example/v1/user.proto

import addressBundle from "../../jsonschema/example.v1.Address.jsonschema.bundle.json" with { type: "json" };
import userBundle from "../../jsonschema/example.v1.User.jsonschema.bundle.json" with { type: "json" };
import { loosen } from "../../strict/jsonschema";

/**
 * User demonstrates standard buf.validate rules alongside custom CEL rules.
 *
 * JSON Schema 2020-12 for example.v1.User, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   id
 *     cel[user.id.prefix]: this.startsWith('usr_')
 *       message: id must start with 'usr_'
 *       refs: this
 *       calls: startsWith
 *   email
 *     string.email = true
 *   display_name
 *     string.pattern = ^[a-zA-Z0-9_ ]+$
 *   age
 *     int32.gt = 0
 *     int32.lte = 130
 *   login_count
 *     cel[this >= 0]: this >= 0
 *       refs: this
 *       calls: _>=_
 *   roles
 *     repeated.unique = true
 *   absent fields
 *     id, display_name, age, login_count, roles: an absent key is the zero value, which the rules still apply to
 */
export const userJsonSchema = loosen(userBundle);

/**
 * Address is referenced by User to exercise message-typed fields.
 *
 * JSON Schema 2020-12 for example.v1.Address, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   absent fields
 *     country, postal_code: an absent key is the zero value, which the rules still apply to
 */
export const addressJsonSchema = loosen(addressBundle);
