// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/schema/v1/schema.proto

import { z } from "zod/v3";
import { field, message, register } from "../../../strict/protovalidate";
import { anyZod, boolValueZod, bytesValueZod, doubleValueZod, durationZod, emptyZod, fieldMaskZod, floatValueZod, int32ValueZod, int64ValueZod, listValueZod, nullValueZod, stringValueZod, structZod, timestampZod, uInt32ValueZod, uInt64ValueZod, valueZod } from "../../../strict/wkt.zod3";
import { BytesCoverageSchema, CollectionCoverageSchema, EvaluationCoverageSchema, FormatCoverageSchema, IgnoreCoverageSchema, ImplicitCoverageSchema, ItemSchema, JsonNameCoverageSchema, MessageCelCoverageSchema, MessageCelCoverage_WindowSchema, MessageOneofCoverageSchema, NumberCoverageSchema, OneofCoverageSchema, PingSchema, StringContentCoverageSchema, TreeNodeSchema, WellKnownCoverageSchema, file_shop_schema_v1_schema } from "./schema_pb";

register(file_shop_schema_v1_schema);

/**
 * SchemaColor exercises the enum rules and the enum JSON shape.
 *
 * shop.schema.v1.SchemaColor, as protojson writes it: the member's name.
 */
export const schemaColorZod = z.enum(["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]);

/**
 * Item is the rule-bearing message other fixtures reference. Its empty instance is valid, so a reference to it tests presence and nesting only.
 *
 * The composable schema of shop.schema.v1.Item: every field carries its own rules, so
 * `itemZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in itemZod.
 */
export const itemZodObject = z.strictObject({
  /**
   * string.max_len = 32
   *
   * Checked by protovalidate: string.max_len.
   */
  text: z.string().superRefine(field(ItemSchema, "text")).optional(),
});

/** Full validation of shop.schema.v1.Item: the message has no rule beyond its fields'. */
export const itemZod = itemZodObject;

/**
 * FormatCoverage has one field per string well-known format. Every field has explicit presence, so a test can set one at a time.
 *
 * The composable schema of shop.schema.v1.FormatCoverage: every field carries its own rules, so
 * `formatCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in formatCoverageZod.
 */
export const formatCoverageZodObject = z.strictObject({
  /**
   * string.hostname = true
   *
   * Checked by protovalidate: string.hostname.
   */
  hostname: z.string().superRefine(field(FormatCoverageSchema, "hostname")).optional(),
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.string().regex(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/).optional(),
  /**
   * string.ip = true
   *
   * Checked by protovalidate: string.ip.
   */
  ip: z.string().superRefine(field(FormatCoverageSchema, "ip")).optional(),
  /**
   * string.ipv4 = true
   *
   * Checked by protovalidate: string.ipv4.
   */
  ipv4: z.string().superRefine(field(FormatCoverageSchema, "ipv4")).optional(),
  /**
   * string.ipv6 = true
   *
   * Checked by protovalidate: string.ipv6.
   */
  ipv6: z.string().superRefine(field(FormatCoverageSchema, "ipv6")).optional(),
  /**
   * string.uri = true
   *
   * Checked by protovalidate: string.uri.
   */
  uri: z.string().superRefine(field(FormatCoverageSchema, "uri")).optional(),
  /**
   * string.uri_ref = true
   *
   * Checked by protovalidate: string.uri_ref.
   */
  uriRef: z.string().superRefine(field(FormatCoverageSchema, "uri_ref")).optional(),
  /**
   * string.address = true
   *
   * Checked by protovalidate: string.address.
   */
  address: z.string().superRefine(field(FormatCoverageSchema, "address")).optional(),
  /**
   * string.host_and_port = true
   *
   * Checked by protovalidate: string.host_and_port.
   */
  hostAndPort: z.string().superRefine(field(FormatCoverageSchema, "host_and_port")).optional(),
  /**
   * string.ip_with_prefixlen = true
   *
   * Checked by protovalidate: string.ip_with_prefixlen.
   */
  ipWithPrefixlen: z.string().superRefine(field(FormatCoverageSchema, "ip_with_prefixlen")).optional(),
  /**
   * string.ipv4_with_prefixlen = true
   *
   * Checked by protovalidate: string.ipv4_with_prefixlen.
   */
  ipv4WithPrefixlen: z.string().superRefine(field(FormatCoverageSchema, "ipv4_with_prefixlen")).optional(),
  /**
   * string.ipv6_with_prefixlen = true
   *
   * Checked by protovalidate: string.ipv6_with_prefixlen.
   */
  ipv6WithPrefixlen: z.string().superRefine(field(FormatCoverageSchema, "ipv6_with_prefixlen")).optional(),
  /**
   * string.ip_prefix = true
   *
   * Checked by protovalidate: string.ip_prefix.
   */
  ipPrefix: z.string().superRefine(field(FormatCoverageSchema, "ip_prefix")).optional(),
  /**
   * string.ipv4_prefix = true
   *
   * Checked by protovalidate: string.ipv4_prefix.
   */
  ipv4Prefix: z.string().superRefine(field(FormatCoverageSchema, "ipv4_prefix")).optional(),
  /**
   * string.ipv6_prefix = true
   *
   * Checked by protovalidate: string.ipv6_prefix.
   */
  ipv6Prefix: z.string().superRefine(field(FormatCoverageSchema, "ipv6_prefix")).optional(),
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  uuid: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * string.tuuid = true
   *
   * Carried by Zod: string.tuuid.
   */
  tuuid: z.string().regex(/^[0-9a-fA-F]{32}$/).optional(),
  /**
   * string.ulid = true
   *
   * Carried by Zod: string.ulid.
   */
  ulid: z.string().regex(/^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/).optional(),
  /**
   * string.protobuf_fqn = true
   *
   * Carried by Zod: string.protobuf_fqn.
   */
  protobufFqn: z.string().regex(/^[A-Za-z_][A-Za-z_0-9]*(\.[A-Za-z_][A-Za-z_0-9]*)*$/).optional(),
  /**
   * string.protobuf_dot_fqn = true
   *
   * Carried by Zod: string.protobuf_dot_fqn.
   */
  protobufDotFqn: z.string().regex(/^\.[A-Za-z_][A-Za-z_0-9]*(\.[A-Za-z_][A-Za-z_0-9]*)*$/).optional(),
  /**
   * string.strict = true
   * string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_NAME
   *
   * Checked by protovalidate: string.strict, string.well_known_regex.
   */
  headerName: z.string().superRefine(field(FormatCoverageSchema, "header_name")).optional(),
  /**
   * string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_VALUE
   *
   * Checked by protovalidate: string.well_known_regex.
   */
  headerValue: z.string().superRefine(field(FormatCoverageSchema, "header_value")).optional(),
  /**
   * string.hostname = true
   *
   * Checked by protovalidate: string.hostname.
   */
  hiddenHost: z.string().superRefine(field(FormatCoverageSchema, "hidden_host")).optional(),
});

/** Full validation of shop.schema.v1.FormatCoverage: the message has no rule beyond its fields'. */
export const formatCoverageZod = formatCoverageZodObject;

/**
 * StringContentCoverage has one field per string length and content rule.
 *
 * The composable schema of shop.schema.v1.StringContentCoverage: every field carries its own rules, so
 * `stringContentCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stringContentCoverageZod.
 */
export const stringContentCoverageZodObject = z.strictObject({
  /**
   * string.min_len = 2
   *
   * Checked by protovalidate: string.min_len.
   */
  minLen: z.string().superRefine(field(StringContentCoverageSchema, "min_len")).optional(),
  /**
   * string.max_len = 8
   *
   * Checked by protovalidate: string.max_len.
   */
  maxLen: z.string().superRefine(field(StringContentCoverageSchema, "max_len")).optional(),
  /**
   * string.len = 4
   *
   * Checked by protovalidate: string.len.
   */
  exactLen: z.string().superRefine(field(StringContentCoverageSchema, "exact_len")).optional(),
  /**
   * string.len_bytes = 4
   *
   * Checked by protovalidate: string.len_bytes.
   */
  lenBytes: z.string().superRefine(field(StringContentCoverageSchema, "len_bytes")).optional(),
  /**
   * string.min_bytes = 2
   *
   * Checked by protovalidate: string.min_bytes.
   */
  minBytes: z.string().superRefine(field(StringContentCoverageSchema, "min_bytes")).optional(),
  /**
   * string.max_bytes = 8
   *
   * Checked by protovalidate: string.max_bytes.
   */
  maxBytes: z.string().superRefine(field(StringContentCoverageSchema, "max_bytes")).optional(),
  /**
   * string.pattern = (?i)^abc$
   *
   * Checked by protovalidate: string.pattern.
   */
  patternInlineFlag: z.string().superRefine(field(StringContentCoverageSchema, "pattern_inline_flag")).optional(),
  /**
   * string.pattern = ^\S+$
   *
   * Checked by protovalidate: string.pattern.
   */
  patternNonSpace: z.string().superRefine(field(StringContentCoverageSchema, "pattern_non_space")).optional(),
  /**
   * string.prefix = +1
   *
   * Carried by Zod: string.prefix.
   */
  prefix: z.string().startsWith("+1").optional(),
  /**
   * string.suffix = .io
   *
   * Carried by Zod: string.suffix.
   */
  suffix: z.string().endsWith(".io").optional(),
  /**
   * string.contains = .
   *
   * Carried by Zod: string.contains.
   */
  contains: z.string().includes(".").optional(),
  /**
   * string.prefix = pre
   * string.suffix = suf
   *
   * Carried by Zod: string.prefix, string.suffix.
   */
  prefixAndSuffix: z.string().startsWith("pre").endsWith("suf").optional(),
  /**
   * string.not_contains =  
   *
   * Checked by protovalidate: string.not_contains.
   */
  notContains: z.string().superRefine(field(StringContentCoverageSchema, "not_contains")).optional(),
  /**
   * string.const = fixed
   *
   * Carried by Zod: string.const.
   */
  constValue: z.literal("fixed").optional(),
  /**
   * string.in = [a, b, c]
   *
   * Carried by Zod: string.in.
   */
  inSet: z.enum(["a, b", "c"]).optional(),
  /**
   * string.not_in = [x, y]
   *
   * Checked by protovalidate: string.not_in.
   */
  notInSet: z.string().superRefine(field(StringContentCoverageSchema, "not_in_set")).optional(),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  nickname: z.string(),
  /**
   * string.min_len = 2
   * cel[string_content.code.no_spaces]: !this.contains(' ')
   *   message: code must not contain spaces
   *   refs: this
   *   calls: !_, contains
   *
   * Checked by protovalidate: string.min_len, cel[string_content.code.no_spaces].
   */
  code: z.string().superRefine(field(StringContentCoverageSchema, "code")).optional(),
  /**
   * string.pattern = ^[a-f0-9-]+$
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   * Checked by protovalidate: string.pattern.
   */
  uuidPattern: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).superRefine(field(StringContentCoverageSchema, "uuid_pattern", ["string.uuid"])).optional(),
  /**
   * string.in = ["\*\/ , "\*\/x]
   * string.prefix = "\*\/
   * cel[string_content.escaped]: !this.endsWith('"*\/')
   *   message: must not end in "*\/"
   *   refs: this
   *   calls: !_, endsWith
   *
   * Carried by Zod: string.in.
   * Checked by protovalidate: string.prefix, cel[string_content.escaped].
   */
  escaped: z.enum(["\"\\*/\u2028", "\"\\*/x"]).superRefine(field(StringContentCoverageSchema, "escaped", ["string.in"])).optional(),
});

/** Full validation of shop.schema.v1.StringContentCoverage: the message has no rule beyond its fields'. */
export const stringContentCoverageZod = stringContentCoverageZodObject;

/**
 * ImplicitCoverage has implicit-presence fields whose zero value breaks a rule. protojson omits zero values, so the rule has to fire for an absent key.
 *
 * The composable schema of shop.schema.v1.ImplicitCoverage: every field carries its own rules, so
 * `implicitCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in implicitCoverageZod.
 */
export const implicitCoverageZodObject = z.strictObject({
  /**
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  shortCode: z.string().superRefine(field(ImplicitCoverageSchema, "short_code")).optional(),
  /**
   * int32.gt = 0
   *
   * Carried by Zod: int32.gt.
   */
  count: z.number().int().gt(0).optional(),
  /**
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.min_items.
   */
  tags: z.array(z.string()).min(1).optional(),
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.string().regex(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/).optional(),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredName: z.string().min(1),
  /**
   * required
   *
   * Checked by protovalidate: required.
   */
  requiredCount: z.number().int().superRefine(field(ImplicitCoverageSchema, "required_count")),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  accepted: z.literal(true),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  color: z.enum(["SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredTags: z.array(z.string()).min(1),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredItem: itemZod,
});

/**
 * Full validation of shop.schema.v1.ImplicitCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of short_code, count, tags, email when absent: protojson omits a zero value
 */
export const implicitCoverageZod = implicitCoverageZodObject.superRefine(message(ImplicitCoverageSchema));

/**
 * BytesCoverage has one field per bytes rule. JSON carries bytes as base64, standard or URL-safe.
 *
 * The composable schema of shop.schema.v1.BytesCoverage: every field carries its own rules, so
 * `bytesCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in bytesCoverageZod.
 */
export const bytesCoverageZodObject = z.strictObject({
  raw: z.string().optional(),
  /**
   * bytes.len = 4
   *
   * Checked by protovalidate: bytes.len.
   */
  exactLen: z.string().superRefine(field(BytesCoverageSchema, "exact_len")).optional(),
  /**
   * bytes.min_len = 2
   *
   * Checked by protovalidate: bytes.min_len.
   */
  minLen: z.string().superRefine(field(BytesCoverageSchema, "min_len")).optional(),
  /**
   * bytes.max_len = 8
   *
   * Checked by protovalidate: bytes.max_len.
   */
  maxLen: z.string().superRefine(field(BytesCoverageSchema, "max_len")).optional(),
  /**
   * bytes.pattern = ^[a-z]+$
   *
   * Checked by protovalidate: bytes.pattern.
   */
  pattern: z.string().superRefine(field(BytesCoverageSchema, "pattern")).optional(),
  /**
   * bytes.prefix = [1 2]
   *
   * Checked by protovalidate: bytes.prefix.
   */
  prefix: z.string().superRefine(field(BytesCoverageSchema, "prefix")).optional(),
  /**
   * bytes.ip = true
   *
   * Checked by protovalidate: bytes.ip.
   */
  ip: z.string().superRefine(field(BytesCoverageSchema, "ip")).optional(),
  /**
   * bytes.uuid = true
   *
   * Checked by protovalidate: bytes.uuid.
   */
  uuid: z.string().superRefine(field(BytesCoverageSchema, "uuid")).optional(),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredBlob: z.string(),
});

/** Full validation of shop.schema.v1.BytesCoverage: the message has no rule beyond its fields'. */
export const bytesCoverageZod = bytesCoverageZodObject;

/**
 * NumberCoverage has one field per numeric rule shape, over every JSON number form: int32-family numbers, int64-family strings, floats with NaN.
 *
 * The composable schema of shop.schema.v1.NumberCoverage: every field carries its own rules, so
 * `numberCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in numberCoverageZod.
 */
export const numberCoverageZodObject = z.strictObject({
  /**
   * int32.gt = 0
   * int32.lte = 100
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  bounded: z.number().int().gt(0).lte(100).optional(),
  /**
   * int32.gt = 10
   * int32.lt = 5
   *
   * Checked by protovalidate: int32.gt, int32.lt.
   */
  reversedRange: z.number().int().superRefine(field(NumberCoverageSchema, "reversed_range")).optional(),
  /**
   * int32.const = 7
   *
   * Carried by Zod: int32.const.
   */
  constValue: z.literal(7).optional(),
  /**
   * int32.in = [1, 2, 3]
   *
   * Carried by Zod: int32.in.
   */
  inSet: z.union([z.literal(1), z.literal(2), z.literal(3)]).optional(),
  /**
   * int32.not_in = [0, -1]
   *
   * Checked by protovalidate: int32.not_in.
   */
  notInSet: z.number().int().superRefine(field(NumberCoverageSchema, "not_in_set")).optional(),
  /**
   * uint32.gte = 1
   * uint32.lt = 65536
   *
   * Carried by Zod: uint32.gte, uint32.lt.
   */
  unsigned: z.number().int().gte(1).lt(65536).optional(),
  /**
   * sint32.gte = -128
   *
   * Carried by Zod: sint32.gte.
   */
  zigzag: z.number().int().gte(-128).optional(),
  /**
   * fixed32.lte = 1000
   *
   * Carried by Zod: fixed32.lte.
   */
  fixed: z.number().int().lte(1000).optional(),
  /**
   * sfixed32.lt = 0
   *
   * Carried by Zod: sfixed32.lt.
   */
  signedFixed: z.number().int().lt(0).optional(),
  /**
   * int64.gt = 0
   *
   * Checked by protovalidate: int64.gt.
   */
  big: z.string().regex(/^-?[0-9]+$/).superRefine(field(NumberCoverageSchema, "big")).optional(),
  /**
   * uint64.lte = 1000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  bigUnsigned: z.string().regex(/^[0-9]+$/).superRefine(field(NumberCoverageSchema, "big_unsigned")).optional(),
  /**
   * float.finite = true
   *
   * Checked by protovalidate: float.finite.
   */
  ratio: z.union([z.number(), z.enum(["NaN", "Infinity", "-Infinity"])]).superRefine(field(NumberCoverageSchema, "ratio")).optional(),
  /**
   * double.gt = 0
   *
   * Checked by protovalidate: double.gt.
   */
  score: z.union([z.number(), z.enum(["NaN", "Infinity", "-Infinity"])]).superRefine(field(NumberCoverageSchema, "score")).optional(),
  /**
   * double.in = [0.5, 1, 2]
   *
   * Checked by protovalidate: double.in.
   */
  factor: z.union([z.number(), z.enum(["NaN", "Infinity", "-Infinity"])]).superRefine(field(NumberCoverageSchema, "factor")).optional(),
  /**
   * float.lte = 0.1
   *
   * Checked by protovalidate: float.lte.
   */
  capped: z.union([z.number(), z.enum(["NaN", "Infinity", "-Infinity"])]).superRefine(field(NumberCoverageSchema, "capped")).optional(),
});

/** Full validation of shop.schema.v1.NumberCoverage: the message has no rule beyond its fields'. */
export const numberCoverageZod = numberCoverageZodObject;

/**
 * CollectionCoverage has one field per repeated and map shape.
 *
 * The composable schema of shop.schema.v1.CollectionCoverage: every field carries its own rules, so
 * `collectionCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in collectionCoverageZod.
 */
export const collectionCoverageZodObject = z.strictObject({
  /**
   * repeated.max_items = 3
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.max_items, repeated.min_items.
   */
  bounded: z.array(z.string()).max(3).min(1).optional(),
  /**
   * repeated.unique = true
   *
   * Checked by protovalidate: repeated.unique.
   */
  unique: z.array(z.string()).superRefine(field(CollectionCoverageSchema, "unique")).optional(),
  /**
   * repeated.items.string.uri = true
   *
   * Checked by protovalidate: repeated.items.string.uri.
   */
  links: z.array(z.string()).superRefine(field(CollectionCoverageSchema, "links")).optional(),
  /**
   * repeated.items.string.min_len = 1
   *
   * Checked by protovalidate: repeated.items.string.min_len.
   */
  names: z.array(z.string()).superRefine(field(CollectionCoverageSchema, "names")).optional(),
  /**
   * map.keys.string.min_len = 2
   * map.max_pairs = 4
   * map.min_pairs = 1
   * map.values.string.uri = true
   *
   * Checked by protovalidate: map.keys.string.min_len, map.max_pairs, map.min_pairs, map.values.string.uri.
   */
  labels: z.record(z.string(), z.string()).superRefine(field(CollectionCoverageSchema, "labels")).optional(),
  flags: z.record(z.string(), z.string()).optional(),
  byNumber: z.record(z.string(), z.string()).optional(),
  items: z.array(itemZod).optional(),
  itemsByKey: z.record(z.string(), itemZod).optional(),
});

/**
 * Full validation of shop.schema.v1.CollectionCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of bounded, unique, labels when absent: protojson omits a zero value
 */
export const collectionCoverageZod = collectionCoverageZodObject.superRefine(message(CollectionCoverageSchema));

/**
 * IgnoreCoverage has rules that are skipped for the zero value, and a field that is never validated.
 *
 * The composable schema of shop.schema.v1.IgnoreCoverage: every field carries its own rules, so
 * `ignoreCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in ignoreCoverageZod.
 */
export const ignoreCoverageZodObject = z.strictObject({
  /**
   * ignore = IGNORE_IF_ZERO_VALUE
   * string.email = true
   *
   * Checked by protovalidate: string.email.
   */
  email: z.string().superRefine(field(IgnoreCoverageSchema, "email")).optional(),
  /**
   * ignore = IGNORE_IF_ZERO_VALUE
   * int32.gt = 5
   *
   * Checked by protovalidate: int32.gt.
   */
  threshold: z.number().int().superRefine(field(IgnoreCoverageSchema, "threshold")).optional(),
  /**
   * repeated.items.ignore = IGNORE_IF_ZERO_VALUE
   * repeated.items.string.uuid = true
   *
   * Checked by protovalidate: repeated.items.string.uuid.
   */
  ids: z.array(z.string()).superRefine(field(IgnoreCoverageSchema, "ids")).optional(),
  /** ignore = IGNORE_ALWAYS */
  neverChecked: z.string().optional(),
  /**
   * map.values.ignore = IGNORE_IF_ZERO_VALUE
   * map.values.string.min_len = 3
   *
   * Checked by protovalidate: map.values.string.min_len.
   */
  codes: z.record(z.string(), z.string()).superRefine(field(IgnoreCoverageSchema, "codes")).optional(),
});

/** Full validation of shop.schema.v1.IgnoreCoverage: the message has no rule beyond its fields'. */
export const ignoreCoverageZod = ignoreCoverageZodObject;

/**
 * OneofCoverage has both oneof kinds: real oneofs, flattened into the JSON object, and a message-level oneof rule over plain fields.
 *
 * The composable schema of shop.schema.v1.OneofCoverage: every field carries its own rules, so
 * `oneofCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in oneofCoverageZod.
 */
export const oneofCoverageZodObject = z.strictObject({
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.string().regex(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/).optional(),
  phone: z.string().optional(),
  query: z.string().optional(),
  page: z.number().int().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
});

/**
 * Full validation of shop.schema.v1.OneofCoverage. Adds what protovalidate checks on the whole message:
 *   required oneof contact: exactly one of email, phone
 *   oneof filter: at most one of query, page
 *   required oneof: exactly one of first_name, last_name
 */
export const oneofCoverageZod = oneofCoverageZodObject.superRefine(message(OneofCoverageSchema));

/**
 * WellKnownCoverage has one field per well-known type the JSON shape maps.
 *
 * The composable schema of shop.schema.v1.WellKnownCoverage: every field carries its own rules, so
 * `wellKnownCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in wellKnownCoverageZod.
 */
export const wellKnownCoverageZodObject = z.strictObject({
  /**
   * duration.gte.seconds = 1
   * duration.lte.seconds = 300
   *
   * Checked by protovalidate: duration.gte.seconds, duration.lte.seconds.
   */
  timeout: durationZod.superRefine(field(WellKnownCoverageSchema, "timeout")).optional(),
  /**
   * timestamp.gt_now = true
   *
   * Checked by protovalidate: timestamp.gt_now.
   */
  expiresAt: timestampZod.superRefine(field(WellKnownCoverageSchema, "expires_at")).optional(),
  createdAt: timestampZod.optional(),
  /**
   * any.in = [type.googleapis.com/google.protobuf.Duration]
   *
   * Checked by protovalidate: any.in.
   */
  detail: anyZod.superRefine(field(WellKnownCoverageSchema, "detail")).optional(),
  metadata: structZod.optional(),
  value: valueZod.optional(),
  list: listValueZod.optional(),
  nothing: emptyZod.optional(),
  updateMask: fieldMaskZod.optional(),
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  label: stringValueZod.superRefine(field(WellKnownCoverageSchema, "label")).optional(),
  blob: bytesValueZod.optional(),
  bigCount: int64ValueZod.optional(),
  ratio: doubleValueZod.optional(),
  flag: boolValueZod.optional(),
  nullValue: nullValueZod.optional(),
  /**
   * enum.defined_only = true
   *
   * Checked by protovalidate: enum.defined_only.
   */
  checkedNull: nullValueZod.superRefine(field(WellKnownCoverageSchema, "checked_null")).optional(),
  smallRatio: floatValueZod.optional(),
  smallCount: int32ValueZod.optional(),
  unsignedCount: uInt32ValueZod.optional(),
  bigUnsigned: uInt64ValueZod.optional(),
});

/**
 * Full validation of shop.schema.v1.WellKnownCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of checked_null when absent: protojson omits a zero value
 */
export const wellKnownCoverageZod = wellKnownCoverageZodObject.superRefine(message(WellKnownCoverageSchema));

/**
 * EnumCoverage has one field per enum rule, and a field without rules.
 *
 * The composable schema of shop.schema.v1.EnumCoverage: every field carries its own rules, so
 * `enumCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in enumCoverageZod.
 */
export const enumCoverageZodObject = z.strictObject({
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  defined: z.enum(["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]).optional(),
  /**
   * enum.in = [1, 2]
   *
   * Carried by Zod: enum.in.
   */
  allowed: z.enum(["SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN"]).optional(),
  /**
   * enum.not_in = [3]
   *
   * Carried by Zod: enum.not_in.
   */
  excluded: z.enum(["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN"]).optional(),
  /**
   * enum.const = 2
   *
   * Carried by Zod: enum.const.
   */
  pinned: z.enum(["SCHEMA_COLOR_GREEN"]).optional(),
  plain: schemaColorZod.optional(),
});

/** Full validation of shop.schema.v1.EnumCoverage: the message has no rule beyond its fields'. */
export const enumCoverageZod = enumCoverageZodObject;

/**
 * JsonNameCoverage has fields whose JSON name differs from the proto name in ways a naive camelCase conversion gets wrong.
 *
 * The composable schema of shop.schema.v1.JsonNameCoverage: every field carries its own rules, so
 * `jsonNameCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in jsonNameCoverageZod.
 */
export const jsonNameCoverageZodObject = z.strictObject({
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  extId: z.string().superRefine(field(JsonNameCoverageSchema, "external_id")).optional(),
  /**
   * int32.gte = 0
   *
   * Carried by Zod: int32.gte.
   */
  metric1st: z.number().int().gte(0).optional(),
  /**
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  displayName: z.string().superRefine(field(JsonNameCoverageSchema, "display_name")).optional(),
});

/**
 * Full validation of shop.schema.v1.JsonNameCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of external_id, metric_1st, display_name when absent: protojson omits a zero value
 */
export const jsonNameCoverageZod = jsonNameCoverageZodObject.superRefine(message(JsonNameCoverageSchema));

const treeNodeBase = z.strictObject({
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  label: z.string().superRefine(field(TreeNodeSchema, "label")).optional(),
  /**
   * ignore = IGNORE_ALWAYS
   *
   * protovalidate never evaluates the shop.schema.v1.TreeNode inside, so the field takes any value that decodes as one.
   */
  skipped: z.unknown().superRefine(field(TreeNodeSchema, "skipped")).optional(),
});

type TreeNodeShape = z.input<typeof treeNodeBase> & { children?: TreeNodeShape[]; parent?: TreeNodeShape };

/**
 * TreeNode refers to itself, directly and through a list.
 *
 * The composable schema of shop.schema.v1.TreeNode: every field carries its own rules, so
 * `treeNodeZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in treeNodeZod.
 */
export const treeNodeZodObject = z.strictObject({
  ...treeNodeBase.shape,
  children: z.array(z.lazy((): z.ZodType<TreeNodeShape> => treeNodeZod)).optional(),
  parent: z.lazy((): z.ZodType<TreeNodeShape> => treeNodeZod).optional(),
});

/**
 * Full validation of shop.schema.v1.TreeNode. Adds what protovalidate checks on the whole message:
 *   the rules of label when absent: protojson omits a zero value
 */
export const treeNodeZod = treeNodeZodObject.superRefine(message(TreeNodeSchema));

const pingBase = z.strictObject({
  /**
   * string.max_len = 140
   *
   * Checked by protovalidate: string.max_len.
   */
  note: z.string().superRefine(field(PingSchema, "note")).optional(),
});

type PingShape = z.input<typeof pingBase> & { pong?: PongShape };

/**
 * Ping and Pong refer to each other: a cycle across two messages.
 *
 * The composable schema of shop.schema.v1.Ping: every field carries its own rules, so
 * `pingZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in pingZod.
 */
export const pingZodObject = z.strictObject({
  ...pingBase.shape,
  pong: z.lazy((): z.ZodType<PongShape> => pongZod).optional(),
});

/**
 * Full validation of shop.schema.v1.Ping. Adds what protovalidate checks on the whole message:
 *   the rules of note when absent: protojson omits a zero value
 */
export const pingZod = pingZodObject.superRefine(message(PingSchema));

const pongBase = z.strictObject({});

type PongShape = z.input<typeof pongBase> & { ping?: PingShape };

/**
 * Pong is the other half of the Ping cycle.
 *
 * The composable schema of shop.schema.v1.Pong: every field carries its own rules, so
 * `pongZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in pongZod.
 */
export const pongZodObject = z.strictObject({
  ...pongBase.shape,
  ping: z.lazy((): z.ZodType<PingShape> => pingZod).optional(),
});

/** Full validation of shop.schema.v1.Pong: the message has no rule beyond its fields'. */
export const pongZod = pongZodObject;

/**
 * Window is nested to check that nested messages get their own schema.
 *
 * The composable schema of shop.schema.v1.MessageCelCoverage.Window: every field carries its own rules, so
 * `messageCelCoverageWindowZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageCelCoverageWindowZod.
 */
export const messageCelCoverageWindowZodObject = z.strictObject({
  startMinute: z.number().int().optional(),
  endMinute: z.number().int().optional(),
});

/**
 * Full validation of shop.schema.v1.MessageCelCoverage.Window. Adds what protovalidate checks on the whole message:
 *   cel[message_cel.window.ordered]
 */
export const messageCelCoverageWindowZod = messageCelCoverageWindowZodObject.superRefine(message(MessageCelCoverage_WindowSchema));

/**
 * MessageCelCoverage has a message-level CEL rule spanning two fields, and a nested message with a rule of its own.
 *
 * The composable schema of shop.schema.v1.MessageCelCoverage: every field carries its own rules, so
 * `messageCelCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageCelCoverageZod.
 */
export const messageCelCoverageZodObject = z.strictObject({
  low: z.number().int().optional(),
  high: z.number().int().optional(),
  window: messageCelCoverageWindowZod.optional(),
});

/**
 * Full validation of shop.schema.v1.MessageCelCoverage. Adds what protovalidate checks on the whole message:
 *   cel[message_cel.low_below_high]
 */
export const messageCelCoverageZod = messageCelCoverageZodObject.superRefine(message(MessageCelCoverageSchema));

/**
 * MessageOneofCoverage has implicit fields named by a message-level oneof rule. protovalidate gives such a field IGNORE_IF_ZERO_VALUE, so its zero value passes its own rules.
 *
 * The composable schema of shop.schema.v1.MessageOneofCoverage: every field carries its own rules, so
 * `messageOneofCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageOneofCoverageZod.
 */
export const messageOneofCoverageZodObject = z.strictObject({
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  code: z.string().superRefine(field(MessageOneofCoverageSchema, "code")).optional(),
  label: z.string().optional(),
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * repeated.min_items = 2
   *
   * Checked by protovalidate: repeated.min_items.
   */
  tags: z.array(z.string()).superRefine(field(MessageOneofCoverageSchema, "tags")).optional(),
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * enum.defined_only = true
   *
   * Checked by protovalidate: enum.defined_only.
   */
  color: schemaColorZod.superRefine(field(MessageOneofCoverageSchema, "color")).optional(),
  /** ignore = IGNORE_ALWAYS */
  alias: z.string().optional(),
});

/**
 * Full validation of shop.schema.v1.MessageOneofCoverage. Adds what protovalidate checks on the whole message:
 *   oneof: at most one of code, label, tags, color, alias
 */
export const messageOneofCoverageZod = messageOneofCoverageZodObject.superRefine(message(MessageOneofCoverageSchema));

/**
 * EvaluationCoverage has a message rule that fails to evaluate while divisor is 0, the value divisor holds in the message field() checks total in.
 *
 * The composable schema of shop.schema.v1.EvaluationCoverage: every field carries its own rules, so
 * `evaluationCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in evaluationCoverageZod.
 */
export const evaluationCoverageZodObject = z.strictObject({
  divisor: z.number().int().optional(),
  /**
   * cel[this % 2 == 0]: this % 2 == 0
   *   refs: this
   *   calls: _%_, _==_
   *
   * Checked by protovalidate: cel[this % 2 == 0].
   */
  total: z.number().int().superRefine(field(EvaluationCoverageSchema, "total")).optional(),
});

/**
 * Full validation of shop.schema.v1.EvaluationCoverage. Adds what protovalidate checks on the whole message:
 *   cel[evaluation.ratio]
 *   the rules of total when absent: protojson omits a zero value
 */
export const evaluationCoverageZod = evaluationCoverageZodObject.superRefine(message(EvaluationCoverageSchema));
