// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: shop/schema/v1/schema.proto

import type { Email, Narrow, NonEmptyList, Require, Uuid } from "../../../strict/types";
import type { BytesCoverage, CollectionCoverage, EnumCoverage, EvaluationCoverage, FormatCoverage, IgnoreCoverage, ImplicitCoverage, Item, JsonNameCoverage, MessageCelCoverage, MessageCelCoverage_Window, MessageOneofCoverage, NumberCoverage, OneofCoverage, Ping, Pong, SchemaColor, StringContentCoverage, TreeNode, WellKnownCoverage } from "./schema_pb";
import { BytesCoverageSchema, CollectionCoverageSchema, EnumCoverageSchema, FormatCoverageSchema, ImplicitCoverageSchema, OneofCoverageSchema, StringContentCoverageSchema } from "./schema_pb";
import type { GenMessage } from "@bufbuild/protobuf/codegenv2";

/**
 * SchemaColor exercises the enum rules and the enum JSON shape.
 *
 * Without SCHEMA_COLOR_UNSPECIFIED, the member protobuf numbers 0, which this overlay
 * reads as "unset" rather than a value. No buf.validate rule says so; the
 * convention that names it <ENUM>_UNSPECIFIED does.
 */
export type SchemaColorStrict = Exclude<SchemaColor, 0>;

/**
 * Item is the rule-bearing message other fixtures reference. Its empty instance is valid, so a reference to it tests presence and nesting only.
 *
 * Left to runtime validation, having no type equivalent:
 *   text
 *     string.max_len = 32
 */
export type ItemStrict = Item;

/**
 * FormatCoverage has one field per string well-known format. Every field has explicit presence, so a test can set one at a time.
 *
 * Left to runtime validation, having no type equivalent:
 *   hostname
 *     string.hostname = true
 *   ip
 *     string.ip = true
 *   ipv4
 *     string.ipv4 = true
 *   ipv6
 *     string.ipv6 = true
 *   uri
 *     string.uri = true
 *   uri_ref
 *     string.uri_ref = true
 *   address
 *     string.address = true
 *   host_and_port
 *     string.host_and_port = true
 *   ip_with_prefixlen
 *     string.ip_with_prefixlen = true
 *   ipv4_with_prefixlen
 *     string.ipv4_with_prefixlen = true
 *   ipv6_with_prefixlen
 *     string.ipv6_with_prefixlen = true
 *   ip_prefix
 *     string.ip_prefix = true
 *   ipv4_prefix
 *     string.ipv4_prefix = true
 *   ipv6_prefix
 *     string.ipv6_prefix = true
 *   tuuid
 *     string.tuuid = true
 *   ulid
 *     string.ulid = true
 *   protobuf_fqn
 *     string.protobuf_fqn = true
 *   protobuf_dot_fqn
 *     string.protobuf_dot_fqn = true
 *   header_name
 *     string.strict = true
 *     string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_NAME
 *   header_value
 *     string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_VALUE
 *   hidden_host
 *     string.hostname = true
 */
export type FormatCoverageStrict = Narrow<FormatCoverage, {
  /**
   * string.email = true
   *
   * Carried into the type: string.email.
   */
  email: Email;
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  uuid: Uuid;
}>;

/**
 * StringContentCoverage has one field per string length and content rule.
 *
 * Left to runtime validation, having no type equivalent:
 *   min_len
 *     string.min_len = 2
 *   max_len
 *     string.max_len = 8
 *   exact_len
 *     string.len = 4
 *   len_bytes
 *     string.len_bytes = 4
 *   min_bytes
 *     string.min_bytes = 2
 *   max_bytes
 *     string.max_bytes = 8
 *   pattern_inline_flag
 *     string.pattern = (?i)^abc$
 *   pattern_non_space
 *     string.pattern = ^\S+$
 *   prefix
 *     string.prefix = +1
 *   suffix
 *     string.suffix = .io
 *   contains
 *     string.contains = .
 *   prefix_and_suffix
 *     string.prefix = pre
 *     string.suffix = suf
 *   not_contains
 *     string.not_contains =  
 *   const_value
 *     string.const = fixed
 *   in_set
 *     string.in = [a, b, c]
 *   not_in_set
 *     string.not_in = [x, y]
 *   code
 *     string.min_len = 2
 *     cel[string_content.code.no_spaces]: !this.contains(' ')
 *       message: code must not contain spaces
 *       refs: this
 *       calls: !_, contains
 *   escaped
 *     string.in = ["\*\/ , "\*\/x]
 *     string.prefix = "\*\/
 *     cel[string_content.escaped]: !this.endsWith('"*\/')
 *       message: must not end in "*\/"
 *       refs: this
 *       calls: !_, endsWith
 */
export type StringContentCoverageStrict = Require<Narrow<StringContentCoverage, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  nickname: NonNullable<StringContentCoverage["nickname"]>;
  /**
   * string.pattern = ^[a-f0-9-]+$
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  uuidPattern: Uuid;
}>, "nickname">;

/**
 * ImplicitCoverage has implicit-presence fields whose zero value breaks a rule. protojson omits zero values, so the rule has to fire for an absent key.
 *
 * Left to runtime validation, having no type equivalent:
 *   short_code
 *     string.min_len = 3
 *   count
 *     int32.gt = 0
 *   required_name
 *     required
 *   required_count
 *     required
 *   accepted
 *     required
 */
export type ImplicitCoverageStrict = Require<Narrow<ImplicitCoverage, {
  /**
   * repeated.min_items = 1
   *
   * Carried into the type: repeated.min_items.
   */
  tags: NonEmptyList<ImplicitCoverage["tags"]>;
  /**
   * string.email = true
   *
   * Carried into the type: string.email.
   */
  email: Email;
  /**
   * required
   *
   * Carried into the type: required.
   */
  color: SchemaColorStrict;
  /**
   * required
   *
   * Carried into the type: required.
   */
  requiredTags: NonEmptyList<ImplicitCoverage["requiredTags"]>;
  /**
   * required
   *
   * Carried into the type: required.
   */
  requiredItem: NonNullable<ImplicitCoverage["requiredItem"]>;
}>, "requiredItem">;

/**
 * BytesCoverage has one field per bytes rule. JSON carries bytes as base64, standard or URL-safe.
 *
 * Left to runtime validation, having no type equivalent:
 *   exact_len
 *     bytes.len = 4
 *   min_len
 *     bytes.min_len = 2
 *   max_len
 *     bytes.max_len = 8
 *   pattern
 *     bytes.pattern = ^[a-z]+$
 *   prefix
 *     bytes.prefix = [1 2]
 *   ip
 *     bytes.ip = true
 *   uuid
 *     bytes.uuid = true
 */
export type BytesCoverageStrict = Require<Narrow<BytesCoverage, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  requiredBlob: NonNullable<BytesCoverage["requiredBlob"]>;
}>, "requiredBlob">;

/**
 * NumberCoverage has one field per numeric rule shape, over every JSON number form: int32-family numbers, int64-family strings, floats with NaN.
 *
 * Left to runtime validation, having no type equivalent:
 *   bounded
 *     int32.gt = 0
 *     int32.lte = 100
 *   reversed_range
 *     int32.gt = 10
 *     int32.lt = 5
 *   const_value
 *     int32.const = 7
 *   in_set
 *     int32.in = [1, 2, 3]
 *   not_in_set
 *     int32.not_in = [0, -1]
 *   unsigned
 *     uint32.gte = 1
 *     uint32.lt = 65536
 *   zigzag
 *     sint32.gte = -128
 *   fixed
 *     fixed32.lte = 1000
 *   signed_fixed
 *     sfixed32.lt = 0
 *   big
 *     int64.gt = 0
 *   big_unsigned
 *     uint64.lte = 1000000
 *   ratio
 *     float.finite = true
 *   score
 *     double.gt = 0
 *   factor
 *     double.in = [0.5, 1, 2]
 *   capped
 *     float.lte = 0.1
 */
export type NumberCoverageStrict = NumberCoverage;

/**
 * CollectionCoverage has one field per repeated and map shape.
 *
 * Left to runtime validation, having no type equivalent:
 *   unique
 *     repeated.unique = true
 *   links
 *     repeated.items.string.uri = true
 *   names
 *     repeated.items.string.min_len = 1
 *   labels
 *     map.keys.string.min_len = 2
 *     map.max_pairs = 4
 *     map.min_pairs = 1
 *     map.values.string.uri = true
 */
export type CollectionCoverageStrict = Narrow<CollectionCoverage, {
  /**
   * repeated.max_items = 3
   * repeated.min_items = 1
   *
   * Carried into the type: repeated.min_items.
   */
  bounded: NonEmptyList<CollectionCoverage["bounded"]>;
}>;

/**
 * IgnoreCoverage has rules that are skipped for the zero value, and a field that is never validated.
 *
 * Left to runtime validation, having no type equivalent:
 *   email
 *     ignore = IGNORE_IF_ZERO_VALUE
 *     string.email = true
 *   threshold
 *     ignore = IGNORE_IF_ZERO_VALUE
 *     int32.gt = 5
 *   ids
 *     repeated.items.ignore = IGNORE_IF_ZERO_VALUE
 *     repeated.items.string.uuid = true
 *   never_checked
 *     ignore = IGNORE_ALWAYS
 *   codes
 *     map.values.ignore = IGNORE_IF_ZERO_VALUE
 *     map.values.string.min_len = 3
 */
export type IgnoreCoverageStrict = IgnoreCoverage;

/**
 * OneofCoverage has both oneof kinds: real oneofs, flattened into the JSON object, and a message-level oneof rule over plain fields.
 *
 * Left to runtime validation, having no type equivalent:
 *   oneof
 *     required oneof: exactly one of first_name, last_name
 */
export type OneofCoverageStrict = Narrow<OneofCoverage, {
  /**
   * required oneof contact: exactly one of email, phone
   * email: string.email = true
   */
  contact: Exclude<OneofCoverage["contact"], { case: undefined }>;
}>;

/**
 * WellKnownCoverage has one field per well-known type the JSON shape maps.
 *
 * Left to runtime validation, having no type equivalent:
 *   timeout
 *     duration.gte.seconds = 1
 *     duration.lte.seconds = 300
 *   expires_at
 *     timestamp.gt_now = true
 *   detail
 *     any.in = [type.googleapis.com/google.protobuf.Duration]
 *   label
 *     string.min_len = 1
 *   checked_null
 *     enum.defined_only = true
 */
export type WellKnownCoverageStrict = WellKnownCoverage;

/** EnumCoverage has one field per enum rule, and a field without rules. */
export type EnumCoverageStrict = Narrow<EnumCoverage, {
  /** enum.defined_only = true */
  defined: SchemaColorStrict;
  /**
   * enum.in = [1, 2]
   *
   * Carried into the type: enum.in.
   */
  allowed: Extract<SchemaColorStrict, 1 | 2>;
  /**
   * enum.not_in = [3]
   *
   * Carried into the type: enum.not_in.
   */
  excluded: Exclude<SchemaColorStrict, 3>;
  /**
   * enum.const = 2
   *
   * Carried into the type: enum.const.
   */
  pinned: Extract<SchemaColorStrict, 2>;
  plain: SchemaColorStrict;
}>;

/**
 * JsonNameCoverage has fields whose JSON name differs from the proto name in ways a naive camelCase conversion gets wrong.
 *
 * Left to runtime validation, having no type equivalent:
 *   external_id
 *     string.min_len = 1
 *   metric_1st
 *     int32.gte = 0
 *   display_name
 *     string.max_len = 64
 */
export type JsonNameCoverageStrict = JsonNameCoverage;

/**
 * TreeNode refers to itself, directly and through a list.
 *
 * Left to runtime validation, having no type equivalent:
 *   label
 *     string.min_len = 1
 *   skipped
 *     ignore = IGNORE_ALWAYS
 */
export type TreeNodeStrict = TreeNode;

/**
 * Ping and Pong refer to each other: a cycle across two messages.
 *
 * Left to runtime validation, having no type equivalent:
 *   note
 *     string.max_len = 140
 */
export type PingStrict = Ping;

/** Pong is the other half of the Ping cycle. */
export type PongStrict = Pong;

/**
 * MessageCelCoverage has a message-level CEL rule spanning two fields, and a nested message with a rule of its own.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[message_cel.low_below_high]
 *     this.low < this.high
 *     message: low must be below high
 */
export type MessageCelCoverageStrict = MessageCelCoverage;

/**
 * Window is nested to check that nested messages get their own schema.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[message_cel.window.ordered]
 *     this.end_minute > this.start_minute
 *     message: end_minute must be after start_minute
 */
export type MessageCelCoverage_WindowStrict = MessageCelCoverage_Window;

/**
 * MessageOneofCoverage has implicit fields named by a message-level oneof rule. protovalidate gives such a field IGNORE_IF_ZERO_VALUE, so its zero value passes its own rules.
 *
 * Left to runtime validation, having no type equivalent:
 *   code
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     string.min_len = 3
 *   tags
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     repeated.min_items = 2
 *   color
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     enum.defined_only = true
 *   alias
 *     ignore = IGNORE_ALWAYS
 *   oneof
 *     oneof: at most one of code, label, tags, color, alias
 */
export type MessageOneofCoverageStrict = MessageOneofCoverage;

/**
 * EvaluationCoverage has a message rule that fails to evaluate while divisor is 0, the value divisor holds in the message field() checks total in.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[evaluation.ratio]
 *     this.total / this.divisor <= 100
 *     message: total / divisor must be at most 100
 *   total
 *     cel[this % 2 == 0]: this % 2 == 0
 *       refs: this
 *       calls: _%_, _==_
 */
export type EvaluationCoverageStrict = EvaluationCoverage;

/**
 * Describes shop.schema.v1.FormatCoverage, reporting FormatCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const FormatCoverageStrictSchema =
  FormatCoverageSchema as GenMessage<FormatCoverage, { validType: FormatCoverageStrict }>;

/**
 * Describes shop.schema.v1.StringContentCoverage, reporting StringContentCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const StringContentCoverageStrictSchema =
  StringContentCoverageSchema as GenMessage<StringContentCoverage, { validType: StringContentCoverageStrict }>;

/**
 * Describes shop.schema.v1.ImplicitCoverage, reporting ImplicitCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const ImplicitCoverageStrictSchema =
  ImplicitCoverageSchema as GenMessage<ImplicitCoverage, { validType: ImplicitCoverageStrict }>;

/**
 * Describes shop.schema.v1.BytesCoverage, reporting BytesCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const BytesCoverageStrictSchema =
  BytesCoverageSchema as GenMessage<BytesCoverage, { validType: BytesCoverageStrict }>;

/**
 * Describes shop.schema.v1.CollectionCoverage, reporting CollectionCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const CollectionCoverageStrictSchema =
  CollectionCoverageSchema as GenMessage<CollectionCoverage, { validType: CollectionCoverageStrict }>;

/**
 * Describes shop.schema.v1.OneofCoverage, reporting OneofCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const OneofCoverageStrictSchema =
  OneofCoverageSchema as GenMessage<OneofCoverage, { validType: OneofCoverageStrict }>;

/**
 * Describes shop.schema.v1.EnumCoverage, reporting EnumCoverageStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const EnumCoverageStrictSchema =
  EnumCoverageSchema as GenMessage<EnumCoverage, { validType: EnumCoverageStrict }>;

