# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/schema/v1/schema.proto
"""buf.validate rules for shop/schema/v1/schema.proto.

One typing.Annotated alias per constrained field, over the type
protoc-gen-python already declared. The message classes stay in
shop.schema.v1.schema_pb2; import them from there.

A rule with an annotated_types equivalent is carried as that constructor,
which pydantic, msgspec and beartype enforce. The rest are metadata strings,
left to protovalidate at runtime.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated

from annotated_types import Ge, Gt, Le, Lt, MaxLen, MinLen

from google.protobuf import any_pb2 as _google_protobuf_any_pb2
from google.protobuf import duration_pb2 as _google_protobuf_duration_pb2
from google.protobuf import struct_pb2 as _google_protobuf_struct_pb2
from google.protobuf import timestamp_pb2 as _google_protobuf_timestamp_pb2
from google.protobuf import wrappers_pb2 as _google_protobuf_wrappers_pb2
from shop.schema.v1.schema_pb2 import Item, SchemaColor, TreeNode

# SchemaColor exercises the enum rules and the enum JSON shape.
# Without SCHEMA_COLOR_UNSPECIFIED, the member protobuf numbers 0, which this overlay
# reads as "unset" rather than a value. No buf.validate rule says so; the
# convention that names it <ENUM>_UNSPECIFIED does.
SchemaColorStrict = Annotated[
    SchemaColor,
    Ge(1),
]

# Item is the rule-bearing message other fixtures reference. Its empty instance is valid, so a reference to it tests presence and nesting only.
ItemText = Annotated[
    str,
    MaxLen(32),
]

# FormatCoverage has one field per string well-known format. Every field has explicit presence, so a test can set one at a time.
FormatCoverageHostname = Annotated[
    str,
    "string.hostname = true",
]
FormatCoverageEmail = Annotated[
    str,
    "string.email = true",
]
FormatCoverageIp = Annotated[
    str,
    "string.ip = true",
]
FormatCoverageIpv4 = Annotated[
    str,
    "string.ipv4 = true",
]
FormatCoverageIpv6 = Annotated[
    str,
    "string.ipv6 = true",
]
FormatCoverageUri = Annotated[
    str,
    "string.uri = true",
]
FormatCoverageUriRef = Annotated[
    str,
    "string.uri_ref = true",
]
FormatCoverageAddress = Annotated[
    str,
    "string.address = true",
]
FormatCoverageHostAndPort = Annotated[
    str,
    "string.host_and_port = true",
]
FormatCoverageIpWithPrefixlen = Annotated[
    str,
    "string.ip_with_prefixlen = true",
]
FormatCoverageIpv4WithPrefixlen = Annotated[
    str,
    "string.ipv4_with_prefixlen = true",
]
FormatCoverageIpv6WithPrefixlen = Annotated[
    str,
    "string.ipv6_with_prefixlen = true",
]
FormatCoverageIpPrefix = Annotated[
    str,
    "string.ip_prefix = true",
]
FormatCoverageIpv4Prefix = Annotated[
    str,
    "string.ipv4_prefix = true",
]
FormatCoverageIpv6Prefix = Annotated[
    str,
    "string.ipv6_prefix = true",
]
FormatCoverageUuid = Annotated[
    str,
    "string.uuid = true",
]
FormatCoverageTuuid = Annotated[
    str,
    "string.tuuid = true",
]
FormatCoverageUlid = Annotated[
    str,
    "string.ulid = true",
]
FormatCoverageProtobufFqn = Annotated[
    str,
    "string.protobuf_fqn = true",
]
FormatCoverageProtobufDotFqn = Annotated[
    str,
    "string.protobuf_dot_fqn = true",
]
FormatCoverageHeaderName = Annotated[
    str,
    "string.strict = true",
    "string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_NAME",
]
FormatCoverageHeaderValue = Annotated[
    str,
    "string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_VALUE",
]
FormatCoverageHiddenHost = Annotated[
    str,
    "string.hostname = true",
]

# StringContentCoverage has one field per string length and content rule.
StringContentCoverageMinLen = Annotated[
    str,
    MinLen(2),
]
StringContentCoverageMaxLen = Annotated[
    str,
    MaxLen(8),
]
StringContentCoverageExactLen = Annotated[
    str,
    MinLen(4),
    MaxLen(4),
]
StringContentCoverageLenBytes = Annotated[
    str,
    "string.len_bytes = 4",
]
StringContentCoverageMinBytes = Annotated[
    str,
    "string.min_bytes = 2",
]
StringContentCoverageMaxBytes = Annotated[
    str,
    "string.max_bytes = 8",
]
StringContentCoveragePatternInlineFlag = Annotated[
    str,
    "string.pattern = (?i)^abc$",
]
StringContentCoveragePatternNonSpace = Annotated[
    str,
    "string.pattern = ^\\S+$",
]
StringContentCoveragePrefix = Annotated[
    str,
    "string.prefix = +1",
]
StringContentCoverageSuffix = Annotated[
    str,
    "string.suffix = .io",
]
StringContentCoverageContains = Annotated[
    str,
    "string.contains = .",
]
StringContentCoveragePrefixAndSuffix = Annotated[
    str,
    "string.prefix = pre",
    "string.suffix = suf",
]
StringContentCoverageNotContains = Annotated[
    str,
    "string.not_contains =  ",
]
StringContentCoverageConstValue = Annotated[
    str,
    "string.const = fixed",
]
StringContentCoverageInSet = Annotated[
    str,
    "string.in = [a, b, c]",
]
StringContentCoverageNotInSet = Annotated[
    str,
    "string.not_in = [x, y]",
]
StringContentCoverageNickname = Annotated[
    str,
    "required",
]
StringContentCoverageCode = Annotated[
    str,
    MinLen(2),
    "cel[string_content.code.no_spaces]: !this.contains(' ')",
    "  message: code must not contain spaces",
    "  refs: this",
    "  calls: !_, contains",
]
StringContentCoverageUuidPattern = Annotated[
    str,
    "string.pattern = ^[a-f0-9-]+$",
    "string.uuid = true",
]
StringContentCoverageEscaped = Annotated[
    str,
    "string.in = [\"\\*/\u2028, \"\\*/x]",
    "string.prefix = \"\\*/",
    "cel[string_content.escaped]: !this.endsWith('\"*/')",
    "  message: must not end in \"*/\"",
    "  refs: this",
    "  calls: !_, endsWith",
]

# ImplicitCoverage has implicit-presence fields whose zero value breaks a rule. protojson omits zero values, so the rule has to fire for an absent key.
ImplicitCoverageShortCode = Annotated[
    str,
    MinLen(3),
]
ImplicitCoverageCount = Annotated[
    int,
    Gt(0),
]
ImplicitCoverageTags = Annotated[
    Sequence[str],
    MinLen(1),
]
ImplicitCoverageEmail = Annotated[
    str,
    "string.email = true",
]
ImplicitCoverageRequiredName = Annotated[
    str,
    "required",
]
ImplicitCoverageRequiredCount = Annotated[
    int,
    "required",
]
ImplicitCoverageAccepted = Annotated[
    bool,
    "required",
]
ImplicitCoverageColor = Annotated[
    SchemaColorStrict,
    "required",
]
ImplicitCoverageRequiredTags = Annotated[
    Sequence[str],
    "required",
]
ImplicitCoverageRequiredItem = Annotated[
    Item,
    "required",
]

# BytesCoverage has one field per bytes rule. JSON carries bytes as base64, standard or URL-safe.
BytesCoverageExactLen = Annotated[
    bytes,
    MinLen(4),
    MaxLen(4),
]
BytesCoverageMinLen = Annotated[
    bytes,
    MinLen(2),
]
BytesCoverageMaxLen = Annotated[
    bytes,
    MaxLen(8),
]
BytesCoveragePattern = Annotated[
    bytes,
    "bytes.pattern = ^[a-z]+$",
]
BytesCoveragePrefix = Annotated[
    bytes,
    "bytes.prefix = [1 2]",
]
BytesCoverageIp = Annotated[
    bytes,
    "bytes.ip = true",
]
BytesCoverageUuid = Annotated[
    bytes,
    "bytes.uuid = true",
]
BytesCoverageRequiredBlob = Annotated[
    bytes,
    "required",
]

# NumberCoverage has one field per numeric rule shape, over every JSON number form: int32-family numbers, int64-family strings, floats with NaN.
NumberCoverageBounded = Annotated[
    int,
    Gt(0),
    Le(100),
]
NumberCoverageReversedRange = Annotated[
    int,
    "int32.gt = 10",
    "int32.lt = 5",
]
NumberCoverageConstValue = Annotated[
    int,
    "int32.const = 7",
]
NumberCoverageInSet = Annotated[
    int,
    "int32.in = [1, 2, 3]",
]
NumberCoverageNotInSet = Annotated[
    int,
    "int32.not_in = [0, -1]",
]
NumberCoverageUnsigned = Annotated[
    int,
    Ge(1),
    Lt(65536),
]
NumberCoverageZigzag = Annotated[
    int,
    Ge(-128),
]
NumberCoverageFixed = Annotated[
    int,
    Le(1000),
]
NumberCoverageSignedFixed = Annotated[
    int,
    Lt(0),
]
NumberCoverageBig = Annotated[
    int,
    Gt(0),
]
NumberCoverageBigUnsigned = Annotated[
    int,
    Le(1000000),
]
NumberCoverageRatio = Annotated[
    float,
    "float.finite = true",
]
NumberCoverageScore = Annotated[
    float,
    Gt(0),
]
NumberCoverageFactor = Annotated[
    float,
    "double.in = [0.5, 1, 2]",
]
NumberCoverageCapped = Annotated[
    float,
    "float.lte = 0.1",
]

# CollectionCoverage has one field per repeated and map shape.
CollectionCoverageBounded = Annotated[
    Sequence[str],
    MaxLen(3),
    MinLen(1),
]
CollectionCoverageUnique = Annotated[
    Sequence[str],
    "repeated.unique = true",
]
CollectionCoverageLinks = Annotated[
    Sequence[str],
    "repeated.items.string.uri = true",
]
CollectionCoverageNames = Annotated[
    Sequence[str],
    "repeated.items.string.min_len = 1",
]
CollectionCoverageLabels = Annotated[
    Mapping[str, str],
    "map.keys.string.min_len = 2",
    MaxLen(4),
    MinLen(1),
    "map.values.string.uri = true",
]

# IgnoreCoverage has rules that are skipped for the zero value, and a field that is never validated.
IgnoreCoverageEmail = Annotated[
    str,
    "ignore = IGNORE_IF_ZERO_VALUE",
    "string.email = true",
]
IgnoreCoverageThreshold = Annotated[
    int,
    "ignore = IGNORE_IF_ZERO_VALUE",
    "int32.gt = 5",
]
IgnoreCoverageIds = Annotated[
    Sequence[str],
    "repeated.items.ignore = IGNORE_IF_ZERO_VALUE",
    "repeated.items.string.uuid = true",
]
IgnoreCoverageNeverChecked = Annotated[
    str,
    "ignore = IGNORE_ALWAYS",
]
IgnoreCoverageCodes = Annotated[
    Mapping[str, str],
    "map.values.ignore = IGNORE_IF_ZERO_VALUE",
    "map.values.string.min_len = 3",
]

# OneofCoverage has both oneof kinds: real oneofs, flattened into the JSON object, and a message-level oneof rule over plain fields.
# required oneof contact: exactly one of email, phone
# oneof filter: at most one of query, page
# required oneof: exactly one of first_name, last_name
OneofCoverageEmail = Annotated[
    str,
    "string.email = true",
]

# WellKnownCoverage has one field per well-known type the JSON shape maps.
WellKnownCoverageTimeout = Annotated[
    _google_protobuf_duration_pb2.Duration,
    "duration.gte.seconds = 1",
    "duration.lte.seconds = 300",
]
WellKnownCoverageExpiresAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "timestamp.gt_now = true",
]
WellKnownCoverageDetail = Annotated[
    _google_protobuf_any_pb2.Any,
    "any.in = [type.googleapis.com/google.protobuf.Duration]",
]
WellKnownCoverageLabel = Annotated[
    _google_protobuf_wrappers_pb2.StringValue,
    MinLen(1),
]
WellKnownCoverageCheckedNull = Annotated[
    _google_protobuf_struct_pb2.NullValue,
    "enum.defined_only = true",
]

# EnumCoverage has one field per enum rule, and a field without rules.
EnumCoverageDefined = Annotated[
    SchemaColorStrict,
    "enum.defined_only = true",
]
EnumCoverageAllowed = Annotated[
    SchemaColorStrict,
    "enum.in = [1, 2]",
]
EnumCoverageExcluded = Annotated[
    SchemaColorStrict,
    "enum.not_in = [3]",
]
EnumCoveragePinned = Annotated[
    SchemaColorStrict,
    "enum.const = 2",
]

# JsonNameCoverage has fields whose JSON name differs from the proto name in ways a naive camelCase conversion gets wrong.
JsonNameCoverageExternalId = Annotated[
    str,
    MinLen(1),
]
JsonNameCoverageMetric1st = Annotated[
    int,
    Ge(0),
]
JsonNameCoverageDisplayName = Annotated[
    str,
    MaxLen(64),
]

# TreeNode refers to itself, directly and through a list.
TreeNodeLabel = Annotated[
    str,
    MinLen(1),
]
TreeNodeSkipped = Annotated[
    TreeNode,
    "ignore = IGNORE_ALWAYS",
]

# Ping and Pong refer to each other: a cycle across two messages.
PingNote = Annotated[
    str,
    MaxLen(140),
]

# Pong is the other half of the Ping cycle.

# MessageCelCoverage has a message-level CEL rule spanning two fields, and a nested message with a rule of its own.
# cel[message_cel.low_below_high]: this.low < this.high
#   message: low must be below high
#   refs: high, low, this
#   calls: _<_

# Window is nested to check that nested messages get their own schema.
# cel[message_cel.window.ordered]: this.end_minute > this.start_minute
#   message: end_minute must be after start_minute
#   refs: end_minute, start_minute, this
#   calls: _>_

# MessageOneofCoverage has implicit fields named by a message-level oneof rule. protovalidate gives such a field IGNORE_IF_ZERO_VALUE, so its zero value passes its own rules.
# oneof: at most one of code, label, tags, color, alias
MessageOneofCoverageCode = Annotated[
    str,
    "ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)",
    "string.min_len = 3",
]
MessageOneofCoverageTags = Annotated[
    Sequence[str],
    "ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)",
    "repeated.min_items = 2",
]
MessageOneofCoverageColor = Annotated[
    SchemaColor,
    "ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)",
    "enum.defined_only = true",
]
MessageOneofCoverageAlias = Annotated[
    str,
    "ignore = IGNORE_ALWAYS",
]

# EvaluationCoverage has a message rule that fails to evaluate while divisor is 0, the value divisor holds in the message field() checks total in.
# cel[evaluation.ratio]: this.total / this.divisor <= 100
#   message: total / divisor must be at most 100
#   refs: divisor, this, total
#   calls: _/_, _<=_
EvaluationCoverageTotal = Annotated[
    int,
    "cel[this % 2 == 0]: this % 2 == 0",
    "  refs: this",
    "  calls: _%_, _==_",
]

