// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/common/v1/common.proto

import { z } from "zod/v3";
import { timestampZod } from "../../../strict/wkt.zod3.js";

/**
 * Currency is the ISO-4217 subset this demo API accepts.
 *
 * shop.common.v1.Currency, as protojson writes it: the member's name.
 */
export declare const currencyZod: z.ZodEnum<["CURRENCY_UNSPECIFIED", "CURRENCY_EUR", "CURRENCY_USD", "CURRENCY_GBP"]>;

/**
 * SortDirection orders a list response.
 *
 * shop.common.v1.SortDirection, as protojson writes it: the member's name.
 */
export declare const sortDirectionZod: z.ZodEnum<["SORT_DIRECTION_UNSPECIFIED", "SORT_DIRECTION_ASC", "SORT_DIRECTION_DESC"]>;

/**
 * Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
 *
 * The composable schema of shop.common.v1.Money: every field carries its own rules, so
 * `moneyZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in moneyZod.
 */
export declare const moneyZodObject: z.ZodObject<{
  /**
   * int64.gte = -1000000000
   * int64.lte = 1000000000
   *
   * Checked by protovalidate: int64.gte, int64.lte.
   */
  units: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * int32.gte = -999999999
   * int32.lte = 999999999
   *
   * Carried by Zod: int32.gte, int32.lte.
   */
  nanos: z.ZodOptional<z.ZodNumber>;
  /**
   * required
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried by Zod: required, enum.defined_only, enum.not_in.
   */
  currency: z.ZodEnum<["CURRENCY_EUR", "CURRENCY_USD", "CURRENCY_GBP"]>;
}, "strict">;

/**
 * Full validation of shop.common.v1.Money. Adds what protovalidate checks on the whole message:
 *   cel[money.consistent_sign]
 *   the rules of units, nanos when absent: protojson omits a zero value
 */
export declare const moneyZod: z.ZodEffects<typeof moneyZodObject>;

/**
 * Pagination is the page selector shared by every list request.
 *
 * The composable schema of shop.common.v1.Pagination: every field carries its own rules, so
 * `paginationZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in paginationZod.
 */
export declare const paginationZodObject: z.ZodObject<{
  /**
   * int32.gte = 1
   *
   * Carried by Zod: int32.gte.
   */
  page: z.ZodOptional<z.ZodNumber>;
  /**
   * int32.gt = 0
   * int32.lte = 100
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  pageSize: z.ZodOptional<z.ZodNumber>;
  /**
   * string.max_len = 512
   * string.min_len = 8
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  pageToken: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.common.v1.Pagination. Adds what protovalidate checks on the whole message:
 *   the rules of page, page_size when absent: protojson omits a zero value
 */
export declare const paginationZod: z.ZodEffects<typeof paginationZodObject>;

/**
 * TimeRange is a half-open interval [start, end).
 *
 * The composable schema of shop.common.v1.TimeRange: every field carries its own rules, so
 * `timeRangeZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in timeRangeZod.
 */
export declare const timeRangeZodObject: z.ZodObject<{
  /**
   * required
   *
   * Carried by Zod: required.
   */
  start: typeof timestampZod;
  end: z.ZodOptional<typeof timestampZod>;
}, "strict">;

/**
 * Full validation of shop.common.v1.TimeRange. Adds what protovalidate checks on the whole message:
 *   cel[time_range.ordered]
 */
export declare const timeRangeZod: z.ZodEffects<typeof timeRangeZodObject>;

/**
 * LabelSet is a bounded set of user-supplied key/value labels.
 *
 * The composable schema of shop.common.v1.LabelSet: every field carries its own rules, so
 * `labelSetZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in labelSetZod.
 */
export declare const labelSetZodObject: z.ZodObject<{
  /**
   * map.keys.string.max_len = 63
   * map.keys.string.min_len = 1
   * map.keys.string.pattern = ^[a-z][a-z0-9_-]*$
   * map.max_pairs = 32
   * map.min_pairs = 1
   * map.values.string.max_len = 255
   *
   * Checked by protovalidate: map.keys.string.max_len, map.keys.string.min_len, map.keys.string.pattern, map.max_pairs, map.min_pairs, map.values.string.max_len.
   */
  labels: z.ZodOptional<z.ZodEffects<z.ZodRecord<z.ZodString, z.ZodString>>>;
}, "strict">;

/**
 * Full validation of shop.common.v1.LabelSet. Adds what protovalidate checks on the whole message:
 *   the rules of labels when absent: protojson omits a zero value
 */
export declare const labelSetZod: z.ZodEffects<typeof labelSetZodObject>;
