// Code generated by protoc-gen-strict. DO NOT EDIT.

// Nominal types for the scalar rules a structural type cannot express, and the
// mapped types the generated strict types are built from.
//
// A brand costs nothing at runtime. The point is not the check in the
// constructor — that is a shape check, and protovalidate stays the authority on
// validity — but that the constructor is the only way to produce the type, so an
// arbitrary string can no longer reach a field the proto declares as a UUID.
//
// One `unique symbol` per brand rather than one shared symbol carrying the
// brand's name: a field can carry two rules at once, and a `string.uuid` with
// `string.min_len = 1` narrows to `Uuid & NonEmpty`. Under a shared key that
// intersection would resolve to `"Uuid" & "NonEmpty"`, which is `never`.

declare const uuidBrand: unique symbol;
declare const emailBrand: unique symbol;
declare const nonEmptyBrand: unique symbol;

/** A string declared with `(buf.validate.field).string.uuid`. */
export type Uuid = string & { readonly [uuidBrand]: true };

/** A string declared with `(buf.validate.field).string.email`. */
export type Email = string & { readonly [emailBrand]: true };

/**
 * A string declared with `(buf.validate.field).string.min_len` of at least 1, or
 * constrained by a message CEL rule of the form `this.<field> != ''`.
 */
export type NonEmpty = string & { readonly [nonEmptyBrand]: true };

const UUID_PATTERN =
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;
const EMAIL_PATTERN = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;

// Each constructor rejects a non-string before it looks at the value. The
// signatures say `string`, but nothing stops a JavaScript caller.
//
// They are generic in the argument so they compose: a field a CEL rule also
// constrains needs `Uuid & NonEmpty`, which is `nonEmpty(uuid(value))`.

export function uuid<T extends string>(value: T): T & Uuid {
  if (typeof value !== "string" || !UUID_PATTERN.test(value)) {
    throw new TypeError(`not a UUID: ${String(value)}`);
  }
  return value as T & Uuid;
}

export function email<T extends string>(value: T): T & Email {
  if (typeof value !== "string" || !EMAIL_PATTERN.test(value)) {
    throw new TypeError(`not an email address: ${String(value)}`);
  }
  return value as T & Email;
}

export function nonEmpty<T extends string>(value: T): T & NonEmpty {
  if (typeof value !== "string" || value.length === 0) {
    throw new TypeError("value must be a non-empty string");
  }
  return value as T & NonEmpty;
}

/**
 * Replaces the type of every property named in `M` and keeps the rest of `T`.
 * Optionality and readonly survive, so `{ createdAt?: Timestamp }` narrowed with
 * `{ createdAt: never }` becomes `{ createdAt?: never }`: the field may be
 * omitted, and nothing but `undefined` assigned to it.
 *
 * The constraint on `M` makes every override prove it narrows the property it
 * replaces, which is what the generated-output type-check tests the emitter with.
 */
export type Narrow<T, M extends { [K in keyof M]: K extends keyof T ? T[K] : never }> = {
  [K in keyof T]: K extends keyof M ? M[K] : T[K];
};

/**
 * Makes every property named in `K` required, for the fields a rule declares present.
 *
 * `Required` drops the `?` but not an `undefined` written into the property
 * type itself, which protoc-gen-es does emit — so a `required` field is narrowed
 * with `NonNullable` first and lifted here second.
 */
export type Require<T, K extends keyof T> = T & Required<Pick<T, K>>;

/** A list a `repeated.min_items` rule guarantees is not empty. */
export type NonEmptyList<T extends readonly unknown[]> = [T[number], ...T[number][]];
