# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: example/v1/user.proto
"""buf.validate rules for example/v1/user.proto.

One typing.Annotated alias per constrained field, over the type
protoc-gen-python already declared. The message classes stay in
example.v1.user_pb2; import them from there.

A rule with an annotated_types equivalent is carried as that constructor,
which pydantic, msgspec and beartype enforce. The rest are metadata strings,
left to protovalidate at runtime.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from annotated_types import Gt, Le, MaxLen, MinLen

# User demonstrates standard buf.validate rules alongside custom CEL rules.
UserId = Annotated[
    str,
    MaxLen(64),
    MinLen(5),
    "cel[user.id.prefix]: this.startsWith('usr_')",
    "  message: id must start with 'usr_'",
    "  refs: this",
    "  calls: startsWith",
]
UserEmail = Annotated[
    str,
    "required",
    "string.email = true",
]
UserDisplayName = Annotated[
    str,
    MinLen(3),
    "string.pattern = ^[a-zA-Z0-9_ ]+$",
]
UserAge = Annotated[
    int,
    Gt(0),
    Le(130),
]
UserLoginCount = Annotated[
    int,
    "cel[this >= 0]: this >= 0",
    "  refs: this",
    "  calls: _>=_",
]
UserRoles = Annotated[
    Sequence[str],
    "repeated.items.string.min_len = 1",
    MinLen(1),
    "repeated.unique = true",
]

# Address is referenced by User to exercise message-typed fields.
AddressCountry = Annotated[
    str,
    MinLen(2),
    MaxLen(2),
]
AddressPostalCode = Annotated[
    str,
    MinLen(3),
]

