// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: example/v1/user.proto

import type { Email, Narrow, NonEmptyList } from "../../strict/types";
import type { Address, User } from "./user_pb";
import { UserSchema } from "./user_pb";
import type { GenMessage } from "@bufbuild/protobuf/codegenv2";

/**
 * User demonstrates standard buf.validate rules alongside custom CEL rules.
 *
 * Left to runtime validation, having no type equivalent:
 *   id
 *     string.max_len = 64
 *     string.min_len = 5
 *     cel[user.id.prefix]: this.startsWith('usr_')
 *       message: id must start with 'usr_'
 *       refs: this
 *       calls: startsWith
 *   display_name
 *     string.min_len = 3
 *     string.pattern = ^[a-zA-Z0-9_ ]+$
 *   age
 *     int32.gt = 0
 *     int32.lte = 130
 *   login_count
 *     cel[this >= 0]: this >= 0
 *       refs: this
 *       calls: _>=_
 */
export type UserStrict = Narrow<User, {
  /**
   * required
   * string.email = true
   *
   * Carried into the type: string.email.
   */
  email: Email;
  /**
   * repeated.items.string.min_len = 1
   * repeated.min_items = 1
   * repeated.unique = true
   *
   * Carried into the type: repeated.min_items.
   */
  roles: NonEmptyList<User["roles"]>;
}>;

/**
 * Address is referenced by User to exercise message-typed fields.
 *
 * Left to runtime validation, having no type equivalent:
 *   country
 *     string.len = 2
 *   postal_code
 *     string.min_len = 3
 */
export type AddressStrict = Address;

/**
 * Describes example.v1.User, reporting UserStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const UserStrictSchema =
  UserSchema as GenMessage<User, { validType: UserStrict }>;

