# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: example/v1/user.proto
"""buf.validate rules for example/v1/user.proto.

Types come from example.v1.user_pb2 and are re-exported here, so one
import gives a caller both the message class and its annotated field types.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from example.v1.user_pb2 import (
    Address as Address,
    User as User,
)

# User demonstrates standard buf.validate rules alongside custom CEL rules.
UserId = Annotated[
    str,
    "string.max_len = 64",
    "string.min_len = 5",
    "cel[user.id.prefix]: this.startsWith('usr_')",
    "  message: id must start with 'usr_'",
    "  refs: this",
    "  calls: startsWith",
]
UserEmail = Annotated[
    str,
    "required",
    "string.email = true",
]
UserDisplayName = Annotated[
    str,
    "string.min_len = 3",
    "string.pattern = ^[a-zA-Z0-9_ ]+$",
]
UserAge = Annotated[
    int,
    "int32.gt = 0",
    "int32.lte = 130",
]
UserLoginCount = Annotated[
    int,
    "cel[this >= 0]: this >= 0",
    "  refs: this",
    "  calls: _>=_",
]
UserRoles = Annotated[
    Sequence[str],
    "repeated.items.string.min_len = 1",
    "repeated.min_items = 1",
    "repeated.unique = true",
]

# Address is referenced by User to exercise message-typed fields.
AddressCountry = Annotated[
    str,
    "string.len = 2",
]
AddressPostalCode = Annotated[
    str,
    "string.min_len = 3",
]

