// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: example/v1/user.proto

import type { Email, Narrow, NonEmpty, NonEmptyList } from "../../strict/types";
import type { Address, User } from "./user_pb";

/**
 * User demonstrates standard buf.validate rules alongside custom CEL rules.
 *
 * Left to runtime validation, having no type equivalent:
 *   age
 *     int32.gt = 0
 *     int32.lte = 130
 *   login_count
 *     cel[this >= 0]: this >= 0
 *       refs: this
 *       calls: _>=_
 */
export type UserStrict = Narrow<User, {
  /**
   * string.max_len = 64
   * string.min_len = 5
   * cel[user.id.prefix]: this.startsWith('usr_')
   *   message: id must start with 'usr_'
   *   refs: this
   *   calls: startsWith
   *
   * Carried into the type: string.min_len.
   */
  id: NonEmpty;
  /**
   * required
   * string.email = true
   *
   * Carried into the type: required, string.email.
   */
  email: Email;
  /**
   * string.min_len = 3
   * string.pattern = ^[a-zA-Z0-9_ ]+$
   *
   * Carried into the type: string.min_len.
   */
  displayName: NonEmpty;
  /**
   * repeated.items.string.min_len = 1
   * repeated.min_items = 1
   * repeated.unique = true
   *
   * Carried into the type: repeated.min_items.
   */
  roles: NonEmptyList<User["roles"]>;
  address: AddressStrict;
}>;

/**
 * Address is referenced by User to exercise message-typed fields.
 *
 * Left to runtime validation, having no type equivalent:
 *   country
 *     string.len = 2
 */
export type AddressStrict = Narrow<Address, {
  /**
   * string.min_len = 3
   *
   * Carried into the type: string.min_len.
   */
  postalCode: NonEmpty;
}>;

