# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/common/v1/common.proto
"""buf.validate rules for shop/common/v1/common.proto.

One typing.Annotated alias per constrained field, over the type
protoc-gen-python already declared. The message classes stay in
shop.common.v1.common_pb2; import them from there.

A rule with an annotated_types equivalent is carried as that constructor,
which pydantic, msgspec and beartype enforce. The rest are metadata strings,
left to protovalidate at runtime.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Annotated

from annotated_types import Ge, Gt, Le, MaxLen, MinLen

from google.protobuf import timestamp_pb2 as _google_protobuf_timestamp_pb2
from shop.common.v1.common_pb2 import Currency, SortDirection

# Currency is the ISO-4217 subset this demo API accepts.
# Without CURRENCY_UNSPECIFIED, the member protobuf numbers 0, which this overlay
# reads as "unset" rather than a value. No buf.validate rule says so; the
# convention that names it <ENUM>_UNSPECIFIED does.
CurrencyStrict = Annotated[
    Currency,
    Ge(1),
]

# SortDirection orders a list response.
# Without SORT_DIRECTION_UNSPECIFIED, the member protobuf numbers 0, which this overlay
# reads as "unset" rather than a value. No buf.validate rule says so; the
# convention that names it <ENUM>_UNSPECIFIED does.
SortDirectionStrict = Annotated[
    SortDirection,
    Ge(1),
]

# Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
# cel[money.consistent_sign]: this.units == 0 || this.nanos == 0 || (this.units > 0) == (this.nanos > 0)
#   message: units and nanos must have the same sign
#   refs: nanos, this, units
#   calls: _==_, _>_, _||_
MoneyUnits = Annotated[
    int,
    Ge(-1000000000),
    Le(1000000000),
]
MoneyNanos = Annotated[
    int,
    Ge(-999999999),
    Le(999999999),
]
MoneyCurrency = Annotated[
    CurrencyStrict,
    "required",
    "enum.defined_only = true",
    "enum.not_in = [0]",
]

# Pagination is the page selector shared by every list request.
PaginationPage = Annotated[
    int,
    Ge(1),
]
PaginationPageSize = Annotated[
    int,
    Gt(0),
    Le(100),
]
PaginationPageToken = Annotated[
    str,
    MaxLen(512),
    MinLen(8),
]

# TimeRange is a half-open interval [start, end).
# cel[time_range.ordered]: !has(this.end) || this.start < this.end
#   message: end must be strictly after start
#   refs: end, start, this
#   calls: !_, _<_, _||_
TimeRangeStart = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "required",
]

# LabelSet is a bounded set of user-supplied key/value labels.
LabelSetLabels = Annotated[
    Mapping[str, str],
    "map.keys.string.max_len = 63",
    "map.keys.string.min_len = 1",
    "map.keys.string.pattern = ^[a-z][a-z0-9_-]*$",
    MaxLen(32),
    MinLen(1),
    "map.values.string.max_len = 255",
]

