# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/common/v1/common.proto
"""buf.validate rules for shop/common/v1/common.proto.

Types come from shop.common.v1.common_pb2 and are re-exported here, so one
import gives a caller both the message class and its annotated field types.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Annotated

from google.protobuf import timestamp_pb2 as _timestamp_pb2
from shop.common.v1.common_pb2 import (
    Currency as Currency,
    LabelSet as LabelSet,
    Money as Money,
    Pagination as Pagination,
    TimeRange as TimeRange,
)

# Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
# cel[money.consistent_sign]: this.units == 0 || this.nanos == 0 || (this.units > 0) == (this.nanos > 0)
#   message: units and nanos must have the same sign
#   refs: nanos, this, units
#   calls: _==_, _>_, _||_
MoneyUnits = Annotated[
    int,
    "int64.gte = -1000000000",
    "int64.lte = 1000000000",
]
MoneyNanos = Annotated[
    int,
    "int32.gte = -999999999",
    "int32.lte = 999999999",
]
MoneyCurrency = Annotated[
    Currency,
    "required",
    "enum.defined_only = true",
    "enum.not_in = [0]",
]

# Pagination is the page selector shared by every list request.
PaginationPage = Annotated[
    int,
    "int32.gte = 1",
]
PaginationPageSize = Annotated[
    int,
    "int32.gt = 0",
    "int32.lte = 100",
]
PaginationPageToken = Annotated[
    str,
    "string.max_len = 512",
    "string.min_len = 8",
]

# TimeRange is a half-open interval [start, end).
# cel[time_range.ordered]: !has(this.end) || this.start < this.end
#   message: end must be strictly after start
#   refs: end, start, this
#   calls: !_, _<_, _||_
TimeRangeStart = Annotated[
    _timestamp_pb2.Timestamp,
    "required",
]

# LabelSet is a bounded set of user-supplied key/value labels.
LabelSetLabels = Annotated[
    Mapping[str, str],
    "map.keys.string.max_len = 63",
    "map.keys.string.min_len = 1",
    "map.keys.string.pattern = ^[a-z][a-z0-9_-]*$",
    "map.max_pairs = 32",
    "map.min_pairs = 1",
    "map.values.string.max_len = 255",
]

