// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: shop/common/v1/common.proto

import type { Narrow, NonEmpty, Require } from "../../../strict/types";
import type { LabelSet, Money, Pagination, TimeRange } from "./common_pb";

/**
 * Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[money.consistent_sign]
 *     this.units == 0 || this.nanos == 0 || this.units > 0 == (this.nanos > 0)
 *     message: units and nanos must have the same sign
 *   units
 *     int64.gte = -1000000000
 *     int64.lte = 1000000000
 *   nanos
 *     int32.gte = -999999999
 *     int32.lte = 999999999
 */
export type MoneyStrict = Narrow<Money, {
  /**
   * required
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried into the type: enum.not_in.
   */
  currency: Exclude<Money["currency"], 0>;
}>;

/**
 * Pagination is the page selector shared by every list request.
 *
 * Left to runtime validation, having no type equivalent:
 *   page
 *     int32.gte = 1
 *   page_size
 *     int32.gt = 0
 *     int32.lte = 100
 */
export type PaginationStrict = Narrow<Pagination, {
  /**
   * string.max_len = 512
   * string.min_len = 8
   *
   * Carried into the type: string.min_len.
   */
  pageToken: NonEmpty;
}>;

/**
 * TimeRange is a half-open interval [start, end).
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[time_range.ordered]
 *     !has(this.end) || this.start < this.end
 *     message: end must be strictly after start
 */
export type TimeRangeStrict = Require<Narrow<TimeRange, {
  /**
   * required
   *
   * Carried into the type: required.
   */
  start: NonNullable<TimeRange["start"]>;
}>, "start">;

/**
 * LabelSet is a bounded set of user-supplied key/value labels.
 *
 * Left to runtime validation, having no type equivalent:
 *   labels
 *     map.keys.string.max_len = 63
 *     map.keys.string.min_len = 1
 *     map.keys.string.pattern = ^[a-z][a-z0-9_-]*$
 *     map.max_pairs = 32
 *     map.min_pairs = 1
 *     map.values.string.max_len = 255
 */
export type LabelSetStrict = LabelSet;

