// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/inventory/v1/warehouse.proto

import contactPointBundle from "../../../jsonschema/shop.inventory.v1.ContactPoint.jsonschema.bundle.json" with { type: "json" };
import openingHoursBundle from "../../../jsonschema/shop.inventory.v1.OpeningHours.jsonschema.bundle.json" with { type: "json" };
import stockLevelBundle from "../../../jsonschema/shop.inventory.v1.StockLevel.jsonschema.bundle.json" with { type: "json" };
import stockMovementBundle from "../../../jsonschema/shop.inventory.v1.StockMovement.jsonschema.bundle.json" with { type: "json" };
import warehouseBundle from "../../../jsonschema/shop.inventory.v1.Warehouse.jsonschema.bundle.json" with { type: "json" };
import { loosen } from "../../../strict/jsonschema";

/**
 * Warehouse is a physical stocking location.
 *
 * JSON Schema 2020-12 for shop.inventory.v1.Warehouse, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   max_dwell_time
 *     duration.gte.seconds = 3600
 *     duration.lte.seconds = 2592000
 *   opening_hours
 *     map.max_pairs = 7
 *   absent fields
 *     id, name, opening_hours, contacts: an absent key is the zero value, which the rules still apply to
 *   Address.country_code
 *     string.pattern = ^[A-Z]{2}$
 *   Address.absent fields
 *     line1, city, country_code, postal_code: an absent key is the zero value, which the rules still apply to
 */
export const warehouseJsonSchema = loosen(warehouseBundle);

/**
 * OpeningHours is a daily window expressed in minutes past midnight.
 *
 * JSON Schema 2020-12 for shop.inventory.v1.OpeningHours, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[opening_hours.ordered]
 *     this.closes_at_minute > this.opens_at_minute
 *     message: closes_at_minute must be after opens_at_minute
 *   opens_at_minute
 *     uint32.lte = 1439
 *   closes_at_minute
 *     uint32.lte = 1440
 *   absent fields
 *     opens_at_minute, closes_at_minute: an absent key is the zero value, which the rules still apply to
 */
export const openingHoursJsonSchema = loosen(openingHoursBundle);

/**
 * ContactPoint reaches a person by exactly one channel.
 *
 * JSON Schema 2020-12 for shop.inventory.v1.ContactPoint, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   required oneof channel: exactly one of email, phone, extension
 *   email
 *     string.email = true
 *   phone
 *     string.pattern = ^\+[1-9][0-9]{7,14}$
 *   extension
 *     uint32.gte = 100
 *     uint32.lte = 9999
 *   absent fields
 *     name: an absent key is the zero value, which the rules still apply to
 */
export const contactPointJsonSchema = loosen(contactPointBundle);

/**
 * StockMovement records one change to the stock level of a product.
 *
 * JSON Schema 2020-12 for shop.inventory.v1.StockMovement, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   oneof: at most one of purchase_order_id, customer_order_id
 *   cel[stock_movement.quantity_sign]
 *     (this.kind == 2 && this.quantity_delta < 0) || (this.kind == 1 && this.quantity_delta > 0) || this.kind == 3
 *     message: outbound movements require a negative quantity, inbound a positive one
 *   quantity_delta
 *     sint32.gte = -100000
 *     sint32.lte = 100000
 *   occurred_at
 *     timestamp.lt_now = true
 *   purchase_order_id
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     string.max_len = 64
 *   customer_order_id
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     string.max_len = 64
 *   absent fields
 *     id, kind, quantity_delta: an absent key is the zero value, which the rules still apply to
 */
export const stockMovementJsonSchema = loosen(stockMovementBundle);

/**
 * StockLevel is the current quantity of a product in a warehouse.
 *
 * JSON Schema 2020-12 for shop.inventory.v1.StockLevel, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[stock_level.reserved_within_on_hand]
 *     this.reserved <= this.on_hand
 *     message: reserved must not exceed on_hand
 *   on_hand
 *     uint64.lte = 100000000
 *   reserved
 *     uint64.lte = 100000000
 *   counted_at
 *     timestamp.within.seconds = 7776000
 *   reorder_threshold
 *     cel[this <= 10000]: this <= 10000
 *       refs: this
 *       calls: _<=_
 *   absent fields
 *     product_id, on_hand, reserved, reorder_threshold: an absent key is the zero value, which the rules still apply to
 */
export const stockLevelJsonSchema = loosen(stockLevelBundle);
