// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: example/v1/user.proto

import { z } from "zod/v3";
import { field, message, register } from "../../strict/protovalidate.js";
import { AddressSchema, UserSchema, file_example_v1_user } from "./user_pb.js";

register(file_example_v1_user);

/**
 * Address is referenced by User to exercise message-typed fields.
 *
 * The composable schema of example.v1.Address: every field carries its own rules, so
 * `addressZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in addressZod.
 */
export const addressZodObject = z.strictObject({
  /**
   * string.len = 2
   *
   * Checked by protovalidate: string.len.
   */
  country: z.string().superRefine(field(AddressSchema, "country")).optional(),
  /**
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  postalCode: z.string().superRefine(field(AddressSchema, "postal_code")).optional(),
});

/**
 * Full validation of example.v1.Address. Adds what protovalidate checks on the whole message:
 *   the rules of country, postal_code when absent: protojson omits a zero value
 */
export const addressZod = addressZodObject.superRefine(message(AddressSchema));

/**
 * User demonstrates standard buf.validate rules alongside custom CEL rules.
 *
 * The composable schema of example.v1.User: every field carries its own rules, so
 * `userZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in userZod.
 */
export const userZodObject = z.strictObject({
  /**
   * string.max_len = 64
   * string.min_len = 5
   * cel[user.id.prefix]: this.startsWith('usr_')
   *   message: id must start with 'usr_'
   *   refs: this
   *   calls: startsWith
   *
   * Checked by protovalidate: string.max_len, string.min_len, cel[user.id.prefix].
   */
  id: z.string().superRefine(field(UserSchema, "id")).optional(),
  /**
   * required
   * string.email = true
   *
   * Carried by Zod: required, string.email.
   */
  email: z.string().regex(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/).min(1),
  /**
   * string.min_len = 3
   * string.pattern = ^[a-zA-Z0-9_ ]+$
   *
   * Checked by protovalidate: string.min_len, string.pattern.
   */
  displayName: z.string().superRefine(field(UserSchema, "display_name")).optional(),
  /**
   * int32.gt = 0
   * int32.lte = 130
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  age: z.number().int().gt(0).lte(130).optional(),
  /**
   * cel[this >= 0]: this >= 0
   *   refs: this
   *   calls: _>=_
   *
   * Checked by protovalidate: cel[this >= 0].
   */
  loginCount: z.number().int().superRefine(field(UserSchema, "login_count")).optional(),
  /**
   * repeated.items.string.min_len = 1
   * repeated.min_items = 1
   * repeated.unique = true
   *
   * Carried by Zod: repeated.min_items.
   * Checked by protovalidate: repeated.items.string.min_len, repeated.unique.
   */
  roles: z.array(z.string()).min(1).superRefine(field(UserSchema, "roles", ["repeated.min_items"])).optional(),
  address: addressZod.optional(),
});

/**
 * Full validation of example.v1.User. Adds what protovalidate checks on the whole message:
 *   the rules of id, display_name, age, login_count, roles when absent: protojson omits a zero value
 */
export const userZod = userZodObject.superRefine(message(UserSchema));
