// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: example/v1/user.proto

import { z } from "zod/v3";

/**
 * Address is referenced by User to exercise message-typed fields.
 *
 * The composable schema of example.v1.Address: every field carries its own rules, so
 * `addressZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in addressZod.
 */
export declare const addressZodObject: z.ZodObject<{
  /**
   * string.len = 2
   *
   * Checked by protovalidate: string.len.
   */
  country: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  postalCode: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of example.v1.Address. Adds what protovalidate checks on the whole message:
 *   the rules of country, postal_code when absent: protojson omits a zero value
 */
export declare const addressZod: z.ZodEffects<typeof addressZodObject>;

/**
 * User demonstrates standard buf.validate rules alongside custom CEL rules.
 *
 * The composable schema of example.v1.User: every field carries its own rules, so
 * `userZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in userZod.
 */
export declare const userZodObject: z.ZodObject<{
  /**
   * string.max_len = 64
   * string.min_len = 5
   * cel[user.id.prefix]: this.startsWith('usr_')
   *   message: id must start with 'usr_'
   *   refs: this
   *   calls: startsWith
   *
   * Checked by protovalidate: string.max_len, string.min_len, cel[user.id.prefix].
   */
  id: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * required
   * string.email = true
   *
   * Carried by Zod: required, string.email.
   */
  email: z.ZodString;
  /**
   * string.min_len = 3
   * string.pattern = ^[a-zA-Z0-9_ ]+$
   *
   * Checked by protovalidate: string.min_len, string.pattern.
   */
  displayName: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * int32.gt = 0
   * int32.lte = 130
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  age: z.ZodOptional<z.ZodNumber>;
  /**
   * cel[this >= 0]: this >= 0
   *   refs: this
   *   calls: _>=_
   *
   * Checked by protovalidate: cel[this >= 0].
   */
  loginCount: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
  /**
   * repeated.items.string.min_len = 1
   * repeated.min_items = 1
   * repeated.unique = true
   *
   * Carried by Zod: repeated.min_items.
   * Checked by protovalidate: repeated.items.string.min_len, repeated.unique.
   */
  roles: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  address: z.ZodOptional<typeof addressZod>;
}, "strict">;

/**
 * Full validation of example.v1.User. Adds what protovalidate checks on the whole message:
 *   the rules of id, display_name, age, login_count, roles when absent: protojson omits a zero value
 */
export declare const userZod: z.ZodEffects<typeof userZodObject>;
