// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/common/v1/common.proto

import { z } from "zod";
import { field, message, register } from "../../../strict/protovalidate.js";
import { timestampZod } from "../../../strict/wkt.zod.js";
import { LabelSetSchema, MoneySchema, PaginationSchema, TimeRangeSchema, file_shop_common_v1_common } from "./common_pb.js";

register(file_shop_common_v1_common);

/**
 * Currency is the ISO-4217 subset this demo API accepts.
 *
 * shop.common.v1.Currency, as protojson writes it: the member's name.
 */
export const currencyZod = z.enum(["CURRENCY_UNSPECIFIED", "CURRENCY_EUR", "CURRENCY_USD", "CURRENCY_GBP"]);

/**
 * SortDirection orders a list response.
 *
 * shop.common.v1.SortDirection, as protojson writes it: the member's name.
 */
export const sortDirectionZod = z.enum(["SORT_DIRECTION_UNSPECIFIED", "SORT_DIRECTION_ASC", "SORT_DIRECTION_DESC"]);

/**
 * Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
 *
 * The composable schema of shop.common.v1.Money: every field carries its own rules, so
 * `moneyZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in moneyZod.
 */
export const moneyZodObject = z.strictObject({
  /**
   * int64.gte = -1000000000
   * int64.lte = 1000000000
   *
   * Checked by protovalidate: int64.gte, int64.lte.
   */
  units: z.string().regex(/^-?[0-9]+$/).superRefine(field(MoneySchema, "units")).optional(),
  /**
   * int32.gte = -999999999
   * int32.lte = 999999999
   *
   * Carried by Zod: int32.gte, int32.lte.
   */
  nanos: z.number().int().gte(-999999999).lte(999999999).optional(),
  /**
   * required
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried by Zod: required, enum.defined_only, enum.not_in.
   */
  currency: z.enum(["CURRENCY_EUR", "CURRENCY_USD", "CURRENCY_GBP"]),
});

/**
 * Full validation of shop.common.v1.Money. Adds what protovalidate checks on the whole message:
 *   cel[money.consistent_sign]
 *   the rules of units, nanos when absent: protojson omits a zero value
 */
export const moneyZod = moneyZodObject.superRefine(message(MoneySchema));

/**
 * Pagination is the page selector shared by every list request.
 *
 * The composable schema of shop.common.v1.Pagination: every field carries its own rules, so
 * `paginationZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in paginationZod.
 */
export const paginationZodObject = z.strictObject({
  /**
   * int32.gte = 1
   *
   * Carried by Zod: int32.gte.
   */
  page: z.number().int().gte(1).optional(),
  /**
   * int32.gt = 0
   * int32.lte = 100
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  pageSize: z.number().int().gt(0).lte(100).optional(),
  /**
   * string.max_len = 512
   * string.min_len = 8
   *
   * Carried by Zod: string.max_len, string.min_len.
   */
  pageToken: z.string().max(512).min(8).optional(),
});

/**
 * Full validation of shop.common.v1.Pagination. Adds what protovalidate checks on the whole message:
 *   the rules of page, page_size when absent: protojson omits a zero value
 */
export const paginationZod = paginationZodObject.superRefine(message(PaginationSchema));

/**
 * TimeRange is a half-open interval [start, end).
 *
 * The composable schema of shop.common.v1.TimeRange: every field carries its own rules, so
 * `timeRangeZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in timeRangeZod.
 */
export const timeRangeZodObject = z.strictObject({
  /**
   * required
   *
   * Carried by Zod: required.
   */
  start: timestampZod,
  end: timestampZod.optional(),
});

/**
 * Full validation of shop.common.v1.TimeRange. Adds what protovalidate checks on the whole message:
 *   cel[time_range.ordered]
 */
export const timeRangeZod = timeRangeZodObject.superRefine(message(TimeRangeSchema));

/**
 * LabelSet is a bounded set of user-supplied key/value labels.
 *
 * The composable schema of shop.common.v1.LabelSet: every field carries its own rules, so
 * `labelSetZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in labelSetZod.
 */
export const labelSetZodObject = z.strictObject({
  /**
   * map.keys.string.max_len = 63
   * map.keys.string.min_len = 1
   * map.keys.string.pattern = ^[a-z][a-z0-9_-]*$
   * map.max_pairs = 32
   * map.min_pairs = 1
   * map.values.string.max_len = 255
   *
   * Checked by protovalidate: map.keys.string.max_len, map.keys.string.min_len, map.keys.string.pattern, map.max_pairs, map.min_pairs, map.values.string.max_len.
   */
  labels: z.record(z.string(), z.string()).superRefine(field(LabelSetSchema, "labels")).optional(),
});

/**
 * Full validation of shop.common.v1.LabelSet. Adds what protovalidate checks on the whole message:
 *   the rules of labels when absent: protojson omits a zero value
 */
export const labelSetZod = labelSetZodObject.superRefine(message(LabelSetSchema));
