// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/schema/v1/schema.proto

import { z } from "zod/v3";
import { anyZod, boolValueZod, bytesValueZod, doubleValueZod, durationZod, emptyZod, fieldMaskZod, floatValueZod, int32ValueZod, int64ValueZod, listValueZod, nullValueZod, stringValueZod, structZod, timestampZod, uInt32ValueZod, uInt64ValueZod, valueZod } from "../../../strict/wkt.zod3.js";

/**
 * SchemaColor exercises the enum rules and the enum JSON shape.
 *
 * shop.schema.v1.SchemaColor, as protojson writes it: the member's name.
 */
export declare const schemaColorZod: z.ZodEnum<["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]>;

/**
 * Item is the rule-bearing message other fixtures reference. Its empty instance is valid, so a reference to it tests presence and nesting only.
 *
 * The composable schema of shop.schema.v1.Item: every field carries its own rules, so
 * `itemZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in itemZod.
 */
export declare const itemZodObject: z.ZodObject<{
  /**
   * string.max_len = 32
   *
   * Checked by protovalidate: string.max_len.
   */
  text: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/** Full validation of shop.schema.v1.Item: the message has no rule beyond its fields'. */
export declare const itemZod: typeof itemZodObject;

/**
 * FormatCoverage has one field per string well-known format. Every field has explicit presence, so a test can set one at a time.
 *
 * The composable schema of shop.schema.v1.FormatCoverage: every field carries its own rules, so
 * `formatCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in formatCoverageZod.
 */
export declare const formatCoverageZodObject: z.ZodObject<{
  /**
   * string.hostname = true
   *
   * Checked by protovalidate: string.hostname.
   */
  hostname: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.ZodOptional<z.ZodString>;
  /**
   * string.ip = true
   *
   * Checked by protovalidate: string.ip.
   */
  ip: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv4 = true
   *
   * Checked by protovalidate: string.ipv4.
   */
  ipv4: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv6 = true
   *
   * Checked by protovalidate: string.ipv6.
   */
  ipv6: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.uri = true
   *
   * Checked by protovalidate: string.uri.
   */
  uri: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.uri_ref = true
   *
   * Checked by protovalidate: string.uri_ref.
   */
  uriRef: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.address = true
   *
   * Checked by protovalidate: string.address.
   */
  address: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.host_and_port = true
   *
   * Checked by protovalidate: string.host_and_port.
   */
  hostAndPort: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ip_with_prefixlen = true
   *
   * Checked by protovalidate: string.ip_with_prefixlen.
   */
  ipWithPrefixlen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv4_with_prefixlen = true
   *
   * Checked by protovalidate: string.ipv4_with_prefixlen.
   */
  ipv4WithPrefixlen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv6_with_prefixlen = true
   *
   * Checked by protovalidate: string.ipv6_with_prefixlen.
   */
  ipv6WithPrefixlen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ip_prefix = true
   *
   * Checked by protovalidate: string.ip_prefix.
   */
  ipPrefix: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv4_prefix = true
   *
   * Checked by protovalidate: string.ipv4_prefix.
   */
  ipv4Prefix: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.ipv6_prefix = true
   *
   * Checked by protovalidate: string.ipv6_prefix.
   */
  ipv6Prefix: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  uuid: z.ZodOptional<z.ZodString>;
  /**
   * string.tuuid = true
   *
   * Carried by Zod: string.tuuid.
   */
  tuuid: z.ZodOptional<z.ZodString>;
  /**
   * string.ulid = true
   *
   * Carried by Zod: string.ulid.
   */
  ulid: z.ZodOptional<z.ZodString>;
  /**
   * string.protobuf_fqn = true
   *
   * Carried by Zod: string.protobuf_fqn.
   */
  protobufFqn: z.ZodOptional<z.ZodString>;
  /**
   * string.protobuf_dot_fqn = true
   *
   * Carried by Zod: string.protobuf_dot_fqn.
   */
  protobufDotFqn: z.ZodOptional<z.ZodString>;
  /**
   * string.strict = true
   * string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_NAME
   *
   * Checked by protovalidate: string.strict, string.well_known_regex.
   */
  headerName: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_VALUE
   *
   * Checked by protovalidate: string.well_known_regex.
   */
  headerValue: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.hostname = true
   *
   * Checked by protovalidate: string.hostname.
   */
  hiddenHost: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/** Full validation of shop.schema.v1.FormatCoverage: the message has no rule beyond its fields'. */
export declare const formatCoverageZod: typeof formatCoverageZodObject;

/**
 * StringContentCoverage has one field per string length and content rule.
 *
 * The composable schema of shop.schema.v1.StringContentCoverage: every field carries its own rules, so
 * `stringContentCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stringContentCoverageZod.
 */
export declare const stringContentCoverageZodObject: z.ZodObject<{
  /**
   * string.min_len = 2
   *
   * Checked by protovalidate: string.min_len.
   */
  minLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_len = 8
   *
   * Checked by protovalidate: string.max_len.
   */
  maxLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.len = 4
   *
   * Checked by protovalidate: string.len.
   */
  exactLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.len_bytes = 4
   *
   * Checked by protovalidate: string.len_bytes.
   */
  lenBytes: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.min_bytes = 2
   *
   * Checked by protovalidate: string.min_bytes.
   */
  minBytes: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_bytes = 8
   *
   * Checked by protovalidate: string.max_bytes.
   */
  maxBytes: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.pattern = (?i)^abc$
   *
   * Checked by protovalidate: string.pattern.
   */
  patternInlineFlag: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.pattern = ^\S+$
   *
   * Checked by protovalidate: string.pattern.
   */
  patternNonSpace: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.prefix = +1
   *
   * Carried by Zod: string.prefix.
   */
  prefix: z.ZodOptional<z.ZodString>;
  /**
   * string.suffix = .io
   *
   * Carried by Zod: string.suffix.
   */
  suffix: z.ZodOptional<z.ZodString>;
  /**
   * string.contains = .
   *
   * Carried by Zod: string.contains.
   */
  contains: z.ZodOptional<z.ZodString>;
  /**
   * string.prefix = pre
   * string.suffix = suf
   *
   * Carried by Zod: string.prefix, string.suffix.
   */
  prefixAndSuffix: z.ZodOptional<z.ZodString>;
  /**
   * string.not_contains =  
   *
   * Checked by protovalidate: string.not_contains.
   */
  notContains: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.const = fixed
   *
   * Carried by Zod: string.const.
   */
  constValue: z.ZodOptional<z.ZodLiteral<"fixed">>;
  /**
   * string.in = [a, b, c]
   *
   * Carried by Zod: string.in.
   */
  inSet: z.ZodOptional<z.ZodEnum<["a, b", "c"]>>;
  /**
   * string.not_in = [x, y]
   *
   * Checked by protovalidate: string.not_in.
   */
  notInSet: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  nickname: z.ZodString;
  /**
   * string.min_len = 2
   * cel[string_content.code.no_spaces]: !this.contains(' ')
   *   message: code must not contain spaces
   *   refs: this
   *   calls: !_, contains
   *
   * Checked by protovalidate: string.min_len, cel[string_content.code.no_spaces].
   */
  code: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.pattern = ^[a-f0-9-]+$
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   * Checked by protovalidate: string.pattern.
   */
  uuidPattern: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.in = ["\*\/ , "\*\/x]
   * string.prefix = "\*\/
   * cel[string_content.escaped]: !this.endsWith('"*\/')
   *   message: must not end in "*\/"
   *   refs: this
   *   calls: !_, endsWith
   *
   * Carried by Zod: string.in.
   * Checked by protovalidate: string.prefix, cel[string_content.escaped].
   */
  escaped: z.ZodOptional<z.ZodEffects<z.ZodEnum<["\"\\*/\u2028", "\"\\*/x"]>>>;
}, "strict">;

/** Full validation of shop.schema.v1.StringContentCoverage: the message has no rule beyond its fields'. */
export declare const stringContentCoverageZod: typeof stringContentCoverageZodObject;

/**
 * ImplicitCoverage has implicit-presence fields whose zero value breaks a rule. protojson omits zero values, so the rule has to fire for an absent key.
 *
 * The composable schema of shop.schema.v1.ImplicitCoverage: every field carries its own rules, so
 * `implicitCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in implicitCoverageZod.
 */
export declare const implicitCoverageZodObject: z.ZodObject<{
  /**
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  shortCode: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * int32.gt = 0
   *
   * Carried by Zod: int32.gt.
   */
  count: z.ZodOptional<z.ZodNumber>;
  /**
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.min_items.
   */
  tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.ZodOptional<z.ZodString>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredName: z.ZodString;
  /**
   * required
   *
   * Checked by protovalidate: required.
   */
  requiredCount: z.ZodEffects<z.ZodNumber>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  accepted: z.ZodLiteral<true>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  color: z.ZodEnum<["SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredTags: z.ZodArray<z.ZodString>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredItem: typeof itemZod;
}, "strict">;

/**
 * Full validation of shop.schema.v1.ImplicitCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of short_code, count, tags, email when absent: protojson omits a zero value
 */
export declare const implicitCoverageZod: z.ZodEffects<typeof implicitCoverageZodObject>;

/**
 * BytesCoverage has one field per bytes rule. JSON carries bytes as base64, standard or URL-safe.
 *
 * The composable schema of shop.schema.v1.BytesCoverage: every field carries its own rules, so
 * `bytesCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in bytesCoverageZod.
 */
export declare const bytesCoverageZodObject: z.ZodObject<{
  raw: z.ZodOptional<z.ZodString>;
  /**
   * bytes.len = 4
   *
   * Checked by protovalidate: bytes.len.
   */
  exactLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.min_len = 2
   *
   * Checked by protovalidate: bytes.min_len.
   */
  minLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.max_len = 8
   *
   * Checked by protovalidate: bytes.max_len.
   */
  maxLen: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.pattern = ^[a-z]+$
   *
   * Checked by protovalidate: bytes.pattern.
   */
  pattern: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.prefix = [1 2]
   *
   * Checked by protovalidate: bytes.prefix.
   */
  prefix: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.ip = true
   *
   * Checked by protovalidate: bytes.ip.
   */
  ip: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * bytes.uuid = true
   *
   * Checked by protovalidate: bytes.uuid.
   */
  uuid: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  requiredBlob: z.ZodString;
}, "strict">;

/** Full validation of shop.schema.v1.BytesCoverage: the message has no rule beyond its fields'. */
export declare const bytesCoverageZod: typeof bytesCoverageZodObject;

/**
 * NumberCoverage has one field per numeric rule shape, over every JSON number form: int32-family numbers, int64-family strings, floats with NaN.
 *
 * The composable schema of shop.schema.v1.NumberCoverage: every field carries its own rules, so
 * `numberCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in numberCoverageZod.
 */
export declare const numberCoverageZodObject: z.ZodObject<{
  /**
   * int32.gt = 0
   * int32.lte = 100
   *
   * Carried by Zod: int32.gt, int32.lte.
   */
  bounded: z.ZodOptional<z.ZodNumber>;
  /**
   * int32.gt = 10
   * int32.lt = 5
   *
   * Checked by protovalidate: int32.gt, int32.lt.
   */
  reversedRange: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
  /**
   * int32.const = 7
   *
   * Carried by Zod: int32.const.
   */
  constValue: z.ZodOptional<z.ZodLiteral<7>>;
  /**
   * int32.in = [1, 2, 3]
   *
   * Carried by Zod: int32.in.
   */
  inSet: z.ZodOptional<z.ZodUnion<[z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>]>>;
  /**
   * int32.not_in = [0, -1]
   *
   * Checked by protovalidate: int32.not_in.
   */
  notInSet: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
  /**
   * uint32.gte = 1
   * uint32.lt = 65536
   *
   * Carried by Zod: uint32.gte, uint32.lt.
   */
  unsigned: z.ZodOptional<z.ZodNumber>;
  /**
   * sint32.gte = -128
   *
   * Carried by Zod: sint32.gte.
   */
  zigzag: z.ZodOptional<z.ZodNumber>;
  /**
   * fixed32.lte = 1000
   *
   * Carried by Zod: fixed32.lte.
   */
  fixed: z.ZodOptional<z.ZodNumber>;
  /**
   * sfixed32.lt = 0
   *
   * Carried by Zod: sfixed32.lt.
   */
  signedFixed: z.ZodOptional<z.ZodNumber>;
  /**
   * int64.gt = 0
   *
   * Checked by protovalidate: int64.gt.
   */
  big: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * uint64.lte = 1000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  bigUnsigned: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * float.finite = true
   *
   * Checked by protovalidate: float.finite.
   */
  ratio: z.ZodOptional<z.ZodEffects<z.ZodUnion<[z.ZodNumber, z.ZodEnum<["NaN", "Infinity", "-Infinity"]>]>>>;
  /**
   * double.gt = 0
   *
   * Checked by protovalidate: double.gt.
   */
  score: z.ZodOptional<z.ZodEffects<z.ZodUnion<[z.ZodNumber, z.ZodEnum<["NaN", "Infinity", "-Infinity"]>]>>>;
  /**
   * double.in = [0.5, 1, 2]
   *
   * Checked by protovalidate: double.in.
   */
  factor: z.ZodOptional<z.ZodEffects<z.ZodUnion<[z.ZodNumber, z.ZodEnum<["NaN", "Infinity", "-Infinity"]>]>>>;
  /**
   * float.lte = 0.1
   *
   * Checked by protovalidate: float.lte.
   */
  capped: z.ZodOptional<z.ZodEffects<z.ZodUnion<[z.ZodNumber, z.ZodEnum<["NaN", "Infinity", "-Infinity"]>]>>>;
}, "strict">;

/** Full validation of shop.schema.v1.NumberCoverage: the message has no rule beyond its fields'. */
export declare const numberCoverageZod: typeof numberCoverageZodObject;

/**
 * CollectionCoverage has one field per repeated and map shape.
 *
 * The composable schema of shop.schema.v1.CollectionCoverage: every field carries its own rules, so
 * `collectionCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in collectionCoverageZod.
 */
export declare const collectionCoverageZodObject: z.ZodObject<{
  /**
   * repeated.max_items = 3
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.max_items, repeated.min_items.
   */
  bounded: z.ZodOptional<z.ZodArray<z.ZodString>>;
  /**
   * repeated.unique = true
   *
   * Checked by protovalidate: repeated.unique.
   */
  unique: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /**
   * repeated.items.string.uri = true
   *
   * Checked by protovalidate: repeated.items.string.uri.
   */
  links: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /**
   * repeated.items.string.min_len = 1
   *
   * Checked by protovalidate: repeated.items.string.min_len.
   */
  names: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /**
   * map.keys.string.min_len = 2
   * map.max_pairs = 4
   * map.min_pairs = 1
   * map.values.string.uri = true
   *
   * Checked by protovalidate: map.keys.string.min_len, map.max_pairs, map.min_pairs, map.values.string.uri.
   */
  labels: z.ZodOptional<z.ZodEffects<z.ZodRecord<z.ZodString, z.ZodString>>>;
  flags: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
  byNumber: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
  items: z.ZodOptional<z.ZodArray<typeof itemZod>>;
  itemsByKey: z.ZodOptional<z.ZodRecord<z.ZodString, typeof itemZod>>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.CollectionCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of bounded, unique, labels when absent: protojson omits a zero value
 */
export declare const collectionCoverageZod: z.ZodEffects<typeof collectionCoverageZodObject>;

/**
 * IgnoreCoverage has rules that are skipped for the zero value, and a field that is never validated.
 *
 * The composable schema of shop.schema.v1.IgnoreCoverage: every field carries its own rules, so
 * `ignoreCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in ignoreCoverageZod.
 */
export declare const ignoreCoverageZodObject: z.ZodObject<{
  /**
   * ignore = IGNORE_IF_ZERO_VALUE
   * string.email = true
   *
   * Checked by protovalidate: string.email.
   */
  email: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * ignore = IGNORE_IF_ZERO_VALUE
   * int32.gt = 5
   *
   * Checked by protovalidate: int32.gt.
   */
  threshold: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
  /**
   * repeated.items.ignore = IGNORE_IF_ZERO_VALUE
   * repeated.items.string.uuid = true
   *
   * Checked by protovalidate: repeated.items.string.uuid.
   */
  ids: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /** ignore = IGNORE_ALWAYS */
  neverChecked: z.ZodOptional<z.ZodString>;
  /**
   * map.values.ignore = IGNORE_IF_ZERO_VALUE
   * map.values.string.min_len = 3
   *
   * Checked by protovalidate: map.values.string.min_len.
   */
  codes: z.ZodOptional<z.ZodEffects<z.ZodRecord<z.ZodString, z.ZodString>>>;
}, "strict">;

/** Full validation of shop.schema.v1.IgnoreCoverage: the message has no rule beyond its fields'. */
export declare const ignoreCoverageZod: typeof ignoreCoverageZodObject;

/**
 * OneofCoverage has both oneof kinds: real oneofs, flattened into the JSON object, and a message-level oneof rule over plain fields.
 *
 * The composable schema of shop.schema.v1.OneofCoverage: every field carries its own rules, so
 * `oneofCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in oneofCoverageZod.
 */
export declare const oneofCoverageZodObject: z.ZodObject<{
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.ZodOptional<z.ZodString>;
  phone: z.ZodOptional<z.ZodString>;
  query: z.ZodOptional<z.ZodString>;
  page: z.ZodOptional<z.ZodNumber>;
  firstName: z.ZodOptional<z.ZodString>;
  lastName: z.ZodOptional<z.ZodString>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.OneofCoverage. Adds what protovalidate checks on the whole message:
 *   required oneof contact: exactly one of email, phone
 *   oneof filter: at most one of query, page
 *   required oneof: exactly one of first_name, last_name
 */
export declare const oneofCoverageZod: z.ZodEffects<typeof oneofCoverageZodObject>;

/**
 * WellKnownCoverage has one field per well-known type the JSON shape maps.
 *
 * The composable schema of shop.schema.v1.WellKnownCoverage: every field carries its own rules, so
 * `wellKnownCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in wellKnownCoverageZod.
 */
export declare const wellKnownCoverageZodObject: z.ZodObject<{
  /**
   * duration.gte.seconds = 1
   * duration.lte.seconds = 300
   *
   * Checked by protovalidate: duration.gte.seconds, duration.lte.seconds.
   */
  timeout: z.ZodOptional<z.ZodEffects<typeof durationZod>>;
  /**
   * timestamp.gt_now = true
   *
   * Checked by protovalidate: timestamp.gt_now.
   */
  expiresAt: z.ZodOptional<z.ZodEffects<typeof timestampZod>>;
  createdAt: z.ZodOptional<typeof timestampZod>;
  /**
   * any.in = [type.googleapis.com/google.protobuf.Duration]
   *
   * Checked by protovalidate: any.in.
   */
  detail: z.ZodOptional<z.ZodEffects<typeof anyZod>>;
  metadata: z.ZodOptional<typeof structZod>;
  value: z.ZodOptional<typeof valueZod>;
  list: z.ZodOptional<typeof listValueZod>;
  nothing: z.ZodOptional<typeof emptyZod>;
  updateMask: z.ZodOptional<typeof fieldMaskZod>;
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  label: z.ZodOptional<z.ZodEffects<typeof stringValueZod>>;
  blob: z.ZodOptional<typeof bytesValueZod>;
  bigCount: z.ZodOptional<typeof int64ValueZod>;
  ratio: z.ZodOptional<typeof doubleValueZod>;
  flag: z.ZodOptional<typeof boolValueZod>;
  nullValue: z.ZodOptional<typeof nullValueZod>;
  /**
   * enum.defined_only = true
   *
   * Checked by protovalidate: enum.defined_only.
   */
  checkedNull: z.ZodOptional<z.ZodEffects<typeof nullValueZod>>;
  smallRatio: z.ZodOptional<typeof floatValueZod>;
  smallCount: z.ZodOptional<typeof int32ValueZod>;
  unsignedCount: z.ZodOptional<typeof uInt32ValueZod>;
  bigUnsigned: z.ZodOptional<typeof uInt64ValueZod>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.WellKnownCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of checked_null when absent: protojson omits a zero value
 */
export declare const wellKnownCoverageZod: z.ZodEffects<typeof wellKnownCoverageZodObject>;

/**
 * EnumCoverage has one field per enum rule, and a field without rules.
 *
 * The composable schema of shop.schema.v1.EnumCoverage: every field carries its own rules, so
 * `enumCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in enumCoverageZod.
 */
export declare const enumCoverageZodObject: z.ZodObject<{
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  defined: z.ZodOptional<z.ZodEnum<["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN", "SCHEMA_COLOR_BLUE"]>>;
  /**
   * enum.in = [1, 2]
   *
   * Carried by Zod: enum.in.
   */
  allowed: z.ZodOptional<z.ZodEnum<["SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN"]>>;
  /**
   * enum.not_in = [3]
   *
   * Carried by Zod: enum.not_in.
   */
  excluded: z.ZodOptional<z.ZodEnum<["SCHEMA_COLOR_UNSPECIFIED", "SCHEMA_COLOR_RED", "SCHEMA_COLOR_GREEN"]>>;
  /**
   * enum.const = 2
   *
   * Carried by Zod: enum.const.
   */
  pinned: z.ZodOptional<z.ZodEnum<["SCHEMA_COLOR_GREEN"]>>;
  plain: z.ZodOptional<typeof schemaColorZod>;
}, "strict">;

/** Full validation of shop.schema.v1.EnumCoverage: the message has no rule beyond its fields'. */
export declare const enumCoverageZod: typeof enumCoverageZodObject;

/**
 * JsonNameCoverage has fields whose JSON name differs from the proto name in ways a naive camelCase conversion gets wrong.
 *
 * The composable schema of shop.schema.v1.JsonNameCoverage: every field carries its own rules, so
 * `jsonNameCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in jsonNameCoverageZod.
 */
export declare const jsonNameCoverageZodObject: z.ZodObject<{
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  extId: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * int32.gte = 0
   *
   * Carried by Zod: int32.gte.
   */
  metric1st: z.ZodOptional<z.ZodNumber>;
  /**
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  displayName: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.JsonNameCoverage. Adds what protovalidate checks on the whole message:
 *   the rules of external_id, metric_1st, display_name when absent: protojson omits a zero value
 */
export declare const jsonNameCoverageZod: z.ZodEffects<typeof jsonNameCoverageZodObject>;

declare const treeNodeBase: z.ZodObject<{
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  label: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * ignore = IGNORE_ALWAYS
   *
   * protovalidate never evaluates the shop.schema.v1.TreeNode inside, so the field takes any value that decodes as one.
   */
  skipped: z.ZodOptional<z.ZodEffects<z.ZodUnknown>>;
}, "strict">;

type TreeNodeShape = z.input<typeof treeNodeBase> & { children?: TreeNodeShape[]; parent?: TreeNodeShape };

/**
 * TreeNode refers to itself, directly and through a list.
 *
 * The composable schema of shop.schema.v1.TreeNode: every field carries its own rules, so
 * `treeNodeZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in treeNodeZod.
 */
export declare const treeNodeZodObject: z.ZodObject<{
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  label: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  children: z.ZodOptional<z.ZodArray<z.ZodLazy<z.ZodType<TreeNodeShape>>>>;
  parent: z.ZodOptional<z.ZodLazy<z.ZodType<TreeNodeShape>>>;
  /**
   * ignore = IGNORE_ALWAYS
   *
   * protovalidate never evaluates the shop.schema.v1.TreeNode inside, so the field takes any value that decodes as one.
   */
  skipped: z.ZodOptional<z.ZodEffects<z.ZodUnknown>>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.TreeNode. Adds what protovalidate checks on the whole message:
 *   the rules of label when absent: protojson omits a zero value
 */
export declare const treeNodeZod: z.ZodEffects<typeof treeNodeZodObject>;

declare const pingBase: z.ZodObject<{
  /**
   * string.max_len = 140
   *
   * Checked by protovalidate: string.max_len.
   */
  note: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

type PingShape = z.input<typeof pingBase> & { pong?: PongShape };

/**
 * Ping and Pong refer to each other: a cycle across two messages.
 *
 * The composable schema of shop.schema.v1.Ping: every field carries its own rules, so
 * `pingZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in pingZod.
 */
export declare const pingZodObject: z.ZodObject<{
  pong: z.ZodOptional<z.ZodLazy<z.ZodType<PongShape>>>;
  /**
   * string.max_len = 140
   *
   * Checked by protovalidate: string.max_len.
   */
  note: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.Ping. Adds what protovalidate checks on the whole message:
 *   the rules of note when absent: protojson omits a zero value
 */
export declare const pingZod: z.ZodEffects<typeof pingZodObject>;

declare const pongBase: z.ZodObject<{
}, "strict">;

type PongShape = z.input<typeof pongBase> & { ping?: PingShape };

/**
 * Pong is the other half of the Ping cycle.
 *
 * The composable schema of shop.schema.v1.Pong: every field carries its own rules, so
 * `pongZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in pongZod.
 */
export declare const pongZodObject: z.ZodObject<{
  ping: z.ZodOptional<z.ZodLazy<z.ZodType<PingShape>>>;
}, "strict">;

/** Full validation of shop.schema.v1.Pong: the message has no rule beyond its fields'. */
export declare const pongZod: typeof pongZodObject;

/**
 * Window is nested to check that nested messages get their own schema.
 *
 * The composable schema of shop.schema.v1.MessageCelCoverage.Window: every field carries its own rules, so
 * `messageCelCoverageWindowZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageCelCoverageWindowZod.
 */
export declare const messageCelCoverageWindowZodObject: z.ZodObject<{
  startMinute: z.ZodOptional<z.ZodNumber>;
  endMinute: z.ZodOptional<z.ZodNumber>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.MessageCelCoverage.Window. Adds what protovalidate checks on the whole message:
 *   cel[message_cel.window.ordered]
 */
export declare const messageCelCoverageWindowZod: z.ZodEffects<typeof messageCelCoverageWindowZodObject>;

/**
 * MessageCelCoverage has a message-level CEL rule spanning two fields, and a nested message with a rule of its own.
 *
 * The composable schema of shop.schema.v1.MessageCelCoverage: every field carries its own rules, so
 * `messageCelCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageCelCoverageZod.
 */
export declare const messageCelCoverageZodObject: z.ZodObject<{
  low: z.ZodOptional<z.ZodNumber>;
  high: z.ZodOptional<z.ZodNumber>;
  window: z.ZodOptional<typeof messageCelCoverageWindowZod>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.MessageCelCoverage. Adds what protovalidate checks on the whole message:
 *   cel[message_cel.low_below_high]
 */
export declare const messageCelCoverageZod: z.ZodEffects<typeof messageCelCoverageZodObject>;

/**
 * MessageOneofCoverage has implicit fields named by a message-level oneof rule. protovalidate gives such a field IGNORE_IF_ZERO_VALUE, so its zero value passes its own rules.
 *
 * The composable schema of shop.schema.v1.MessageOneofCoverage: every field carries its own rules, so
 * `messageOneofCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in messageOneofCoverageZod.
 */
export declare const messageOneofCoverageZodObject: z.ZodObject<{
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.min_len = 3
   *
   * Checked by protovalidate: string.min_len.
   */
  code: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  label: z.ZodOptional<z.ZodString>;
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * repeated.min_items = 2
   *
   * Checked by protovalidate: repeated.min_items.
   */
  tags: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodString>>>;
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * enum.defined_only = true
   *
   * Checked by protovalidate: enum.defined_only.
   */
  color: z.ZodOptional<z.ZodEffects<typeof schemaColorZod>>;
  /** ignore = IGNORE_ALWAYS */
  alias: z.ZodOptional<z.ZodString>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.MessageOneofCoverage. Adds what protovalidate checks on the whole message:
 *   oneof: at most one of code, label, tags, color, alias
 */
export declare const messageOneofCoverageZod: z.ZodEffects<typeof messageOneofCoverageZodObject>;

/**
 * EvaluationCoverage has a message rule that fails to evaluate while divisor is 0, the value divisor holds in the message field() checks total in.
 *
 * The composable schema of shop.schema.v1.EvaluationCoverage: every field carries its own rules, so
 * `evaluationCoverageZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in evaluationCoverageZod.
 */
export declare const evaluationCoverageZodObject: z.ZodObject<{
  divisor: z.ZodOptional<z.ZodNumber>;
  /**
   * cel[this % 2 == 0]: this % 2 == 0
   *   refs: this
   *   calls: _%_, _==_
   *
   * Checked by protovalidate: cel[this % 2 == 0].
   */
  total: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
}, "strict">;

/**
 * Full validation of shop.schema.v1.EvaluationCoverage. Adds what protovalidate checks on the whole message:
 *   cel[evaluation.ratio]
 *   the rules of total when absent: protojson omits a zero value
 */
export declare const evaluationCoverageZod: z.ZodEffects<typeof evaluationCoverageZodObject>;

export {};
