// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

import type { DescFile, DescMessage } from "@bufbuild/protobuf";

/** What a refinement needs from Zod's context. A method, so both majors fit. */
type RefinementContext = {
  addIssue(issue: {
    code: "custom";
    message: string;
    path?: (string | number)[];
    params?: { ruleId?: string };
  }): void;
};

type Refinement = (value: unknown, ctx: RefinementContext) => void;

/**
 * register adds a file's types, and its dependencies', to the registry fromJson
 * decodes a google.protobuf.Any with. Each generated module calls it once for
 * its own file.
 */
export declare function register(file: DescFile): void;

/**
 * field checks one field on its own: the message is built with only that field
 * set, and only the violations on the field itself, its list items or its map
 * entries are kept. `name` is the proto field name; `native` lists the rule
 * paths ("string.min_len") the Zod schema already checks.
 */
export declare function field(desc: DescMessage, name: string, native?: readonly string[]): Refinement;

/**
 * message checks what spans the whole message: message CEL, oneofs, and the
 * zero value of every absent field, which protojson omits but protovalidate
 * still validates. Present fields are left to their own schema, unless a rule
 * elsewhere kept field() from evaluating them.
 */
export declare function message(desc: DescMessage): Refinement;

// Without it, a declaration file exports every top-level declaration.
export {};
