// Code generated by protoc-gen-strict-schema. DO NOT EDIT.

import type { JsonValue } from "@bufbuild/protobuf";
import { z } from "zod/v3";

// The well-known types, in the canonical protojson form protobuf-es's toJson
// emits and its *Json types describe.

export declare const timestampZod: z.ZodString;
export declare const durationZod: z.ZodString;
export declare const fieldMaskZod: z.ZodString;

// Zod 3 has no z.json(): the schema refers to itself, so its type is declared.
export declare const valueZod: z.ZodType<JsonValue>;
export declare const structZod: z.ZodRecord<z.ZodString, z.ZodType<JsonValue>>;
export declare const listValueZod: z.ZodArray<z.ZodType<JsonValue>>;
export declare const nullValueZod: z.ZodNull;

// An empty Any is written as {}, so "@type" is optional.
export declare const anyZod: z.ZodObject<{ "@type": z.ZodOptional<z.ZodString> }, "passthrough">;
export declare const emptyZod: z.ZodObject<{}, "strict">;

export declare const boolValueZod: z.ZodBoolean;
export declare const bytesValueZod: z.ZodString;
export declare const doubleValueZod: z.ZodUnion<[z.ZodNumber, z.ZodEnum<["NaN", "Infinity", "-Infinity"]>]>;
export declare const floatValueZod: typeof doubleValueZod;
export declare const int32ValueZod: z.ZodNumber;
export declare const int64ValueZod: z.ZodString;
export declare const stringValueZod: z.ZodString;
export declare const uInt32ValueZod: z.ZodNumber;
export declare const uInt64ValueZod: z.ZodString;
