# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/inventory/v1/warehouse.proto
"""buf.validate rules for shop/inventory/v1/warehouse.proto.

One typing.Annotated alias per constrained field, over the type
protoc-gen-python already declared. The message classes stay in
shop.inventory.v1.warehouse_pb2; import them from there.

A rule with an annotated_types equivalent is carried as that constructor,
which pydantic, msgspec and beartype enforce. The rest are metadata strings,
left to protovalidate at runtime.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated

from annotated_types import Ge, Le, MaxLen, MinLen

from google.protobuf import duration_pb2 as _google_protobuf_duration_pb2
from google.protobuf import timestamp_pb2 as _google_protobuf_timestamp_pb2
from shop.inventory.v1.warehouse_pb2 import ContactPoint, OpeningHours, StockMovementKind, Warehouse

# StockMovementKind classifies a change in stock level.
# Without STOCK_MOVEMENT_KIND_UNSPECIFIED, the member protobuf numbers 0, which this overlay
# reads as "unset" rather than a value. No buf.validate rule says so; the
# convention that names it <ENUM>_UNSPECIFIED does.
StockMovementKindStrict = Annotated[
    StockMovementKind,
    Ge(1),
]

# Warehouse is a physical stocking location.
WarehouseId = Annotated[
    str,
    "string.uuid = true",
]
WarehouseName = Annotated[
    str,
    MaxLen(120),
    MinLen(1),
]
WarehouseAddress = Annotated[
    Warehouse.Address,
    "required",
]
WarehouseMaxDwellTime = Annotated[
    _google_protobuf_duration_pb2.Duration,
    "duration.gte.seconds = 3600",
    "duration.lte.seconds = 2592000",
]
WarehouseOpeningHours = Annotated[
    Mapping[str, OpeningHours],
    "map.keys.string.in = [mon, tue, wed, thu, fri, sat, sun]",
    MaxLen(7),
]
WarehouseContacts = Annotated[
    Sequence[ContactPoint],
    MinLen(1),
]

# Address is nested to check that nested messages are walked.
WarehouseAddressLine1 = Annotated[
    str,
    MinLen(1),
]
WarehouseAddressLine2 = Annotated[
    str,
    MaxLen(120),
]
WarehouseAddressCity = Annotated[
    str,
    MinLen(1),
]
WarehouseAddressCountryCode = Annotated[
    str,
    MinLen(2),
    MaxLen(2),
    "string.pattern = ^[A-Z]{2}$",
]
WarehouseAddressPostalCode = Annotated[
    str,
    MaxLen(12),
    MinLen(3),
]

# OpeningHours is a daily window expressed in minutes past midnight.
# cel[opening_hours.ordered]: this.closes_at_minute > this.opens_at_minute
#   message: closes_at_minute must be after opens_at_minute
#   refs: closes_at_minute, opens_at_minute, this
#   calls: _>_
OpeningHoursOpensAtMinute = Annotated[
    int,
    Le(1439),
]
OpeningHoursClosesAtMinute = Annotated[
    int,
    Le(1440),
]

# ContactPoint reaches a person by exactly one channel.
# required oneof channel: exactly one of email, phone, extension
ContactPointName = Annotated[
    str,
    MinLen(1),
]
ContactPointEmail = Annotated[
    str,
    "string.email = true",
]
ContactPointPhone = Annotated[
    str,
    "string.pattern = ^\\+[1-9][0-9]{7,14}$",
]
ContactPointExtension = Annotated[
    int,
    Ge(100),
    Le(9999),
]

# StockMovement records one change to the stock level of a product.
# oneof: exactly one of purchase_order_id, customer_order_id
# cel[stock_movement.quantity_sign]: (this.kind == 2 && this.quantity_delta < 0) || (this.kind == 1 && this.quantity_delta > 0) || this.kind == 3
#   message: outbound movements require a negative quantity, inbound a positive one
#   refs: kind, quantity_delta, this
#   calls: _&&_, _<_, _==_, _>_, _||_
StockMovementId = Annotated[
    str,
    "string.uuid = true",
]
StockMovementWarehouseId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
StockMovementProductId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
StockMovementKind_ = Annotated[
    StockMovementKindStrict,
    "enum.defined_only = true",
    "enum.not_in = [0]",
]
StockMovementQuantityDelta = Annotated[
    int,
    Ge(-100000),
    Le(100000),
]
StockMovementOccurredAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "required",
    "timestamp.lt_now = true",
]
StockMovementPurchaseOrderId = Annotated[
    str,
    MaxLen(64),
]
StockMovementCustomerOrderId = Annotated[
    str,
    MaxLen(64),
]

# StockLevel is the current quantity of a product in a warehouse.
# cel[stock_level.reserved_within_on_hand]: this.reserved <= this.on_hand
#   message: reserved must not exceed on_hand
#   refs: on_hand, reserved, this
#   calls: _<=_
StockLevelProductId = Annotated[
    str,
    "string.uuid = true",
]
StockLevelOnHand = Annotated[
    int,
    Le(100000000),
]
StockLevelReserved = Annotated[
    int,
    Le(100000000),
]
StockLevelCountedAt = Annotated[
    _google_protobuf_timestamp_pb2.Timestamp,
    "timestamp.within.seconds = 7776000",
]
StockLevelReorderThreshold = Annotated[
    int,
    "cel[this <= 10000]: this <= 10000",
    "  refs: this",
    "  calls: _<=_",
]

