# Code generated by protoc-gen-strict. DO NOT EDIT.
# source: shop/inventory/v1/warehouse.proto
"""buf.validate rules for shop/inventory/v1/warehouse.proto.

Types come from shop.inventory.v1.warehouse_pb2 and are re-exported here, so one
import gives a caller both the message class and its annotated field types.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated

from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from shop.inventory.v1.warehouse_pb2 import (
    ContactPoint as ContactPoint,
    OpeningHours as OpeningHours,
    StockLevel as StockLevel,
    StockMovement as StockMovement,
    StockMovementKind as StockMovementKind,
    Warehouse as Warehouse,
)

# Warehouse is a physical stocking location.
WarehouseId = Annotated[
    str,
    "string.uuid = true",
]
WarehouseName = Annotated[
    str,
    "string.max_len = 120",
    "string.min_len = 1",
]
WarehouseAddress = Annotated[
    Warehouse.Address,
    "required",
]
WarehouseMaxDwellTime = Annotated[
    _duration_pb2.Duration,
    "duration.gte.seconds = 3600",
    "duration.lte.seconds = 2592000",
]
WarehouseOpeningHours = Annotated[
    Mapping[str, OpeningHours],
    "map.keys.string.in = [mon, tue, wed, thu, fri, sat, sun]",
    "map.max_pairs = 7",
]
WarehouseContacts = Annotated[
    Sequence[ContactPoint],
    "repeated.min_items = 1",
]

# Address is nested to check that nested messages are walked.
WarehouseAddressLine1 = Annotated[
    str,
    "string.min_len = 1",
]
WarehouseAddressLine2 = Annotated[
    str,
    "string.max_len = 120",
]
WarehouseAddressCity = Annotated[
    str,
    "string.min_len = 1",
]
WarehouseAddressCountryCode = Annotated[
    str,
    "string.len = 2",
    "string.pattern = ^[A-Z]{2}$",
]
WarehouseAddressPostalCode = Annotated[
    str,
    "string.max_len = 12",
    "string.min_len = 3",
]

# OpeningHours is a daily window expressed in minutes past midnight.
# cel[opening_hours.ordered]: this.closes_at_minute > this.opens_at_minute
#   message: closes_at_minute must be after opens_at_minute
#   refs: closes_at_minute, opens_at_minute, this
#   calls: _>_
OpeningHoursOpensAtMinute = Annotated[
    int,
    "uint32.lte = 1439",
]
OpeningHoursClosesAtMinute = Annotated[
    int,
    "uint32.lte = 1440",
]

# ContactPoint reaches a person by exactly one channel.
# required oneof channel: exactly one of email, phone, extension
ContactPointName = Annotated[
    str,
    "string.min_len = 1",
]
ContactPointEmail = Annotated[
    str,
    "string.email = true",
]
ContactPointPhone = Annotated[
    str,
    "string.pattern = ^\\+[1-9][0-9]{7,14}$",
]
ContactPointExtension = Annotated[
    int,
    "uint32.gte = 100",
    "uint32.lte = 9999",
]

# StockMovement records one change to the stock level of a product.
# oneof: exactly one of purchase_order_id, customer_order_id
# cel[stock_movement.quantity_sign]: (this.kind == 2 && this.quantity_delta < 0) || (this.kind == 1 && this.quantity_delta > 0) || this.kind == 3
#   message: outbound movements require a negative quantity, inbound a positive one
#   refs: kind, quantity_delta, this
#   calls: _&&_, _<_, _==_, _>_, _||_
StockMovementId = Annotated[
    str,
    "string.uuid = true",
]
StockMovementWarehouseId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
StockMovementProductId = Annotated[
    str,
    "required",
    "string.uuid = true",
]
StockMovementKind = Annotated[
    StockMovementKind,
    "enum.defined_only = true",
    "enum.not_in = [0]",
]
StockMovementQuantityDelta = Annotated[
    int,
    "sint32.gte = -100000",
    "sint32.lte = 100000",
]
StockMovementOccurredAt = Annotated[
    _timestamp_pb2.Timestamp,
    "required",
    "timestamp.lt_now = true",
]
StockMovementPurchaseOrderId = Annotated[
    str,
    "string.max_len = 64",
]
StockMovementCustomerOrderId = Annotated[
    str,
    "string.max_len = 64",
]

# StockLevel is the current quantity of a product in a warehouse.
# cel[stock_level.reserved_within_on_hand]: this.reserved <= this.on_hand
#   message: reserved must not exceed on_hand
#   refs: on_hand, reserved, this
#   calls: _<=_
StockLevelProductId = Annotated[
    str,
    "string.uuid = true",
]
StockLevelOnHand = Annotated[
    int,
    "uint64.lte = 100000000",
]
StockLevelReserved = Annotated[
    int,
    "uint64.lte = 100000000",
]
StockLevelCountedAt = Annotated[
    _timestamp_pb2.Timestamp,
    "timestamp.within.seconds = 7776000",
]
StockLevelReorderThreshold = Annotated[
    int,
    "cel[this <= 10000]: this <= 10000",
    "  refs: this",
    "  calls: _<=_",
]

