// Code generated by protoc-gen-strict. DO NOT EDIT.
// source: shop/inventory/v1/warehouse.proto

import type { Narrow, NonEmptyList, Require, Uuid } from "../../../strict/types";
import type { ContactPoint, OpeningHours, StockLevel, StockMovement, StockMovementKind, Warehouse, Warehouse_Address } from "./warehouse_pb";
import { ContactPointSchema, StockLevelSchema, StockMovementSchema, WarehouseSchema } from "./warehouse_pb";
import type { MoneyStrict } from "../../common/v1/common.strict";
import type { GenMessage } from "@bufbuild/protobuf/codegenv2";

/**
 * StockMovementKind classifies a change in stock level.
 *
 * Without STOCK_MOVEMENT_KIND_UNSPECIFIED, the member protobuf numbers 0, which this overlay
 * reads as "unset" rather than a value. No buf.validate rule says so; the
 * convention that names it <ENUM>_UNSPECIFIED does.
 */
export type StockMovementKindStrict = Exclude<StockMovementKind, 0>;

/**
 * Warehouse is a physical stocking location.
 *
 * Left to runtime validation, having no type equivalent:
 *   name
 *     string.max_len = 120
 *     string.min_len = 1
 *   max_dwell_time
 *     duration.gte.seconds = 3600
 *     duration.lte.seconds = 2592000
 *   opening_hours
 *     map.keys.string.in = [mon, tue, wed, thu, fri, sat, sun]
 *     map.max_pairs = 7
 */
export type WarehouseStrict = Require<Narrow<Warehouse, {
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  id: Uuid;
  /**
   * required
   *
   * Carried into the type: required.
   */
  address: NonNullable<Warehouse["address"]>;
  /**
   * repeated.min_items = 1
   *
   * Carried into the type: repeated.min_items.
   */
  contacts: NonEmptyList<ContactPointStrict[]>;
}>, "address">;

/**
 * Address is nested to check that nested messages are walked.
 *
 * Left to runtime validation, having no type equivalent:
 *   line1
 *     string.min_len = 1
 *   line2
 *     string.max_len = 120
 *   city
 *     string.min_len = 1
 *   country_code
 *     string.len = 2
 *     string.pattern = ^[A-Z]{2}$
 *   postal_code
 *     string.max_len = 12
 *     string.min_len = 3
 */
export type Warehouse_AddressStrict = Warehouse_Address;

/**
 * OpeningHours is a daily window expressed in minutes past midnight.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[opening_hours.ordered]
 *     this.closes_at_minute > this.opens_at_minute
 *     message: closes_at_minute must be after opens_at_minute
 *   opens_at_minute
 *     uint32.lte = 1439
 *   closes_at_minute
 *     uint32.lte = 1440
 */
export type OpeningHoursStrict = OpeningHours;

/**
 * ContactPoint reaches a person by exactly one channel.
 *
 * Left to runtime validation, having no type equivalent:
 *   name
 *     string.min_len = 1
 */
export type ContactPointStrict = Narrow<ContactPoint, {
  /**
   * required oneof channel: exactly one of email, phone, extension
   * email: string.email = true
   * phone: string.pattern = ^\+[1-9][0-9]{7,14}$
   * extension: uint32.gte = 100
   * extension: uint32.lte = 9999
   */
  channel: Exclude<ContactPoint["channel"], { case: undefined }>;
}>;

/**
 * StockMovement records one change to the stock level of a product.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[stock_movement.quantity_sign]
 *     this.kind == 2 && this.quantity_delta < 0 || this.kind == 1 && this.quantity_delta > 0 ||
 * this.kind == 3
 *     message: outbound movements require a negative quantity, inbound a positive one
 *   quantity_delta
 *     sint32.gte = -100000
 *     sint32.lte = 100000
 *   purchase_order_id
 *     string.max_len = 64
 *   customer_order_id
 *     string.max_len = 64
 *   oneof
 *     oneof: exactly one of purchase_order_id, customer_order_id
 */
export type StockMovementStrict = Require<Narrow<StockMovement, {
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  id: Uuid;
  /**
   * required
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  warehouseId: Uuid;
  /**
   * required
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  productId: Uuid;
  /**
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried into the type: enum.not_in.
   */
  kind: StockMovementKindStrict;
  /**
   * required
   * timestamp.lt_now = true
   *
   * Carried into the type: required.
   */
  occurredAt: NonNullable<StockMovement["occurredAt"]>;
  unitCost: MoneyStrict;
}>, "occurredAt">;

/**
 * StockLevel is the current quantity of a product in a warehouse.
 *
 * Left to runtime validation, having no type equivalent:
 *   cel[stock_level.reserved_within_on_hand]
 *     this.reserved <= this.on_hand
 *     message: reserved must not exceed on_hand
 *   on_hand
 *     uint64.lte = 100000000
 *   reserved
 *     uint64.lte = 100000000
 *   counted_at
 *     timestamp.within.seconds = 7776000
 *   reorder_threshold
 *     cel[this <= 10000]: this <= 10000
 *       refs: this
 *       calls: _<=_
 */
export type StockLevelStrict = Narrow<StockLevel, {
  /**
   * string.uuid = true
   *
   * Carried into the type: string.uuid.
   */
  productId: Uuid;
}>;

/**
 * Describes shop.inventory.v1.Warehouse, reporting WarehouseStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const WarehouseStrictSchema =
  WarehouseSchema as GenMessage<Warehouse, { validType: WarehouseStrict }>;

/**
 * Describes shop.inventory.v1.ContactPoint, reporting ContactPointStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const ContactPointStrictSchema =
  ContactPointSchema as GenMessage<ContactPoint, { validType: ContactPointStrict }>;

/**
 * Describes shop.inventory.v1.StockMovement, reporting StockMovementStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const StockMovementStrictSchema =
  StockMovementSchema as GenMessage<StockMovement, { validType: StockMovementStrict }>;

/**
 * Describes shop.inventory.v1.StockLevel, reporting StockLevelStrict as its valid type.
 * The same descriptor protoc-gen-es generated, so the wire format and the identity
 * this has as a query key are unchanged — only what `MessageValidType` reports differs.
 */
export const StockLevelStrictSchema =
  StockLevelSchema as GenMessage<StockLevel, { validType: StockLevelStrict }>;

