// Package oapigen writes openapi_config.yaml: the buf.validate rules as
// grpc-gateway OpenAPI field options, one file for the whole run.
package oapigen

import (
	"slices"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/generator/emit"
	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// openAPIConfigFile is the whole OpenAPI output: one file for the run. Its keys
// are fully qualified proto names, so there is nothing per-directory to shard —
// which is why the plugin entry needs `strategy: all`.
const openAPIConfigFile = "openapi_config.yaml"

// WriteConfig writes the grpc-gateway OpenAPI configuration that carries
// the buf.validate rules into protoc-gen-openapiv2's output.
//
// protoc-gen-openapiv2 reads no protovalidate rule, so every constraint is
// missing from the swagger it generates. It does accept an external
// configuration — `openapi_configuration=<file>` — whose `field` entries attach
// a JSONSchema to a field by fully qualified name. That is the whole
// integration: the .proto files stay free of OpenAPI annotations and the
// generated JSON is never patched.
//
// The config has to exist before protoc-gen-openapiv2 runs, so the two are
// separate `buf generate` passes; see the Makefile.
func WriteConfig(gen *protogen.Plugin, messages []parser.MessageMetadata) {
	type entry struct {
		field    string // fully qualified, e.g. "shop.catalog.v1.Product.sku"
		keywords []keyword
	}

	var entries []entry
	for _, msg := range messages {
		for _, field := range msg.Fields {
			keywords := fieldKeywords(field)
			if len(keywords) == 0 {
				continue
			}
			entries = append(entries, entry{msg.Name + "." + field.Name, keywords})
		}
	}

	g := gen.NewGeneratedFile(openAPIConfigFile, "")
	g.P("# Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("# buf.validate rules, as grpc-gateway OpenAPI field options.")
	g.P("# Pass it to protoc-gen-openapiv2 as openapi_configuration=<this file>.")
	g.P("openapiOptions:")
	if len(entries) == 0 {
		return
	}
	g.P("  field:")
	for _, e := range entries {
		g.P("    - field: ", e.field)
		g.P("      option:")
		for _, kw := range e.keywords {
			g.P("        ", kw.key, ": ", kw.value)
		}
	}
}

// fieldKeywords renders every rule on a field that has a JSONSchema equivalent.
//
// The order follows FieldMetadata.Rules, which the parser sorts by rule name,
// so two runs on the same proto emit the same bytes. A keyword two rules both
// claim — `string.len` alongside `string.min_len` — keeps the first: the proto
// contradicts itself, and a duplicate YAML key would fail to parse at all.
func fieldKeywords(field parser.FieldMetadata) []keyword {
	// `ignore` means the rules do not always apply, so none of them describes
	// the schema either — the same call fieldNarrowing makes for TypeScript.
	if _, ok := emit.RuleValue(field, emit.IgnoreRule); ok {
		return nil
	}
	// `repeated.items.ignore` says the same of the element rules, which
	// grpc-gateway puts on the array's `items`. The two are independent: a list
	// whose elements are ignored still has its own min_items.
	_, itemsIgnored := emit.RuleValue(field, emit.RepeatedItems+emit.IgnoreRule)

	reversed := emit.ReversedBounds(field.Rules)

	// `required` is absent on purpose. grpc-gateway hoists it into the parent
	// message's required list, which is right for a body schema — but the same
	// list also marks the flattened query parameter of a GET required, and a
	// field of an optional sub-message is not. Over-narrowing a request is worse
	// than leaving the rule to runtime validation.
	var out []keyword
	for _, rule := range field.Rules {
		if itemsIgnored && strings.HasPrefix(rule.Kind, emit.RepeatedItems) {
			continue
		}
		if reversed[rule.Kind] {
			continue
		}
		for _, kw := range ruleKeywords(rule) {
			if slices.ContainsFunc(out, func(seen keyword) bool { return seen.key == kw.key }) {
				continue
			}
			out = append(out, kw)
		}
	}
	return out
}
