// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/catalog/v1/product.proto

import createProductRequestBundle from "../../../jsonschema/shop.catalog.v1.CreateProductRequest.jsonschema.bundle.json" with { type: "json" };
import createProductResponseBundle from "../../../jsonschema/shop.catalog.v1.CreateProductResponse.jsonschema.bundle.json" with { type: "json" };
import deleteProductRequestBundle from "../../../jsonschema/shop.catalog.v1.DeleteProductRequest.jsonschema.bundle.json" with { type: "json" };
import deleteProductResponseBundle from "../../../jsonschema/shop.catalog.v1.DeleteProductResponse.jsonschema.bundle.json" with { type: "json" };
import getProductRequestBundle from "../../../jsonschema/shop.catalog.v1.GetProductRequest.jsonschema.bundle.json" with { type: "json" };
import getProductResponseBundle from "../../../jsonschema/shop.catalog.v1.GetProductResponse.jsonschema.bundle.json" with { type: "json" };
import listProductsRequestBundle from "../../../jsonschema/shop.catalog.v1.ListProductsRequest.jsonschema.bundle.json" with { type: "json" };
import listProductsResponseBundle from "../../../jsonschema/shop.catalog.v1.ListProductsResponse.jsonschema.bundle.json" with { type: "json" };
import productBundle from "../../../jsonschema/shop.catalog.v1.Product.jsonschema.bundle.json" with { type: "json" };
import updateProductRequestBundle from "../../../jsonschema/shop.catalog.v1.UpdateProductRequest.jsonschema.bundle.json" with { type: "json" };
import updateProductResponseBundle from "../../../jsonschema/shop.catalog.v1.UpdateProductResponse.jsonschema.bundle.json" with { type: "json" };
import { loosen } from "../../../strict/jsonschema.js";

/**
 * Product is the catalog resource.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.Product, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[product.discount_below_price]
 *     !has(this.discount_price) || this.discount_price.units < this.price.units
 *     message: discount_price must be lower than price
 *   cel[product.draft_not_published]
 *     this.status != 3 || !has(this.published_at)
 *     message: a draft product cannot have published_at set
 *   sku
 *     string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$
 *   tags
 *     repeated.unique = true
 *     repeated.items.string.pattern = ^[a-z0-9-]+$
 *   labels
 *     map.max_pairs = 16
 *   created_by_email
 *     cel[product.created_by_email]: this.size() == 0 || this.isEmail()
 *       message: if set, created_by_email must be a valid email address
 *       refs: this
 *       calls: _==_, _||_, isEmail, size
 *   version
 *     int64.gte = 0
 *   absent fields
 *     id, sku, name, status, tags, labels, created_by_email, version: an absent key is the zero value, which the rules still apply to
 */
export const productJsonSchema = loosen(productBundle);

/**
 * CreateProductRequest creates a new product.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.CreateProductRequest, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[create_product.no_read_only_fields]
 *     this.product.id == '' && !has(this.product.created_at) && !has(this.product.updated_at) && this.product.version == 0
 *     message: read-only fields (id, created_at, updated_at, version) must not be set
 */
export const createProductRequestJsonSchema = loosen(createProductRequestBundle);

/**
 * CreateProductResponse returns the stored product.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.CreateProductResponse, from protoschema-jsonschema.
 */
export const createProductResponseJsonSchema = loosen(createProductResponseBundle);

/**
 * GetProductRequest looks a product up by id or by SKU.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.GetProductRequest, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   required oneof key: exactly one of id, sku
 */
export const getProductRequestJsonSchema = loosen(getProductRequestBundle);

/**
 * GetProductResponse returns a single product.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.GetProductResponse, from protoschema-jsonschema.
 */
export const getProductResponseJsonSchema = loosen(getProductResponseBundle);

/**
 * ListProductsRequest pages through the catalog.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.ListProductsRequest, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[list_products.price_bounds]
 *     has(this.min_price) == has(this.max_price)
 *     message: min_price and max_price must be set together
 *   absent fields
 *     order_by, order_direction: an absent key is the zero value, which the rules still apply to
 */
export const listProductsRequestJsonSchema = loosen(listProductsRequestBundle);

/**
 * ListProductsResponse is one page of products.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.ListProductsResponse, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   total_size
 *     int64.gte = 0
 *   absent fields
 *     total_size: an absent key is the zero value, which the rules still apply to
 */
export const listProductsResponseJsonSchema = loosen(listProductsResponseBundle);

/**
 * UpdateProductRequest performs a partial update.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.UpdateProductRequest, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[update_product.id_present]
 *     this.product.id != ''
 *     message: product.id is required for an update
 */
export const updateProductRequestJsonSchema = loosen(updateProductRequestBundle);

/**
 * UpdateProductResponse returns the stored product.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.UpdateProductResponse, from protoschema-jsonschema.
 */
export const updateProductResponseJsonSchema = loosen(updateProductResponseBundle);

/**
 * DeleteProductRequest removes a product.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.DeleteProductRequest, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   expected_version
 *     int64.gte = 0
 */
export const deleteProductRequestJsonSchema = loosen(deleteProductRequestBundle);

/**
 * DeleteProductResponse is intentionally empty.
 *
 * JSON Schema 2020-12 for shop.catalog.v1.DeleteProductResponse, from protoschema-jsonschema.
 */
export const deleteProductResponseJsonSchema = loosen(deleteProductResponseBundle);
