// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/catalog/v1/product.proto

import { z } from "zod";
import { field, message, register } from "../../../strict/protovalidate.js";
import { fieldMaskZod, timestampZod } from "../../../strict/wkt.zod.js";
import { moneyZod, paginationZod } from "../../common/v1/common.zod.js";
import { CreateProductRequestSchema, DeleteProductRequestSchema, GetProductRequestSchema, ListProductsRequestSchema, ListProductsResponseSchema, ProductSchema, UpdateProductRequestSchema, file_shop_catalog_v1_product } from "./product_pb.js";

register(file_shop_catalog_v1_product);

/**
 * ProductStatus is the lifecycle state of a product.
 *
 * shop.catalog.v1.ProductStatus, as protojson writes it: the member's name.
 */
export const productStatusZod = z.enum(["PRODUCT_STATUS_UNSPECIFIED", "PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"]);

/**
 * Product is the catalog resource.
 *
 * The composable schema of shop.catalog.v1.Product: every field carries its own rules, so
 * `productZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in productZod.
 */
export const productZodObject = z.strictObject({
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * string.max_len = 32
   * string.min_len = 3
   * string.pattern = ^[A-Z0-9]+(-[A-Z0-9]+)*$
   *
   * Carried by Zod: string.max_len, string.min_len.
   * Checked by protovalidate: string.pattern.
   */
  sku: z.string().max(32).min(3).superRefine(field(ProductSchema, "sku", ["string.max_len", "string.min_len"])).optional(),
  /**
   * string.max_len = 200
   * string.min_len = 1
   *
   * Carried by Zod: string.max_len, string.min_len.
   */
  name: z.string().max(200).min(1).optional(),
  /**
   * string.max_len = 4096
   *
   * Carried by Zod: string.max_len.
   */
  description: z.string().max(4096).optional(),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  price: moneyZod,
  discountPrice: moneyZod.optional(),
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  status: z.enum(["PRODUCT_STATUS_UNSPECIFIED", "PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"]).optional(),
  /**
   * repeated.items.string.max_len = 40
   * repeated.items.string.min_len = 1
   * repeated.items.string.pattern = ^[a-z0-9-]+$
   * repeated.max_items = 20
   * repeated.unique = true
   *
   * Carried by Zod: repeated.items.string.max_len, repeated.items.string.min_len, repeated.max_items.
   * Checked by protovalidate: repeated.items.string.pattern, repeated.unique.
   */
  tags: z.array(z.string().max(40).min(1)).max(20).superRefine(field(ProductSchema, "tags", ["repeated.items.string.max_len", "repeated.items.string.min_len", "repeated.max_items"])).optional(),
  /**
   * map.max_pairs = 16
   *
   * Checked by protovalidate: map.max_pairs.
   */
  labels: z.record(z.string(), z.string()).superRefine(field(ProductSchema, "labels")).optional(),
  /**
   * cel[product.created_by_email]: this.size() == 0 || this.isEmail()
   *   message: if set, created_by_email must be a valid email address
   *   refs: this
   *   calls: _==_, _||_, isEmail, size
   *
   * Checked by protovalidate: cel[product.created_by_email].
   */
  createdByEmail: z.string().superRefine(field(ProductSchema, "created_by_email")).optional(),
  createdAt: timestampZod.optional(),
  updatedAt: timestampZod.optional(),
  publishedAt: timestampZod.optional(),
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  version: z.string().regex(/^-?[0-9]+$/).superRefine(field(ProductSchema, "version")).optional(),
});

/**
 * Full validation of shop.catalog.v1.Product. Adds what protovalidate checks on the whole message:
 *   cel[product.discount_below_price]
 *   cel[product.draft_not_published]
 *   the rules of id, sku, name, status, tags, labels, created_by_email, version when absent: protojson omits a zero value
 */
export const productZod = productZodObject.superRefine(message(ProductSchema));

/**
 * CreateProductRequest creates a new product.
 *
 * The composable schema of shop.catalog.v1.CreateProductRequest: every field carries its own rules, so
 * `createProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in createProductRequestZod.
 */
export const createProductRequestZodObject = z.strictObject({
  /**
   * required
   *
   * Carried by Zod: required.
   */
  product: productZod,
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  idempotencyKey: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
});

/**
 * Full validation of shop.catalog.v1.CreateProductRequest. Adds what protovalidate checks on the whole message:
 *   cel[create_product.no_read_only_fields]
 */
export const createProductRequestZod = createProductRequestZodObject.superRefine(message(CreateProductRequestSchema));

/**
 * CreateProductResponse returns the stored product.
 *
 * The composable schema of shop.catalog.v1.CreateProductResponse: every field carries its own rules, so
 * `createProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in createProductResponseZod.
 */
export const createProductResponseZodObject = z.strictObject({
  product: productZod.optional(),
});

/** Full validation of shop.catalog.v1.CreateProductResponse: the message has no rule beyond its fields'. */
export const createProductResponseZod = createProductResponseZodObject;

/**
 * GetProductRequest looks a product up by id or by SKU.
 *
 * The composable schema of shop.catalog.v1.GetProductRequest: every field carries its own rules, so
 * `getProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in getProductRequestZod.
 */
export const getProductRequestZodObject = z.strictObject({
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * string.min_len = 3
   *
   * Carried by Zod: string.min_len.
   */
  sku: z.string().min(3).optional(),
});

/**
 * Full validation of shop.catalog.v1.GetProductRequest. Adds what protovalidate checks on the whole message:
 *   required oneof key: exactly one of id, sku
 */
export const getProductRequestZod = getProductRequestZodObject.superRefine(message(GetProductRequestSchema));

/**
 * GetProductResponse returns a single product.
 *
 * The composable schema of shop.catalog.v1.GetProductResponse: every field carries its own rules, so
 * `getProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in getProductResponseZod.
 */
export const getProductResponseZodObject = z.strictObject({
  product: productZod.optional(),
});

/** Full validation of shop.catalog.v1.GetProductResponse: the message has no rule beyond its fields'. */
export const getProductResponseZod = getProductResponseZodObject;

/**
 * ListProductsRequest pages through the catalog.
 *
 * The composable schema of shop.catalog.v1.ListProductsRequest: every field carries its own rules, so
 * `listProductsRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in listProductsRequestZod.
 */
export const listProductsRequestZodObject = z.strictObject({
  /**
   * required
   *
   * Carried by Zod: required.
   */
  pagination: paginationZod,
  /**
   * repeated.items.enum.defined_only = true
   * repeated.items.enum.not_in = [0]
   *
   * Carried by Zod: repeated.items.enum.defined_only, repeated.items.enum.not_in.
   */
  statuses: z.array(z.enum(["PRODUCT_STATUS_ACTIVE", "PRODUCT_STATUS_ARCHIVED", "PRODUCT_STATUS_DRAFT"])).optional(),
  /**
   * string.max_len = 200
   * string.min_len = 1
   *
   * Carried by Zod: string.max_len, string.min_len.
   */
  nameContains: z.string().max(200).min(1).optional(),
  minPrice: moneyZod.optional(),
  maxPrice: moneyZod.optional(),
  /**
   * string.in = [, name, sku, created_at, price]
   *
   * Carried by Zod: string.in.
   */
  orderBy: z.enum(["", "name", "sku", "created_at", "price"]).optional(),
  /**
   * enum.defined_only = true
   *
   * Carried by Zod: enum.defined_only.
   */
  orderDirection: z.enum(["SORT_DIRECTION_UNSPECIFIED", "SORT_DIRECTION_ASC", "SORT_DIRECTION_DESC"]).optional(),
});

/**
 * Full validation of shop.catalog.v1.ListProductsRequest. Adds what protovalidate checks on the whole message:
 *   cel[list_products.price_bounds]
 *   the rules of order_by, order_direction when absent: protojson omits a zero value
 */
export const listProductsRequestZod = listProductsRequestZodObject.superRefine(message(ListProductsRequestSchema));

/**
 * ListProductsResponse is one page of products.
 *
 * The composable schema of shop.catalog.v1.ListProductsResponse: every field carries its own rules, so
 * `listProductsResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in listProductsResponseZod.
 */
export const listProductsResponseZodObject = z.strictObject({
  products: z.array(productZod).optional(),
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  totalSize: z.string().regex(/^-?[0-9]+$/).superRefine(field(ListProductsResponseSchema, "total_size")).optional(),
  nextPageToken: z.string().optional(),
});

/**
 * Full validation of shop.catalog.v1.ListProductsResponse. Adds what protovalidate checks on the whole message:
 *   the rules of total_size when absent: protojson omits a zero value
 */
export const listProductsResponseZod = listProductsResponseZodObject.superRefine(message(ListProductsResponseSchema));

/**
 * UpdateProductRequest performs a partial update.
 *
 * The composable schema of shop.catalog.v1.UpdateProductRequest: every field carries its own rules, so
 * `updateProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in updateProductRequestZod.
 */
export const updateProductRequestZodObject = z.strictObject({
  /**
   * required
   *
   * Carried by Zod: required.
   */
  product: productZod,
  updateMask: fieldMaskZod.optional(),
});

/**
 * Full validation of shop.catalog.v1.UpdateProductRequest. Adds what protovalidate checks on the whole message:
 *   cel[update_product.id_present]
 */
export const updateProductRequestZod = updateProductRequestZodObject.superRefine(message(UpdateProductRequestSchema));

/**
 * UpdateProductResponse returns the stored product.
 *
 * The composable schema of shop.catalog.v1.UpdateProductResponse: every field carries its own rules, so
 * `updateProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in updateProductResponseZod.
 */
export const updateProductResponseZodObject = z.strictObject({
  product: productZod.optional(),
});

/** Full validation of shop.catalog.v1.UpdateProductResponse: the message has no rule beyond its fields'. */
export const updateProductResponseZod = updateProductResponseZodObject;

/**
 * DeleteProductRequest removes a product.
 *
 * The composable schema of shop.catalog.v1.DeleteProductRequest: every field carries its own rules, so
 * `deleteProductRequestZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in deleteProductRequestZod.
 */
export const deleteProductRequestZodObject = z.strictObject({
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  id: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).min(1),
  /**
   * int64.gte = 0
   *
   * Checked by protovalidate: int64.gte.
   */
  expectedVersion: z.string().regex(/^-?[0-9]+$/).superRefine(field(DeleteProductRequestSchema, "expected_version")).optional(),
});

/** Full validation of shop.catalog.v1.DeleteProductRequest: the message has no rule beyond its fields'. */
export const deleteProductRequestZod = deleteProductRequestZodObject;

/**
 * DeleteProductResponse is intentionally empty.
 *
 * The composable schema of shop.catalog.v1.DeleteProductResponse: every field carries its own rules, so
 * `deleteProductResponseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in deleteProductResponseZod.
 */
export const deleteProductResponseZodObject = z.strictObject({
});

/** Full validation of shop.catalog.v1.DeleteProductResponse: the message has no rule beyond its fields'. */
export const deleteProductResponseZod = deleteProductResponseZodObject;
