// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/schema/v1/schema.proto

import bytesCoverageBundle from "../../../jsonschema/shop.schema.v1.BytesCoverage.jsonschema.bundle.json" with { type: "json" };
import collectionCoverageBundle from "../../../jsonschema/shop.schema.v1.CollectionCoverage.jsonschema.bundle.json" with { type: "json" };
import enumCoverageBundle from "../../../jsonschema/shop.schema.v1.EnumCoverage.jsonschema.bundle.json" with { type: "json" };
import evaluationCoverageBundle from "../../../jsonschema/shop.schema.v1.EvaluationCoverage.jsonschema.bundle.json" with { type: "json" };
import formatCoverageBundle from "../../../jsonschema/shop.schema.v1.FormatCoverage.jsonschema.bundle.json" with { type: "json" };
import ignoreCoverageBundle from "../../../jsonschema/shop.schema.v1.IgnoreCoverage.jsonschema.bundle.json" with { type: "json" };
import implicitCoverageBundle from "../../../jsonschema/shop.schema.v1.ImplicitCoverage.jsonschema.bundle.json" with { type: "json" };
import itemBundle from "../../../jsonschema/shop.schema.v1.Item.jsonschema.bundle.json" with { type: "json" };
import jsonNameCoverageBundle from "../../../jsonschema/shop.schema.v1.JsonNameCoverage.jsonschema.bundle.json" with { type: "json" };
import messageCelCoverageBundle from "../../../jsonschema/shop.schema.v1.MessageCelCoverage.jsonschema.bundle.json" with { type: "json" };
import messageOneofCoverageBundle from "../../../jsonschema/shop.schema.v1.MessageOneofCoverage.jsonschema.bundle.json" with { type: "json" };
import numberCoverageBundle from "../../../jsonschema/shop.schema.v1.NumberCoverage.jsonschema.bundle.json" with { type: "json" };
import oneofCoverageBundle from "../../../jsonschema/shop.schema.v1.OneofCoverage.jsonschema.bundle.json" with { type: "json" };
import pingBundle from "../../../jsonschema/shop.schema.v1.Ping.jsonschema.bundle.json" with { type: "json" };
import pongBundle from "../../../jsonschema/shop.schema.v1.Pong.jsonschema.bundle.json" with { type: "json" };
import stringContentCoverageBundle from "../../../jsonschema/shop.schema.v1.StringContentCoverage.jsonschema.bundle.json" with { type: "json" };
import treeNodeBundle from "../../../jsonschema/shop.schema.v1.TreeNode.jsonschema.bundle.json" with { type: "json" };
import wellKnownCoverageBundle from "../../../jsonschema/shop.schema.v1.WellKnownCoverage.jsonschema.bundle.json" with { type: "json" };
import { loosen } from "../../../strict/jsonschema.js";

/**
 * Item is the rule-bearing message other fixtures reference. Its empty instance is valid, so a reference to it tests presence and nesting only.
 *
 * JSON Schema 2020-12 for shop.schema.v1.Item, from protoschema-jsonschema.
 */
export const itemJsonSchema = loosen(itemBundle);

/**
 * FormatCoverage has one field per string well-known format. Every field has explicit presence, so a test can set one at a time.
 *
 * JSON Schema 2020-12 for shop.schema.v1.FormatCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   hostname
 *     string.hostname = true
 *   email
 *     string.email = true
 *   ip
 *     string.ip = true
 *   ipv4
 *     string.ipv4 = true
 *   ipv6
 *     string.ipv6 = true
 *   uri
 *     string.uri = true
 *   uri_ref
 *     string.uri_ref = true
 *   address
 *     string.address = true
 *   host_and_port
 *     string.host_and_port = true
 *   ip_with_prefixlen
 *     string.ip_with_prefixlen = true
 *   ipv4_with_prefixlen
 *     string.ipv4_with_prefixlen = true
 *   ipv6_with_prefixlen
 *     string.ipv6_with_prefixlen = true
 *   ip_prefix
 *     string.ip_prefix = true
 *   ipv4_prefix
 *     string.ipv4_prefix = true
 *   ipv6_prefix
 *     string.ipv6_prefix = true
 *   ulid
 *     string.ulid = true
 *   protobuf_fqn
 *     string.protobuf_fqn = true
 *   protobuf_dot_fqn
 *     string.protobuf_dot_fqn = true
 *   header_name
 *     string.strict = true
 *     string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_NAME
 *   header_value
 *     string.well_known_regex = KNOWN_REGEX_HTTP_HEADER_VALUE
 *   hidden_host
 *     string.hostname = true
 */
export const formatCoverageJsonSchema = loosen(formatCoverageBundle);

/**
 * StringContentCoverage has one field per string length and content rule.
 *
 * JSON Schema 2020-12 for shop.schema.v1.StringContentCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   len_bytes
 *     string.len_bytes = 4
 *   min_bytes
 *     string.min_bytes = 2
 *   max_bytes
 *     string.max_bytes = 8
 *   pattern_inline_flag
 *     string.pattern = (?i)^abc$
 *   pattern_non_space
 *     string.pattern = ^\S+$
 *   prefix
 *     string.prefix = +1
 *   suffix
 *     string.suffix = .io
 *   contains
 *     string.contains = .
 *   prefix_and_suffix
 *     string.prefix = pre
 *     string.suffix = suf
 *   not_contains
 *     string.not_contains =  
 *   not_in_set
 *     string.not_in = [x, y]
 *   code
 *     cel[string_content.code.no_spaces]: !this.contains(' ')
 *       message: code must not contain spaces
 *       refs: this
 *       calls: !_, contains
 *   uuid_pattern
 *     string.pattern = ^[a-f0-9-]+$
 *     string.uuid = true
 *   escaped
 *     string.prefix = "\*\/
 *     cel[string_content.escaped]: !this.endsWith('"*\/')
 *       message: must not end in "*\/"
 *       refs: this
 *       calls: !_, endsWith
 */
export const stringContentCoverageJsonSchema = loosen(stringContentCoverageBundle);

/**
 * ImplicitCoverage has implicit-presence fields whose zero value breaks a rule. protojson omits zero values, so the rule has to fire for an absent key.
 *
 * JSON Schema 2020-12 for shop.schema.v1.ImplicitCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   count
 *     int32.gt = 0
 *   email
 *     string.email = true
 *   required_name
 *     required
 *   required_count
 *     required
 *   required_tags
 *     required
 *   absent fields
 *     short_code, count, tags, email: an absent key is the zero value, which the rules still apply to
 */
export const implicitCoverageJsonSchema = loosen(implicitCoverageBundle);

/**
 * BytesCoverage has one field per bytes rule. JSON carries bytes as base64, standard or URL-safe.
 *
 * JSON Schema 2020-12 for shop.schema.v1.BytesCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   exact_len
 *     bytes.len = 4
 *   min_len
 *     bytes.min_len = 2
 *   max_len
 *     bytes.max_len = 8
 *   pattern
 *     bytes.pattern = ^[a-z]+$
 *   prefix
 *     bytes.prefix = [1 2]
 *   ip
 *     bytes.ip = true
 *   uuid
 *     bytes.uuid = true
 */
export const bytesCoverageJsonSchema = loosen(bytesCoverageBundle);

/**
 * NumberCoverage has one field per numeric rule shape, over every JSON number form: int32-family numbers, int64-family strings, floats with NaN.
 *
 * JSON Schema 2020-12 for shop.schema.v1.NumberCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   bounded
 *     int32.gt = 0
 *     int32.lte = 100
 *   reversed_range
 *     int32.gt = 10
 *     int32.lt = 5
 *   const_value
 *     int32.const = 7
 *   in_set
 *     int32.in = [1, 2, 3]
 *   not_in_set
 *     int32.not_in = [0, -1]
 *   unsigned
 *     uint32.gte = 1
 *     uint32.lt = 65536
 *   zigzag
 *     sint32.gte = -128
 *   fixed
 *     fixed32.lte = 1000
 *   signed_fixed
 *     sfixed32.lt = 0
 *   big
 *     int64.gt = 0
 *   big_unsigned
 *     uint64.lte = 1000000
 *   ratio
 *     float.finite = true
 *   score
 *     double.gt = 0
 *   factor
 *     double.in = [0.5, 1, 2]
 *   capped
 *     float.lte = 0.1
 */
export const numberCoverageJsonSchema = loosen(numberCoverageBundle);

/**
 * CollectionCoverage has one field per repeated and map shape.
 *
 * JSON Schema 2020-12 for shop.schema.v1.CollectionCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   unique
 *     repeated.unique = true
 *   links
 *     repeated.items.string.uri = true
 *   labels
 *     map.max_pairs = 4
 *     map.min_pairs = 1
 *     map.values.string.uri = true
 *   absent fields
 *     bounded, unique, labels: an absent key is the zero value, which the rules still apply to
 */
export const collectionCoverageJsonSchema = loosen(collectionCoverageBundle);

/**
 * IgnoreCoverage has rules that are skipped for the zero value, and a field that is never validated.
 *
 * JSON Schema 2020-12 for shop.schema.v1.IgnoreCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   email
 *     string.email = true
 *   threshold
 *     int32.gt = 5
 *   ids
 *     repeated.items.string.uuid = true
 *   codes
 *     map.values.string.min_len = 3
 */
export const ignoreCoverageJsonSchema = loosen(ignoreCoverageBundle);

/**
 * OneofCoverage has both oneof kinds: real oneofs, flattened into the JSON object, and a message-level oneof rule over plain fields.
 *
 * JSON Schema 2020-12 for shop.schema.v1.OneofCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   required oneof contact: exactly one of email, phone
 *   oneof filter: at most one of query, page
 *   required oneof: exactly one of first_name, last_name
 *   email
 *     string.email = true
 */
export const oneofCoverageJsonSchema = loosen(oneofCoverageBundle);

/**
 * WellKnownCoverage has one field per well-known type the JSON shape maps.
 *
 * JSON Schema 2020-12 for shop.schema.v1.WellKnownCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   timeout
 *     duration.gte.seconds = 1
 *     duration.lte.seconds = 300
 *   expires_at
 *     timestamp.gt_now = true
 *   detail
 *     any.in = [type.googleapis.com/google.protobuf.Duration]
 *   label
 *     string.min_len = 1
 *   absent fields
 *     checked_null: an absent key is the zero value, which the rules still apply to
 */
export const wellKnownCoverageJsonSchema = loosen(wellKnownCoverageBundle);

/**
 * EnumCoverage has one field per enum rule, and a field without rules.
 *
 * JSON Schema 2020-12 for shop.schema.v1.EnumCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   excluded
 *     enum.not_in = [3]
 */
export const enumCoverageJsonSchema = loosen(enumCoverageBundle);

/**
 * JsonNameCoverage has fields whose JSON name differs from the proto name in ways a naive camelCase conversion gets wrong.
 *
 * JSON Schema 2020-12 for shop.schema.v1.JsonNameCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   metric_1st
 *     int32.gte = 0
 *   absent fields
 *     external_id, metric_1st, display_name: an absent key is the zero value, which the rules still apply to
 */
export const jsonNameCoverageJsonSchema = loosen(jsonNameCoverageBundle);

/**
 * TreeNode refers to itself, directly and through a list.
 *
 * JSON Schema 2020-12 for shop.schema.v1.TreeNode, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   absent fields
 *     label: an absent key is the zero value, which the rules still apply to
 */
export const treeNodeJsonSchema = loosen(treeNodeBundle);

/**
 * Ping and Pong refer to each other: a cycle across two messages.
 *
 * JSON Schema 2020-12 for shop.schema.v1.Ping, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   absent fields
 *     note: an absent key is the zero value, which the rules still apply to
 */
export const pingJsonSchema = loosen(pingBundle);

/**
 * Pong is the other half of the Ping cycle.
 *
 * JSON Schema 2020-12 for shop.schema.v1.Pong, from protoschema-jsonschema.
 */
export const pongJsonSchema = loosen(pongBundle);

/**
 * MessageCelCoverage has a message-level CEL rule spanning two fields, and a nested message with a rule of its own.
 *
 * JSON Schema 2020-12 for shop.schema.v1.MessageCelCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[message_cel.low_below_high]
 *     this.low < this.high
 *     message: low must be below high
 *   Window.cel[message_cel.window.ordered]
 *     this.end_minute > this.start_minute
 *     message: end_minute must be after start_minute
 */
export const messageCelCoverageJsonSchema = loosen(messageCelCoverageBundle);

/**
 * MessageOneofCoverage has implicit fields named by a message-level oneof rule. protovalidate gives such a field IGNORE_IF_ZERO_VALUE, so its zero value passes its own rules.
 *
 * JSON Schema 2020-12 for shop.schema.v1.MessageOneofCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   oneof: at most one of code, label, tags, color, alias
 *   code
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     string.min_len = 3
 *   tags
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     repeated.min_items = 2
 *   color
 *     ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
 *     enum.defined_only = true
 */
export const messageOneofCoverageJsonSchema = loosen(messageOneofCoverageBundle);

/**
 * EvaluationCoverage has a message rule that fails to evaluate while divisor is 0, the value divisor holds in the message field() checks total in.
 *
 * JSON Schema 2020-12 for shop.schema.v1.EvaluationCoverage, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[evaluation.ratio]
 *     this.total / this.divisor <= 100
 *     message: total / divisor must be at most 100
 *   total
 *     cel[this % 2 == 0]: this % 2 == 0
 *       refs: this
 *       calls: _%_, _==_
 *   absent fields
 *     total: an absent key is the zero value, which the rules still apply to
 */
export const evaluationCoverageJsonSchema = loosen(evaluationCoverageBundle);
