// Package tsgen writes the TypeScript overlay: one <prefix>.strict.ts per proto
// file, plus the shared strict/types.ts module. Every type it prints is derived
// from what protoc-gen-es declared, never re-declared.
package tsgen

import (
	"maps"
	"slices"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/generator/emit"
	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// outputOnlyFieldsSuffix names the const listing a message's server-assigned
// fields, kept apart from the type so it can be read at runtime.
const outputOnlyFieldsSuffix = "OutputOnlyFields"

// tsProp is one property of the object `Narrow` applies to the generated type.
type tsProp struct {
	key string
	typ string
	doc []string
}

// Write writes a <prefix>.strict.ts overlay on protoc-gen-es output.
//
// Every message becomes `<Name>Strict`: the generated type narrowed by the
// rules a type can express, untouched otherwise. It stays assignable to the
// type it narrows, so anything protobuf-es generated still accepts it.
func Write(gen *protogen.Plugin, file *protogen.File, ctx *Context) {
	f := newTSFile(ctx, file)

	// Every name this file declares is reserved first, so an import of a
	// same-named symbol from another package is the one that gets renamed.
	for _, enum := range ctx.enumsByFile[f.proto] {
		if ctx.strictEnums[enum.Name] {
			f.declare(ctx.strictName(enum.Name))
		}
	}
	for _, msg := range ctx.byFile[f.proto] {
		f.declare(ctx.strictName(msg.Name))
		if ctx.needsStrict[msg.Name] {
			f.declare(ctx.tsName(msg.Name) + "StrictSchema")
		}
		if len(msg.OutputOnlyPaths) > 0 {
			f.declare(ctx.tsName(msg.Name) + outputOnlyFieldsSuffix)
		}
	}
	for _, service := range file.Services {
		f.declare(string(service.Desc.Name()) + "Strict")
		f.declare(string(service.Desc.Name()) + "StrictDescriptor")
	}

	for _, enum := range ctx.enumsByFile[f.proto] {
		if ctx.strictEnums[enum.Name] {
			f.enumType(enum)
		}
	}
	for _, msg := range ctx.byFile[f.proto] {
		f.message(msg)
		f.outputOnlyFields(msg)
	}
	for _, msg := range ctx.byFile[f.proto] {
		if ctx.needsStrict[msg.Name] {
			f.strictSchema(msg)
		}
	}
	for _, service := range file.Services {
		f.service(service)
	}

	g := gen.NewGeneratedFile(f.out, "")
	g.P("// Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("// source: ", f.proto)
	g.P()
	for _, line := range f.importLines() {
		g.P(line)
	}
	g.P()
	for _, line := range f.lines {
		g.P(line)
	}
}

// enumType emits `<Name>Strict`, the generated enum without the member
// protobuf numbers 0. Every field of the enum's type takes this alias, so a
// message never carries the "unset" member — no buf.validate rule says so, the
// convention that names it <ENUM>_UNSPECIFIED does.
func (f *tsFile) enumType(enum parser.EnumMetadata) {
	zero, ok := enum.Zero()
	if !ok {
		return
	}
	name := f.shape(f.ctx.tsName(enum.Name))
	strict := f.declare(f.ctx.strictName(enum.Name))
	var doc []string
	if enum.Comments != "" {
		doc = append(doc, emit.OneLine(enum.Comments), "")
	}
	f.doc("", append(doc,
		"Without "+zero.Name+", the member protobuf numbers 0, which this overlay",
		"reads as \"unset\" rather than a value. No buf.validate rule says so; the",
		"convention that names it <ENUM>_UNSPECIFIED does.",
	))
	f.P("export type ", strict, " = Exclude<", name, ", 0>;")
	f.P()
}

// message emits `<Name>Strict`.
func (f *tsFile) message(msg parser.MessageMetadata) {
	name := f.shape(f.ctx.tsName(msg.Name))
	strict := f.declare(f.ctx.strictName(msg.Name))
	var props []tsProp
	var required, readOnly []string
	var runtimeOnly []emit.RuntimeNote

	tree := f.ctx.celTrees[msg.Name]
	seen := map[string]bool{}
	for _, field := range msg.Fields {
		if field.OneofName != "" {
			if seen[field.OneofName] {
				continue
			}
			seen[field.OneofName] = true
			if prop, ok := f.oneofProp(name, msg, field.OneofName); ok {
				props = append(props, prop)
				continue
			}
			// Nothing narrows the union, but its members still carry rules,
			// and this is the only place the overlay can name them.
			runtimeOnly = append(runtimeOnly, oneofMemberNotes(msg, field.OneofName)...)
			continue
		}
		n := f.ctx.narrowingOf(field)
		node := tree.children[field.Name]
		typ := f.applyCEL(name, field, node, f.narrowedType(name, field, n))
		if typ != "" {
			props = append(props, tsProp{key: localName(field.Name), typ: typ, doc: propDoc(field, n)})
		} else if rules := emit.RuleComments(field); len(rules) > 0 {
			runtimeOnly = append(runtimeOnly, emit.RuntimeNote{Subject: field.Name, Lines: rules})
		}
		if n.Required || (node != nil && node.present) {
			required = append(required, localName(field.Name))
		}
		// OUTPUT_ONLY is not a buf.validate rule and narrows no value: the
		// server assigns the field, so the property is readonly rather than
		// retyped.
		if field.OutputOnly {
			readOnly = append(readOnly, localName(field.Name))
		}
	}

	// The wrappers, innermost first: Require<Immutable<Narrow<T, {...}>>>.
	before, after := "", ""
	if len(readOnly) > 0 {
		before, after = f.helper("Immutable")+"<", ", "+quotedUnion(readOnly)+">"
	}
	if len(required) > 0 {
		before, after = f.helper("Require")+"<"+before, after+", "+quotedUnion(required)+">"
	}

	f.doc("", f.messageDoc(msg, runtimeOnly))
	if len(props) == 0 {
		f.P("export type ", strict, " = ", before, name, after, ";")
		f.P()
		return
	}
	f.P("export type ", strict, " = ", before, f.helper("Narrow"), "<", name, ", {")
	for _, prop := range props {
		f.doc("  ", prop.doc)
		f.P("  ", prop.key, ": ", prop.typ, ";")
	}
	f.P("}>", after, ";")
	f.P()
}

// outputOnlyFields emits `<Name>OutputOnlyFields`, the dotted proto paths of
// the fields the server assigns. The readonly properties say the same thing to
// the compiler, but only about this message's own fields; a caller that has to
// name a field — a google.protobuf.FieldMask, a form, a diff — needs the paths
// as values, nested ones included, and in the form a FieldMask carries them,
// which is the proto name rather than the camelCase property.
func (f *tsFile) outputOnlyFields(msg parser.MessageMetadata) {
	if len(msg.OutputOnlyPaths) == 0 {
		return
	}
	f.doc("", []string{
		"Every field of " + msg.Name + " the server assigns: those declared",
		"`(google.api.field_behavior) = OUTPUT_ONLY` and everything under one, since the",
		"server owns the whole subtree. Dotted proto paths, so they can be subtracted from",
		"a google.protobuf.FieldMask; the ones at the top level are readonly in " +
			f.ctx.strictName(msg.Name) + ".",
	})
	f.P("export const ", f.declare(f.ctx.tsName(msg.Name)+outputOnlyFieldsSuffix), " = [")
	for _, path := range msg.OutputOnlyPaths {
		f.P("  ", strconv.Quote(path), ",")
	}
	f.P("] as const;")
	f.P()
}

// narrowedType renders a field's narrowed type, or "" when nothing narrows it.
// The base is an indexed access into the generated type, so scalars, messages,
// enums and well-known types resolve to whatever protoc-gen-es chose without
// this plugin knowing any of them.
func (f *tsFile) narrowedType(owner string, field parser.FieldMetadata, n narrowing) string {
	indexed := indexedProp(owner, localName(field.Name))

	// An enum field narrows off its enum's strict alias rather than off the
	// generated property, so an enum rule stacks on top of the excluded zero.
	base := indexed
	if n.Enum != "" {
		base = f.strictRef(n.Enum)
	}

	switch {
	case n.Target != "":
		typ := f.strictRef(n.Target)
		if field.Repeated {
			typ += "[]"
			if n.List {
				typ = f.helper("NonEmptyList") + "<" + typ + ">"
			}
		}
		return typ
	case len(n.Brands) > 0:
		// Brands are already non-nullable: `required` on the same field needs
		// only the Require wrapper, not NonNullable too.
		brands := make([]string, 0, len(n.Brands))
		for _, brand := range n.Brands {
			brands = append(brands, f.helper(brand))
		}
		return strings.Join(brands, " & ")
	case n.Extract != "":
		return "Extract<" + base + ", " + n.Extract + ">"
	case n.Exclude != "":
		return "Exclude<" + base + ", " + n.Exclude + ">"
	case n.Enum != "":
		if field.Repeated {
			base += "[]"
			if n.List {
				base = f.helper("NonEmptyList") + "<" + base + ">"
			}
		}
		return base
	case n.List:
		return f.helper("NonEmptyList") + "<" + indexed + ">"
	case n.Required:
		return "NonNullable<" + indexed + ">"
	default:
		return ""
	}
}

// applyCEL layers a message CEL rule's narrowing on top of what the field's own
// rules produced, so neither of the two is lost.
func (f *tsFile) applyCEL(owner string, field parser.FieldMetadata, node *celNode, base string) string {
	if node == nil {
		return base
	}

	if len(node.children) > 0 {
		target, ok := messageTarget(field)
		if !ok {
			return base // selectPath only places paths on singular messages
		}
		inner := base
		if inner == "" {
			if f.ctx.needsStrict[target] {
				inner = f.strictRef(target)
			} else {
				inner = f.shapeRef(target)
			}
		}
		// On top of the target's own strict type, so its rules stay in force.
		base = f.narrowNested(inner, f.ctx.messages[target], node)
	}

	// A term intersects rather than replaces: that satisfies `Narrow`'s
	// constraint by construction, and tells the truth when the two disagree. A
	// uuid a rule also requires empty becomes `Uuid & ""`, uninhabited.
	indexed := indexedProp(owner, localName(field.Name))
	if base == "" {
		base = indexed
	}

	// `Require` drops the `?` but not an `undefined` written into the property
	// type itself, which protoc-gen-es does emit — so a field a rule declares
	// present is narrowed here and lifted out of optionality there.
	if node.present && base == indexed {
		base = "NonNullable<" + indexed + ">"
	}

	switch node.term {
	case parser.TermAbsent:
		return "never"
	case parser.TermEmpty:
		return base + ` & ""`
	case parser.TermZero:
		return "Extract<" + base + ", 0>"
	default:
		if base == indexed {
			return "" // nothing narrowed the value; only the optionality moves
		}
		return base
	}
}

// narrowNested renders a nested CEL path's narrowing as one more Narrow around
// the type the field already had.
func (f *tsFile) narrowNested(owner string, msg parser.MessageMetadata, node *celNode) string {
	var props, required []string
	for _, name := range node.order {
		field, ok := fieldByName(msg, name)
		if !ok {
			continue
		}
		child := node.children[name]
		if child.present {
			required = append(required, localName(field.Name))
		}
		// The field's own rules already live in `owner`, the target's strict
		// type, so only the CEL term applies here.
		if typ := f.applyCEL(owner, field, child, ""); typ != "" {
			props = append(props, localName(field.Name)+": "+typ+"; ")
		}
	}

	expr := owner
	if len(props) > 0 {
		expr = f.helper("Narrow") + "<" + expr + ", { " + strings.Join(props, "") + "}>"
	}
	if len(required) > 0 {
		expr = f.helper("Require") + "<" + expr + ", " + quotedUnion(required) + ">"
	}
	return expr
}

// oneofProp folds a real oneof into one property. protoc-gen-es models it as a
// discriminated union whose `{ case: undefined }` member is exactly what
// `(buf.validate.oneof).required` rules out.
func (f *tsFile) oneofProp(owner string, msg parser.MessageMetadata, name string) (tsProp, bool) {
	// Without `required` the union is what protoc-gen-es already declared.
	idx := slices.IndexFunc(msg.Oneofs, func(o parser.OneofMetadata) bool {
		return o.Name == name && o.Required
	})
	if idx < 0 {
		return tsProp{}, false
	}

	key := localName(name)
	prop := tsProp{
		key: key,
		typ: "Exclude<" + indexedProp(owner, key) + ", { case: undefined }>",
		doc: []string{emit.OneofLine(msg.Oneofs[idx])},
	}
	// Member rules cannot narrow the arm, so they are printed against the member
	// name instead.
	for _, field := range msg.Fields {
		if field.OneofName != name {
			continue
		}
		for _, line := range emit.RuleComments(field) {
			prop.doc = append(prop.doc, field.Name+": "+line)
		}
	}
	return prop, true
}

// oneofMemberNotes lists the rules on the members of a oneof nothing narrowed.
// protoc-gen-es models the oneof as a discriminated union, so no member rule
// reaches an arm; every one of them holds at runtime only.
func oneofMemberNotes(msg parser.MessageMetadata, name string) []emit.RuntimeNote {
	var out []emit.RuntimeNote
	for _, field := range msg.Fields {
		if field.OneofName != name {
			continue
		}
		if rules := emit.RuleComments(field); len(rules) > 0 {
			out = append(out, emit.RuntimeNote{Subject: field.Name, Lines: rules})
		}
	}
	return out
}

// messageDoc renders what belongs above the type: the leading comment, the
// rules naming no single field, and every field rule that produced no
// narrowing. A rule that stops being carried then shows up in the diff.
func (f *tsFile) messageDoc(msg parser.MessageMetadata, runtimeOnly []emit.RuntimeNote) []string {
	var lines []string
	if msg.Comments != "" {
		lines = append(lines, emit.OneLine(msg.Comments))
	}
	// A `(buf.validate.message).oneof` names ordinary properties, so no
	// discriminated union rules out setting two of them.
	for _, oneof := range msg.Oneofs {
		if oneof.Name == "" {
			runtimeOnly = append(runtimeOnly, emit.RuntimeNote{Subject: "oneof", Lines: []string{emit.OneofLine(oneof)}})
		}
	}

	notes := f.ctx.celNotes[msg.Name]
	if carried := celCarried(notes); carried != "" {
		lines = append(lines, "", carried)
	}

	runtimeOnly = append(celRuntimeNotes(notes), runtimeOnly...)
	if len(runtimeOnly) > 0 {
		lines = append(lines, "", "Left to runtime validation, having no type equivalent:")
		for _, note := range runtimeOnly {
			lines = append(lines, "  "+note.Subject)
			for _, line := range note.Lines {
				lines = append(lines, "    "+line)
			}
		}
	}
	return lines
}

// propDoc lists every rule on a narrowed field, then names the ones the type
// carries; the rest hold only at runtime.
func propDoc(field parser.FieldMetadata, n narrowing) []string {
	lines := emit.RuleComments(field)
	if len(n.consumed) == 0 {
		return lines
	}
	carried := slices.Sorted(maps.Keys(n.consumed))
	return append(lines, "", emit.CarriedPrefix+strings.Join(carried, ", ")+".")
}

// indexedProp is one property as protoc-gen-es declared it, the base every
// narrowing builds on.
func indexedProp(owner, local string) string {
	return owner + "[" + strconv.Quote(local) + "]"
}
