// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/inventory/v1/warehouse.proto

import { z } from "zod/v3";
import { durationZod, timestampZod } from "../../../strict/wkt.zod3.js";
import { moneyZod } from "../../common/v1/common.zod3.js";

/**
 * StockMovementKind classifies a change in stock level.
 *
 * shop.inventory.v1.StockMovementKind, as protojson writes it: the member's name.
 */
export declare const stockMovementKindZod: z.ZodEnum<["STOCK_MOVEMENT_KIND_UNSPECIFIED", "STOCK_MOVEMENT_KIND_INBOUND", "STOCK_MOVEMENT_KIND_OUTBOUND", "STOCK_MOVEMENT_KIND_ADJUSTMENT"]>;

/**
 * Address is nested to check that nested messages are walked.
 *
 * The composable schema of shop.inventory.v1.Warehouse.Address: every field carries its own rules, so
 * `warehouseAddressZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in warehouseAddressZod.
 */
export declare const warehouseAddressZodObject: z.ZodObject<{
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  line1: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_len = 120
   *
   * Checked by protovalidate: string.max_len.
   */
  line2: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  city: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.len = 2
   * string.pattern = ^[A-Z]{2}$
   *
   * Checked by protovalidate: string.len, string.pattern.
   */
  countryCode: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.max_len = 12
   * string.min_len = 3
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  postalCode: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.Warehouse.Address. Adds what protovalidate checks on the whole message:
 *   the rules of line1, city, country_code, postal_code when absent: protojson omits a zero value
 */
export declare const warehouseAddressZod: z.ZodEffects<typeof warehouseAddressZodObject>;

/**
 * OpeningHours is a daily window expressed in minutes past midnight.
 *
 * The composable schema of shop.inventory.v1.OpeningHours: every field carries its own rules, so
 * `openingHoursZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in openingHoursZod.
 */
export declare const openingHoursZodObject: z.ZodObject<{
  /**
   * uint32.lte = 1439
   *
   * Carried by Zod: uint32.lte.
   */
  opensAtMinute: z.ZodOptional<z.ZodNumber>;
  /**
   * uint32.lte = 1440
   *
   * Carried by Zod: uint32.lte.
   */
  closesAtMinute: z.ZodOptional<z.ZodNumber>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.OpeningHours. Adds what protovalidate checks on the whole message:
 *   cel[opening_hours.ordered]
 *   the rules of opens_at_minute, closes_at_minute when absent: protojson omits a zero value
 */
export declare const openingHoursZod: z.ZodEffects<typeof openingHoursZodObject>;

/**
 * ContactPoint reaches a person by exactly one channel.
 *
 * The composable schema of shop.inventory.v1.ContactPoint: every field carries its own rules, so
 * `contactPointZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in contactPointZod.
 */
export declare const contactPointZodObject: z.ZodObject<{
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  name: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.ZodOptional<z.ZodString>;
  /**
   * string.pattern = ^\+[1-9][0-9]{7,14}$
   *
   * Checked by protovalidate: string.pattern.
   */
  phone: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * uint32.gte = 100
   * uint32.lte = 9999
   *
   * Carried by Zod: uint32.gte, uint32.lte.
   */
  extension: z.ZodOptional<z.ZodNumber>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.ContactPoint. Adds what protovalidate checks on the whole message:
 *   required oneof channel: exactly one of email, phone, extension
 *   the rules of name when absent: protojson omits a zero value
 */
export declare const contactPointZod: z.ZodEffects<typeof contactPointZodObject>;

/**
 * Warehouse is a physical stocking location.
 *
 * The composable schema of shop.inventory.v1.Warehouse: every field carries its own rules, so
 * `warehouseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in warehouseZod.
 */
export declare const warehouseZodObject: z.ZodObject<{
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.ZodOptional<z.ZodString>;
  /**
   * string.max_len = 120
   * string.min_len = 1
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  name: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * required
   *
   * Carried by Zod: required.
   */
  address: typeof warehouseAddressZod;
  /**
   * duration.gte.seconds = 3600
   * duration.lte.seconds = 2592000
   *
   * Checked by protovalidate: duration.gte.seconds, duration.lte.seconds.
   */
  maxDwellTime: z.ZodOptional<z.ZodEffects<typeof durationZod>>;
  /**
   * map.keys.string.in = [mon, tue, wed, thu, fri, sat, sun]
   * map.max_pairs = 7
   *
   * Checked by protovalidate: map.keys.string.in, map.max_pairs.
   */
  openingHours: z.ZodOptional<z.ZodEffects<z.ZodRecord<z.ZodString, typeof openingHoursZod>>>;
  /**
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.min_items.
   */
  contacts: z.ZodOptional<z.ZodArray<typeof contactPointZod>>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.Warehouse. Adds what protovalidate checks on the whole message:
 *   the rules of id, name, opening_hours, contacts when absent: protojson omits a zero value
 */
export declare const warehouseZod: z.ZodEffects<typeof warehouseZodObject>;

/**
 * StockMovement records one change to the stock level of a product.
 *
 * The composable schema of shop.inventory.v1.StockMovement: every field carries its own rules, so
 * `stockMovementZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stockMovementZod.
 */
export declare const stockMovementZodObject: z.ZodObject<{
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.ZodOptional<z.ZodString>;
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  warehouseId: z.ZodString;
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  productId: z.ZodString;
  /**
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried by Zod: enum.defined_only, enum.not_in.
   */
  kind: z.ZodOptional<z.ZodEnum<["STOCK_MOVEMENT_KIND_INBOUND", "STOCK_MOVEMENT_KIND_OUTBOUND", "STOCK_MOVEMENT_KIND_ADJUSTMENT"]>>;
  /**
   * sint32.gte = -100000
   * sint32.lte = 100000
   *
   * Carried by Zod: sint32.gte, sint32.lte.
   */
  quantityDelta: z.ZodOptional<z.ZodNumber>;
  /**
   * required
   * timestamp.lt_now = true
   *
   * Carried by Zod: required.
   * Checked by protovalidate: timestamp.lt_now.
   */
  occurredAt: z.ZodEffects<typeof timestampZod>;
  unitCost: z.ZodOptional<typeof moneyZod>;
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  purchaseOrderId: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  customerOrderId: z.ZodOptional<z.ZodEffects<z.ZodString>>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.StockMovement. Adds what protovalidate checks on the whole message:
 *   cel[stock_movement.quantity_sign]
 *   oneof: at most one of purchase_order_id, customer_order_id
 *   the rules of id, kind, quantity_delta when absent: protojson omits a zero value
 */
export declare const stockMovementZod: z.ZodEffects<typeof stockMovementZodObject>;

/**
 * StockLevel is the current quantity of a product in a warehouse.
 *
 * The composable schema of shop.inventory.v1.StockLevel: every field carries its own rules, so
 * `stockLevelZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stockLevelZod.
 */
export declare const stockLevelZodObject: z.ZodObject<{
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  productId: z.ZodOptional<z.ZodString>;
  /**
   * uint64.lte = 100000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  onHand: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * uint64.lte = 100000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  reserved: z.ZodOptional<z.ZodEffects<z.ZodString>>;
  /**
   * timestamp.within.seconds = 7776000
   *
   * Checked by protovalidate: timestamp.within.seconds.
   */
  countedAt: z.ZodOptional<z.ZodEffects<typeof timestampZod>>;
  /**
   * cel[this <= 10000]: this <= 10000
   *   refs: this
   *   calls: _<=_
   *
   * Checked by protovalidate: cel[this <= 10000].
   */
  reorderThreshold: z.ZodOptional<z.ZodEffects<z.ZodNumber>>;
}, "strict">;

/**
 * Full validation of shop.inventory.v1.StockLevel. Adds what protovalidate checks on the whole message:
 *   cel[stock_level.reserved_within_on_hand]
 *   the rules of product_id, on_hand, reserved, reorder_threshold when absent: protojson omits a zero value
 */
export declare const stockLevelZod: z.ZodEffects<typeof stockLevelZodObject>;
