// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/inventory/v1/warehouse.proto

import { z } from "zod/v3";
import { field, message, register } from "../../../strict/protovalidate.js";
import { durationZod, timestampZod } from "../../../strict/wkt.zod3.js";
import { moneyZod } from "../../common/v1/common.zod3.js";
import { ContactPointSchema, OpeningHoursSchema, StockLevelSchema, StockMovementSchema, WarehouseSchema, Warehouse_AddressSchema, file_shop_inventory_v1_warehouse } from "./warehouse_pb.js";

register(file_shop_inventory_v1_warehouse);

/**
 * StockMovementKind classifies a change in stock level.
 *
 * shop.inventory.v1.StockMovementKind, as protojson writes it: the member's name.
 */
export const stockMovementKindZod = z.enum(["STOCK_MOVEMENT_KIND_UNSPECIFIED", "STOCK_MOVEMENT_KIND_INBOUND", "STOCK_MOVEMENT_KIND_OUTBOUND", "STOCK_MOVEMENT_KIND_ADJUSTMENT"]);

/**
 * Address is nested to check that nested messages are walked.
 *
 * The composable schema of shop.inventory.v1.Warehouse.Address: every field carries its own rules, so
 * `warehouseAddressZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in warehouseAddressZod.
 */
export const warehouseAddressZodObject = z.strictObject({
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  line1: z.string().superRefine(field(Warehouse_AddressSchema, "line1")).optional(),
  /**
   * string.max_len = 120
   *
   * Checked by protovalidate: string.max_len.
   */
  line2: z.string().superRefine(field(Warehouse_AddressSchema, "line2")).optional(),
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  city: z.string().superRefine(field(Warehouse_AddressSchema, "city")).optional(),
  /**
   * string.len = 2
   * string.pattern = ^[A-Z]{2}$
   *
   * Checked by protovalidate: string.len, string.pattern.
   */
  countryCode: z.string().superRefine(field(Warehouse_AddressSchema, "country_code")).optional(),
  /**
   * string.max_len = 12
   * string.min_len = 3
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  postalCode: z.string().superRefine(field(Warehouse_AddressSchema, "postal_code")).optional(),
});

/**
 * Full validation of shop.inventory.v1.Warehouse.Address. Adds what protovalidate checks on the whole message:
 *   the rules of line1, city, country_code, postal_code when absent: protojson omits a zero value
 */
export const warehouseAddressZod = warehouseAddressZodObject.superRefine(message(Warehouse_AddressSchema));

/**
 * OpeningHours is a daily window expressed in minutes past midnight.
 *
 * The composable schema of shop.inventory.v1.OpeningHours: every field carries its own rules, so
 * `openingHoursZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in openingHoursZod.
 */
export const openingHoursZodObject = z.strictObject({
  /**
   * uint32.lte = 1439
   *
   * Carried by Zod: uint32.lte.
   */
  opensAtMinute: z.number().int().lte(1439).optional(),
  /**
   * uint32.lte = 1440
   *
   * Carried by Zod: uint32.lte.
   */
  closesAtMinute: z.number().int().lte(1440).optional(),
});

/**
 * Full validation of shop.inventory.v1.OpeningHours. Adds what protovalidate checks on the whole message:
 *   cel[opening_hours.ordered]
 *   the rules of opens_at_minute, closes_at_minute when absent: protojson omits a zero value
 */
export const openingHoursZod = openingHoursZodObject.superRefine(message(OpeningHoursSchema));

/**
 * ContactPoint reaches a person by exactly one channel.
 *
 * The composable schema of shop.inventory.v1.ContactPoint: every field carries its own rules, so
 * `contactPointZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in contactPointZod.
 */
export const contactPointZodObject = z.strictObject({
  /**
   * string.min_len = 1
   *
   * Checked by protovalidate: string.min_len.
   */
  name: z.string().superRefine(field(ContactPointSchema, "name")).optional(),
  /**
   * string.email = true
   *
   * Carried by Zod: string.email.
   */
  email: z.string().regex(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/).optional(),
  /**
   * string.pattern = ^\+[1-9][0-9]{7,14}$
   *
   * Checked by protovalidate: string.pattern.
   */
  phone: z.string().superRefine(field(ContactPointSchema, "phone")).optional(),
  /**
   * uint32.gte = 100
   * uint32.lte = 9999
   *
   * Carried by Zod: uint32.gte, uint32.lte.
   */
  extension: z.number().int().gte(100).lte(9999).optional(),
});

/**
 * Full validation of shop.inventory.v1.ContactPoint. Adds what protovalidate checks on the whole message:
 *   required oneof channel: exactly one of email, phone, extension
 *   the rules of name when absent: protojson omits a zero value
 */
export const contactPointZod = contactPointZodObject.superRefine(message(ContactPointSchema));

/**
 * Warehouse is a physical stocking location.
 *
 * The composable schema of shop.inventory.v1.Warehouse: every field carries its own rules, so
 * `warehouseZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in warehouseZod.
 */
export const warehouseZodObject = z.strictObject({
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * string.max_len = 120
   * string.min_len = 1
   *
   * Checked by protovalidate: string.max_len, string.min_len.
   */
  name: z.string().superRefine(field(WarehouseSchema, "name")).optional(),
  /**
   * required
   *
   * Carried by Zod: required.
   */
  address: warehouseAddressZod,
  /**
   * duration.gte.seconds = 3600
   * duration.lte.seconds = 2592000
   *
   * Checked by protovalidate: duration.gte.seconds, duration.lte.seconds.
   */
  maxDwellTime: durationZod.superRefine(field(WarehouseSchema, "max_dwell_time")).optional(),
  /**
   * map.keys.string.in = [mon, tue, wed, thu, fri, sat, sun]
   * map.max_pairs = 7
   *
   * Checked by protovalidate: map.keys.string.in, map.max_pairs.
   */
  openingHours: z.record(z.string(), openingHoursZod).superRefine(field(WarehouseSchema, "opening_hours")).optional(),
  /**
   * repeated.min_items = 1
   *
   * Carried by Zod: repeated.min_items.
   */
  contacts: z.array(contactPointZod).min(1).optional(),
});

/**
 * Full validation of shop.inventory.v1.Warehouse. Adds what protovalidate checks on the whole message:
 *   the rules of id, name, opening_hours, contacts when absent: protojson omits a zero value
 */
export const warehouseZod = warehouseZodObject.superRefine(message(WarehouseSchema));

/**
 * StockMovement records one change to the stock level of a product.
 *
 * The composable schema of shop.inventory.v1.StockMovement: every field carries its own rules, so
 * `stockMovementZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stockMovementZod.
 */
export const stockMovementZodObject = z.strictObject({
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  id: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  warehouseId: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).min(1),
  /**
   * required
   * string.uuid = true
   *
   * Carried by Zod: required, string.uuid.
   */
  productId: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).min(1),
  /**
   * enum.defined_only = true
   * enum.not_in = [0]
   *
   * Carried by Zod: enum.defined_only, enum.not_in.
   */
  kind: z.enum(["STOCK_MOVEMENT_KIND_INBOUND", "STOCK_MOVEMENT_KIND_OUTBOUND", "STOCK_MOVEMENT_KIND_ADJUSTMENT"]).optional(),
  /**
   * sint32.gte = -100000
   * sint32.lte = 100000
   *
   * Carried by Zod: sint32.gte, sint32.lte.
   */
  quantityDelta: z.number().int().gte(-100000).lte(100000).optional(),
  /**
   * required
   * timestamp.lt_now = true
   *
   * Carried by Zod: required.
   * Checked by protovalidate: timestamp.lt_now.
   */
  occurredAt: timestampZod.superRefine(field(StockMovementSchema, "occurred_at", ["required"])),
  unitCost: moneyZod.optional(),
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  purchaseOrderId: z.string().superRefine(field(StockMovementSchema, "purchase_order_id")).optional(),
  /**
   * ignore = IGNORE_IF_ZERO_VALUE (implied by the message oneof)
   * string.max_len = 64
   *
   * Checked by protovalidate: string.max_len.
   */
  customerOrderId: z.string().superRefine(field(StockMovementSchema, "customer_order_id")).optional(),
});

/**
 * Full validation of shop.inventory.v1.StockMovement. Adds what protovalidate checks on the whole message:
 *   cel[stock_movement.quantity_sign]
 *   oneof: at most one of purchase_order_id, customer_order_id
 *   the rules of id, kind, quantity_delta when absent: protojson omits a zero value
 */
export const stockMovementZod = stockMovementZodObject.superRefine(message(StockMovementSchema));

/**
 * StockLevel is the current quantity of a product in a warehouse.
 *
 * The composable schema of shop.inventory.v1.StockLevel: every field carries its own rules, so
 * `stockLevelZodObject.shape.<field>`, `.pick()`, `.extend()` and `.partial()` keep validating.
 * The rules on the message as a whole are in stockLevelZod.
 */
export const stockLevelZodObject = z.strictObject({
  /**
   * string.uuid = true
   *
   * Carried by Zod: string.uuid.
   */
  productId: z.string().regex(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/).optional(),
  /**
   * uint64.lte = 100000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  onHand: z.string().regex(/^[0-9]+$/).superRefine(field(StockLevelSchema, "on_hand")).optional(),
  /**
   * uint64.lte = 100000000
   *
   * Checked by protovalidate: uint64.lte.
   */
  reserved: z.string().regex(/^[0-9]+$/).superRefine(field(StockLevelSchema, "reserved")).optional(),
  /**
   * timestamp.within.seconds = 7776000
   *
   * Checked by protovalidate: timestamp.within.seconds.
   */
  countedAt: timestampZod.superRefine(field(StockLevelSchema, "counted_at")).optional(),
  /**
   * cel[this <= 10000]: this <= 10000
   *   refs: this
   *   calls: _<=_
   *
   * Checked by protovalidate: cel[this <= 10000].
   */
  reorderThreshold: z.number().int().superRefine(field(StockLevelSchema, "reorder_threshold")).optional(),
});

/**
 * Full validation of shop.inventory.v1.StockLevel. Adds what protovalidate checks on the whole message:
 *   cel[stock_level.reserved_within_on_hand]
 *   the rules of product_id, on_hand, reserved, reorder_threshold when absent: protojson omits a zero value
 */
export const stockLevelZod = stockLevelZodObject.superRefine(message(StockLevelSchema));
