package generator

import (
	"slices"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// openAPIConfigFile is the whole OpenAPI output: one file for the run. Its keys
// are fully qualified proto names, so there is nothing per-directory to shard —
// which is why the plugin entry needs `strategy: all`.
const openAPIConfigFile = "openapi_config.yaml"

// repeatedItems prefixes the rules that describe a list's elements rather than
// the list. protoc-gen-openapiv2 puts every scalar keyword of an array field on
// its `items`, so these map through the same table as the singular forms.
const repeatedItems = "repeated.items."

// numberKind tells boundKeywords whether the field counts in whole numbers,
// where an exclusive bound has an inclusive equivalent one step away.
type numberKind int

const (
	wholeNumber numberKind = iota
	fractional
)

// boundedTypes are the numeric rule prefixes whose bounds become JSON numbers.
//
// The 64-bit integers are absent on purpose: JSON carries them as strings, and
// protoc-gen-openapiv2 types them `{"type": "string", "format": "int64"}`, where
// a `minimum` describes nothing. `bytes` is absent for the same reason — its
// length rules count raw bytes, not the base64 the client sends.
var boundedTypes = map[string]numberKind{
	"int32": wholeNumber, "sint32": wholeNumber, "sfixed32": wholeNumber,
	"uint32": wholeNumber, "fixed32": wholeNumber,
	"float": fractional, "double": fractional,
}

// stringFormats are the string rules that name a JSONSchema `format`.
var stringFormats = map[string]string{
	"uuid":     "uuid",
	"email":    "email",
	"uri":      "uri",
	"hostname": "hostname",
	"ipv4":     "ipv4",
	"ipv6":     "ipv6",
}

// keyword is one JSONSchema keyword and its value, already rendered as YAML.
type keyword struct {
	key   string
	value string
}

// writeOpenAPIConfig writes the grpc-gateway OpenAPI configuration that carries
// the buf.validate rules into protoc-gen-openapiv2's output.
//
// protoc-gen-openapiv2 reads no protovalidate rule, so every constraint is
// missing from the swagger it generates. It does accept an external
// configuration — `openapi_configuration=<file>` — whose `field` entries attach
// a JSONSchema to a field by fully qualified name. That is the whole
// integration: the .proto files stay free of OpenAPI annotations and the
// generated JSON is never patched.
//
// The config has to exist before protoc-gen-openapiv2 runs, so the two are
// separate `buf generate` passes; see the Makefile.
func writeOpenAPIConfig(gen *protogen.Plugin, messages []parser.MessageMetadata) {
	type entry struct {
		field    string // fully qualified, e.g. "shop.catalog.v1.Product.sku"
		keywords []keyword
	}

	var entries []entry
	for _, msg := range messages {
		for _, field := range msg.Fields {
			keywords := fieldKeywords(field)
			if len(keywords) == 0 {
				continue
			}
			entries = append(entries, entry{msg.Name + "." + field.Name, keywords})
		}
	}

	g := gen.NewGeneratedFile(openAPIConfigFile, "")
	g.P("# Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("# buf.validate rules, as grpc-gateway OpenAPI field options.")
	g.P("# Pass it to protoc-gen-openapiv2 as openapi_configuration=<this file>.")
	g.P("openapiOptions:")
	if len(entries) == 0 {
		return
	}
	g.P("  field:")
	for _, e := range entries {
		g.P("    - field: ", e.field)
		g.P("      option:")
		for _, kw := range e.keywords {
			g.P("        ", kw.key, ": ", kw.value)
		}
	}
}

// fieldKeywords renders every rule on a field that has a JSONSchema equivalent.
//
// The order follows FieldMetadata.Rules, which the parser sorts by rule name,
// so two runs on the same proto emit the same bytes. A keyword two rules both
// claim — `string.len` alongside `string.min_len` — keeps the first: the proto
// contradicts itself, and a duplicate YAML key would fail to parse at all.
func fieldKeywords(field parser.FieldMetadata) []keyword {
	// `ignore` means the rules do not always apply, so none of them describes
	// the schema either — the same call fieldNarrowing makes for TypeScript.
	if _, ok := ruleValue(field, "ignore"); ok {
		return nil
	}

	var out []keyword
	add := func(keywords ...keyword) {
		for _, kw := range keywords {
			if !slices.ContainsFunc(out, func(seen keyword) bool { return seen.key == kw.key }) {
				out = append(out, kw)
			}
		}
	}

	// `required` is absent on purpose. grpc-gateway hoists it into the parent
	// message's required list, which is right for a body schema — but the same
	// list also marks the flattened query parameter of a GET required, and a
	// field of an optional sub-message is not. Over-narrowing a request is worse
	// than leaving the rule to runtime validation.
	for _, rule := range field.Rules {
		add(ruleKeywords(rule)...)
	}
	return out
}

// ruleKeywords maps one protovalidate rule onto JSONSchema keywords. A rule
// with no equivalent yields none: under-narrowing is the safe direction.
func ruleKeywords(rule parser.Rule) []keyword {
	prefix, leaf, ok := strings.Cut(strings.TrimPrefix(rule.Kind, repeatedItems), ".")
	if !ok {
		return nil
	}

	if kind, ok := boundedTypes[prefix]; ok {
		return boundKeywords(leaf, rule.Value, kind)
	}

	switch {
	case prefix == "string":
		return stringKeywords(leaf, rule.Value)
	case prefix == "repeated":
		return repeatedKeywords(leaf, rule.Value)
	case prefix == "map":
		return mapKeywords(leaf, rule.Value)
	}
	return nil
}

// boundKeywords maps one numeric bound onto `minimum` or `maximum`.
//
// A whole-number exclusive bound is rewritten as the inclusive bound one step
// away — `gt: 0` is `minimum: 1` — which keeps it out of the zero that
// jsonNumber has to drop, and keeps draft-4's `exclusiveMinimum` out of the
// output for every integer field.
func boundKeywords(leaf, value string, kind numberKind) []keyword {
	if kind == wholeNumber {
		switch leaf {
		case "gt":
			if shifted, ok := shiftedBound(value, 1); ok {
				leaf, value = "gte", shifted
			}
		case "lt":
			if shifted, ok := shiftedBound(value, -1); ok {
				leaf, value = "lte", shifted
			}
		}
	}

	number, ok := jsonNumber(value)
	if !ok {
		return nil
	}
	switch leaf {
	case "gte":
		return []keyword{{"minimum", number}}
	case "gt":
		return []keyword{{"minimum", number}, {"exclusiveMinimum", "true"}}
	case "lte":
		return []keyword{{"maximum", number}}
	case "lt":
		return []keyword{{"maximum", number}, {"exclusiveMaximum", "true"}}
	}
	return nil
}

func stringKeywords(leaf, value string) []keyword {
	if format, ok := stringFormats[leaf]; ok && value == "true" {
		return []keyword{{"format", strconv.Quote(format)}}
	}
	switch leaf {
	case "len":
		return []keyword{{"maxLength", value}, {"minLength", value}}
	case "max_len":
		return []keyword{{"maxLength", value}}
	case "min_len":
		return []keyword{{"minLength", value}}
	case "pattern":
		// A RE2 source string, straight from the proto: quote it.
		return []keyword{{"pattern", strconv.Quote(value)}}
	}
	return nil
}

func repeatedKeywords(leaf, value string) []keyword {
	switch leaf {
	case "max_items":
		return []keyword{{"maxItems", value}}
	case "min_items":
		return []keyword{{"minItems", value}}
	case "unique":
		if value == "true" {
			return []keyword{{"uniqueItems", "true"}}
		}
	}
	return nil
}

func mapKeywords(leaf, value string) []keyword {
	switch leaf {
	case "max_pairs":
		return []keyword{{"maxProperties", value}}
	case "min_pairs":
		return []keyword{{"minProperties", value}}
	}
	return nil
}

// shiftedBound turns an exclusive whole-number bound into the inclusive one a
// step away. It reports false when the parser did not print an integer, which
// leaves the exclusive form in place.
func shiftedBound(value string, step int64) (string, bool) {
	number, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		return "", false
	}
	return strconv.FormatInt(number+step, 10), true
}

// jsonNumber re-renders a bound as a plain decimal. The parser hands back
// whatever protoreflect printed, and a float in exponent form ("1e+06") is not
// a number to the YAML parser grpc-gateway loads the config with.
//
// A zero is reported absent. grpc-gateway's swagger writer tags `minimum` and
// `maximum` `omitempty`, so a zero bound never reaches the output — and what it
// leaves behind, an `exclusiveMinimum: true` with no `minimum`, describes
// nothing at all.
func jsonNumber(value string) (string, bool) {
	number, err := strconv.ParseFloat(value, 64)
	if err != nil || number == 0 {
		return "", false
	}
	return strconv.FormatFloat(number, 'f', -1, 64), true
}
