package generator

import (
	"maps"
	"path"
	"slices"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// pyScalars maps proto scalars to the types protoc-gen-pyi declares.
var pyScalars = map[string]string{
	"string": "str", "bool": "bool", "bytes": "bytes",
	"double": "float", "float": "float",
	"int32": "int", "sint32": "int", "sfixed32": "int",
	"uint32": "int", "fixed32": "int",
	"int64": "int", "sint64": "int", "sfixed64": "int",
	"uint64": "int", "fixed64": "int",
}

// pyAlias is one `Name = Annotated[T, "rule", ...]` binding.
type pyAlias struct {
	name  string
	typ   string
	rules []string
}

// writePython writes a <prefix>_strict.py overlay on protoc-gen-python output.
//
// Python cannot narrow a type: message classes come from a metaclass and carry
// no structural type to intersect with. It can name each constrained field, so
// the rules show at the call site: `def promote(user_id: UserId)` instead of
// `user_id: str`. The classes are re-exported, so one import covers
// both.
func writePython(gen *protogen.Plugin, file *protogen.File, messages []parser.MessageMetadata) {
	pkgPrefix := string(file.Desc.Package()) + "."
	imports := &pyImports{
		self:    file.Desc.Path(),
		symbols: map[string]bool{},
		modules: map[string]string{},
		typing:  map[string]bool{},
		abc:     map[string]bool{},
	}

	// Resolving types populates the import set, so it runs before the header.
	type block struct {
		doc     []string
		aliases []pyAlias
	}
	blocks := make([]block, 0, len(messages))
	for _, msg := range messages {
		relative := strings.TrimPrefix(msg.Name, pkgPrefix)
		owner := strings.ReplaceAll(relative, ".", "")
		imports.symbols[topLevel(relative)] = true

		b := block{doc: pyMessageDoc(msg)}
		for _, field := range msg.Fields {
			rules := ruleComments(field)
			if len(rules) == 0 {
				continue
			}
			b.aliases = append(b.aliases, pyAlias{
				name:  owner + pascal(field.Name),
				typ:   imports.typeOf(field),
				rules: rules,
			})
		}
		blocks = append(blocks, b)
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_strict.py", "")
	g.P("# Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("# source: ", file.Desc.Path())
	g.P(`"""buf.validate rules for `, file.Desc.Path(), `.`)
	g.P()
	g.P("Types come from ", pyModule(file.Desc.Path()), " and are re-exported here, so one")
	g.P("import gives a caller both the message class and its annotated field types.")
	g.P(`"""`)
	g.P()
	g.P("from __future__ import annotations")
	g.P()
	for _, line := range imports.lines() {
		g.P(line)
	}
	g.P()

	for _, b := range blocks {
		for _, line := range b.doc {
			g.P("# ", line)
		}
		if len(b.aliases) == 0 {
			if len(b.doc) > 0 {
				g.P()
			}
			continue
		}
		for _, alias := range b.aliases {
			g.P(alias.name, " = Annotated[")
			g.P("    ", alias.typ, ",")
			for _, rule := range alias.rules {
				g.P("    ", strconv.Quote(rule), ",")
			}
			g.P("]")
		}
		g.P()
	}
}

// pyImports resolves proto type references to Python names and records the
// import each needs. Symbols from this file are imported by name so they are
// re-exported; the rest go through a module alias, as protoc-gen-pyi does.
type pyImports struct {
	self    string
	symbols map[string]bool   // top-level names taken from the sibling _pb2 module
	modules map[string]string // proto path -> module alias
	typing  map[string]bool   // names from typing
	abc     map[string]bool   // names from collections.abc
}

// typeOf renders the Python type of a field, ignoring the rules attached to it.
func (p *pyImports) typeOf(field parser.FieldMetadata) string {
	p.typing["Annotated"] = true
	switch {
	case field.IsMap:
		p.abc["Mapping"] = true
		return "Mapping[" + p.base(field.MapKey, parser.TypeRef{}) + ", " + p.base(field.MapValue, field.MapValType) + "]"
	case field.Repeated:
		// protoc-gen-pyi declares these as Repeated{Scalar,Composite}FieldContainer,
		// both MutableSequence subclasses.
		p.abc["Sequence"] = true
		return "Sequence[" + p.base(field.ProtoType, field.Type) + "]"
	default:
		return p.base(field.ProtoType, field.Type)
	}
}

func (p *pyImports) base(protoType string, ref parser.TypeRef) string {
	if ref.Name != "" {
		if ref.File == p.self {
			p.symbols[topLevel(ref.Name)] = true
			return ref.Name
		}
		alias := "_" + strings.TrimSuffix(path.Base(ref.File), ".proto") + "_pb2"
		p.modules[ref.File] = alias
		return alias + "." + ref.Name
	}
	if mapped, ok := pyScalars[protoType]; ok {
		return mapped
	}
	p.typing["Any"] = true
	return "Any"
}

func (p *pyImports) lines() []string {
	var out []string
	if len(p.abc) > 0 {
		out = append(out, "from collections.abc import "+strings.Join(slices.Sorted(maps.Keys(p.abc)), ", "))
	}
	if len(p.typing) > 0 {
		out = append(out, "from typing import "+strings.Join(slices.Sorted(maps.Keys(p.typing)), ", "))
	}
	if len(out) > 0 {
		out = append(out, "")
	}

	for _, file := range slices.Sorted(maps.Keys(p.modules)) {
		module, alias := pyModule(file), p.modules[file]
		// A proto at the import root is a top-level module with no package to
		// import it from: "user.proto" is "user_pb2".
		dot := strings.LastIndex(module, ".")
		if dot < 0 {
			out = append(out, "import "+module+" as "+alias)
			continue
		}
		out = append(out, "from "+module[:dot]+" import "+module[dot+1:]+" as "+alias)
	}

	names := slices.Sorted(maps.Keys(p.symbols))
	if len(names) > 0 {
		// `X as X` marks a deliberate re-export, which type checkers require
		// before a caller may import it from here.
		out = append(out, "from "+pyModule(p.self)+" import (")
		for _, name := range names {
			out = append(out, "    "+name+" as "+name+",")
		}
		out = append(out, ")")
	}
	return out
}

// topLevel is the outermost name, which is what the generated module exports:
// "Warehouse.Address" is nested in "Warehouse" and has no export of its own.
func topLevel(relative string) string {
	top, _, _ := strings.Cut(relative, ".")
	return top
}

// pyModule turns a proto path into the module protoc-gen-python writes for it.
//
// ponytail: two files with the same base name in different packages collapse to
// the same `_<base>_pb2` alias, as in protoc-gen-pyi. Widen it to the full path
// if a schema ever trips it.
func pyModule(protoPath string) string {
	return strings.ReplaceAll(strings.TrimSuffix(protoPath, ".proto"), "/", ".") + "_pb2"
}

// pyMessageDoc renders the leading comment and the message-level rules.
func pyMessageDoc(msg parser.MessageMetadata) []string {
	var lines []string
	if msg.Comments != "" {
		lines = append(lines, oneLine(msg.Comments))
	}
	return append(lines, messageComments(msg)...)
}
