package generator

import (
	"maps"
	"slices"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// tsProp is one property of the object `Narrow` applies to the generated type.
type tsProp struct {
	key string
	typ string
	doc []string
}

// writeTypeScript writes a <prefix>.strict.ts overlay on protoc-gen-es output.
//
// Every message becomes `<Name>Strict`: the generated type narrowed by the
// rules a type can express, untouched otherwise. It stays assignable to the
// type it narrows, so anything protobuf-es generated still accepts it.
func writeTypeScript(gen *protogen.Plugin, file *protogen.File, ctx *Context) {
	f := newTSFile(ctx, file)
	for _, msg := range ctx.byFile[f.proto] {
		f.message(msg)
	}
	for _, msg := range ctx.byFile[f.proto] {
		if ctx.strictSchemas[msg.Name] {
			f.strictSchema(msg)
		}
	}
	for _, service := range file.Services {
		f.service(service)
	}

	g := gen.NewGeneratedFile(f.out, "")
	g.P("// Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("// source: ", f.proto)
	g.P()
	for _, line := range f.importLines() {
		g.P(line)
	}
	g.P()
	for _, line := range f.lines {
		g.P(line)
	}
}

// message emits `<Name>Strict`.
func (f *tsFile) message(msg parser.MessageMetadata) {
	name := f.shape(f.ctx.tsName(msg.Name))
	var props []tsProp
	var required []string
	var runtimeOnly []runtimeNote

	tree := f.ctx.celTrees[msg.Name]
	seen := map[string]bool{}
	for _, field := range msg.Fields {
		if field.OneofName != "" {
			if seen[field.OneofName] {
				continue
			}
			seen[field.OneofName] = true
			if prop, ok := f.oneofProp(name, msg, field.OneofName); ok {
				props = append(props, prop)
			}
			continue
		}
		n := f.ctx.narrowingOf(field)
		node := tree.children[field.Name]
		typ := f.applyCEL(name, field, node, f.narrowedType(name, field, n))
		if typ != "" {
			props = append(props, tsProp{key: field.JSONName, typ: typ, doc: propDoc(field, n)})
		} else if rules := ruleComments(field); len(rules) > 0 {
			runtimeOnly = append(runtimeOnly, runtimeNote{subject: field.Name, lines: rules})
		}
		if n.Required || (node != nil && node.term == parser.TermPresent) {
			required = append(required, field.JSONName)
		}
	}

	f.doc("", f.messageDoc(msg, runtimeOnly))
	switch {
	case len(props) == 0 && len(required) == 0:
		f.P("export type ", name, "Strict = ", name, ";")
	case len(props) == 0:
		f.P("export type ", name, "Strict = ", f.helper("Require"), "<", name, ", ", quotedUnion(required), ">;")
	default:
		open, close := "", ""
		if len(required) > 0 {
			open, close = f.helper("Require")+"<", ", "+quotedUnion(required)+">"
		}
		f.P("export type ", name, "Strict = ", open, f.helper("Narrow"), "<", name, ", {")
		for _, prop := range props {
			f.doc("  ", prop.doc)
			f.P("  ", prop.key, ": ", prop.typ, ";")
		}
		f.P("}>", close, ";")
	}
	f.P()
}

// narrowedType renders a field's narrowed type, or "" when nothing narrows it.
// The base is an indexed access into the generated type, so scalars, messages,
// enums and well-known types resolve to whatever protoc-gen-es chose without
// this plugin knowing any of them.
func (f *tsFile) narrowedType(owner string, field parser.FieldMetadata, n narrowing) string {
	indexed := indexedProp(owner, field.JSONName)
	switch {
	case n.Target != "":
		typ := f.strictRef(n.Target)
		if field.Repeated {
			typ += "[]"
			if n.List {
				typ = f.helper("NonEmptyList") + "<" + typ + ">"
			}
		}
		return typ
	case len(n.Brands) > 0:
		// Brands are already non-nullable: `required` on the same field needs
		// only the Require wrapper, not NonNullable too.
		brands := make([]string, 0, len(n.Brands))
		for _, brand := range n.Brands {
			brands = append(brands, f.helper(brand))
		}
		return strings.Join(brands, " & ")
	case n.Extract != "":
		return "Extract<" + indexed + ", " + n.Extract + ">"
	case n.Exclude != "":
		return "Exclude<" + indexed + ", " + n.Exclude + ">"
	case n.List:
		return f.helper("NonEmptyList") + "<" + indexed + ">"
	case n.Required:
		return "NonNullable<" + indexed + ">"
	default:
		return ""
	}
}

// applyCEL layers a message CEL rule's narrowing on top of what the field's own
// rules produced: a `string.uuid` field a rule also requires non-empty narrows
// to `Uuid & NonEmpty` rather than losing one of the two.
func (f *tsFile) applyCEL(owner string, field parser.FieldMetadata, node *celNode, base string) string {
	if node == nil {
		return base
	}

	if len(node.children) > 0 {
		target, ok := messageTarget(field)
		if !ok {
			return base // selectPath only places paths on singular messages
		}
		inner := base
		if inner == "" {
			if f.ctx.needsStrict[target] {
				inner = f.strictRef(target)
			} else {
				inner = f.shapeRef(target)
			}
		}
		// On top of the target's own strict type, so its rules stay in force.
		base = f.narrowNested(inner, f.ctx.messages[target], node)
	}

	// A term intersects rather than replaces: that satisfies `Narrow`'s
	// constraint by construction, and tells the truth when the two disagree. A
	// uuid a rule also requires empty becomes `Uuid & ""`, uninhabited.
	indexed := indexedProp(owner, field.JSONName)
	if base == "" {
		base = indexed
	}
	switch node.term {
	case parser.TermAbsent:
		return "never"
	case parser.TermEmpty:
		return base + ` & ""`
	case parser.TermZero:
		return "Extract<" + base + ", 0>"
	case parser.TermNonEmpty:
		return base + " & " + f.helper("NonEmpty")
	default:
		if base == indexed {
			return "" // `present` alone changes the optionality, not the type
		}
		return base
	}
}

// narrowNested renders a nested CEL path's narrowing as one more Narrow around
// the type the field already had.
func (f *tsFile) narrowNested(owner string, msg parser.MessageMetadata, node *celNode) string {
	var props, required []string
	for _, name := range node.order {
		field, ok := fieldByName(msg, name)
		if !ok {
			continue
		}
		child := node.children[name]
		if child.term == parser.TermPresent {
			required = append(required, field.JSONName)
		}
		// The field's own rules already live in `owner`, the target's strict
		// type, so only the CEL term applies here.
		if typ := f.applyCEL(owner, field, child, ""); typ != "" {
			props = append(props, field.JSONName+": "+typ+"; ")
		}
	}

	expr := owner
	if len(props) > 0 {
		expr = f.helper("Narrow") + "<" + expr + ", { " + strings.Join(props, "") + "}>"
	}
	if len(required) > 0 {
		expr = f.helper("Require") + "<" + expr + ", " + quotedUnion(required) + ">"
	}
	return expr
}

// oneofProp folds a real oneof into one property. protoc-gen-es models it as a
// discriminated union whose `{ case: undefined }` member is exactly what
// `(buf.validate.oneof).required` rules out.
func (f *tsFile) oneofProp(owner string, msg parser.MessageMetadata, name string) (tsProp, bool) {
	// Without `required` the union is what protoc-gen-es already declared.
	idx := slices.IndexFunc(msg.Oneofs, func(o parser.OneofMetadata) bool {
		return o.Name == name && o.Required
	})
	if idx < 0 {
		return tsProp{}, false
	}

	key := camel(name)
	prop := tsProp{
		key: key,
		typ: "Exclude<" + indexedProp(owner, key) + ", { case: undefined }>",
		doc: []string{oneofLine(msg.Oneofs[idx])},
	}
	// Member rules cannot narrow the arm, so they are printed against the member
	// name instead.
	for _, field := range msg.Fields {
		if field.OneofName != name {
			continue
		}
		for _, line := range ruleComments(field) {
			prop.doc = append(prop.doc, field.Name+": "+line)
		}
	}
	return prop, true
}

// messageDoc renders what belongs above the type: the leading comment, the
// rules naming no single field, and every field rule that produced no
// narrowing. A rule that stops being carried then shows up in the diff.
func (f *tsFile) messageDoc(msg parser.MessageMetadata, runtimeOnly []runtimeNote) []string {
	var lines []string
	if msg.Comments != "" {
		lines = append(lines, oneLine(msg.Comments))
	}
	// A `(buf.validate.message).oneof` names ordinary properties, so no
	// discriminated union rules out setting two of them.
	for _, oneof := range msg.Oneofs {
		if oneof.Name == "" {
			runtimeOnly = append(runtimeOnly, runtimeNote{subject: "oneof", lines: []string{oneofLine(oneof)}})
		}
	}

	notes := f.ctx.celNotes[msg.Name]
	if carried := celCarried(notes); carried != "" {
		lines = append(lines, "", carried)
	}

	runtimeOnly = append(celRuntimeNotes(notes), runtimeOnly...)
	if len(runtimeOnly) > 0 {
		lines = append(lines, "", "Left to runtime validation, having no type equivalent:")
		for _, note := range runtimeOnly {
			lines = append(lines, "  "+note.subject)
			for _, line := range note.lines {
				lines = append(lines, "    "+line)
			}
		}
	}
	return lines
}

// propDoc lists every rule on a narrowed field, then names the ones the type
// carries; the rest hold only at runtime.
func propDoc(field parser.FieldMetadata, n narrowing) []string {
	lines := ruleComments(field)
	if len(n.consumed) == 0 {
		return lines
	}
	carried := slices.Sorted(maps.Keys(n.consumed))
	return append(lines, "", carriedPrefix+strings.Join(carried, ", ")+".")
}

// indexedProp is one property as protoc-gen-es declared it, the base every
// narrowing builds on.
func indexedProp(owner, jsonName string) string {
	return owner + "[" + strconv.Quote(jsonName) + "]"
}
