// Package pygen writes the Python overlay: one <prefix>_strict.py per proto
// file, naming each constrained field as an Annotated alias over the type
// protoc-gen-python already declared.
package pygen

import (
	"maps"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/d0whc3r/protoc-gen-strict/internal/generator/emit"
	"github.com/d0whc3r/protoc-gen-strict/internal/parser"
)

// pyAlias is one `Name = Annotated[T, MinLen(3), "rule", ...]` binding.
type pyAlias struct {
	name     string
	typ      string
	metadata []string // rendered Annotated entries: a constructor call, or a quoted rule
}

// WriteFile writes a <prefix>_strict.py overlay on protoc-gen-python output.
//
// Python cannot narrow a type: message classes come from a metaclass and carry
// no structural type to intersect with. It can name each constrained field, so
// the rules show at the call site: `def promote(user_id: UserId)` instead of
// `user_id: str`.
func WriteFile(gen *protogen.Plugin, file *protogen.File, messages []parser.MessageMetadata) {
	pkgPrefix := string(file.Desc.Package()) + "."
	imports := newPyImports(file.Desc.Path())

	// Resolving types populates the import set, so it runs before the header.
	type block struct {
		doc     []string
		aliases []pyAlias
	}
	blocks := make([]block, 0, len(messages))
	for _, msg := range messages {
		relative := strings.TrimPrefix(msg.Name, pkgPrefix)
		owner := strings.ReplaceAll(relative, ".", "")

		b := block{doc: pyMessageDoc(msg)}
		for _, field := range msg.Fields {
			metadata := imports.metadataOf(field)
			if len(metadata) == 0 {
				continue
			}
			b.aliases = append(b.aliases, pyAlias{
				name:     owner + emit.Pascal(field.Name),
				typ:      imports.typeOf(field),
				metadata: metadata,
			})
		}
		blocks = append(blocks, b)
	}

	// An alias and an imported class can want one name: a `UserId id` field
	// yields the alias `UserId`, and its own type is imported under that name.
	// The alias is the one renamed, since the class name is
	// protoc-gen-python's. Resolved after the walk, once every import is known.
	taken := maps.Clone(imports.symbols)
	for i := range blocks {
		for j := range blocks[i].aliases {
			blocks[i].aliases[j].name = uniqueName(taken, blocks[i].aliases[j].name)
		}
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_strict.py", "")
	g.P("# Code generated by protoc-gen-strict. DO NOT EDIT.")
	g.P("# source: ", file.Desc.Path())
	g.P(`"""buf.validate rules for `, file.Desc.Path(), `.`)
	g.P()
	g.P("One typing.Annotated alias per constrained field, over the type")
	g.P("protoc-gen-python already declared. The message classes stay in")
	g.P(pyModule(file.Desc.Path()), "; import them from there.")
	g.P()
	g.P("A rule with an ", annotatedTypesModule, " equivalent is carried as that constructor,")
	g.P("which pydantic, msgspec and beartype enforce. The rest are metadata strings,")
	g.P("left to protovalidate at runtime.")
	g.P(`"""`)
	g.P()
	g.P("from __future__ import annotations")
	g.P()
	for _, line := range imports.lines() {
		g.P(line)
	}
	g.P()

	for _, b := range blocks {
		for _, line := range emit.CommentLines(b.doc) {
			g.P("# ", line)
		}
		if len(b.aliases) == 0 {
			if len(b.doc) > 0 {
				g.P()
			}
			continue
		}
		for _, alias := range b.aliases {
			g.P(alias.name, " = Annotated[")
			g.P("    ", alias.typ, ",")
			for _, entry := range alias.metadata {
				g.P("    ", entry, ",")
			}
			g.P("]")
		}
		g.P()
	}
}

// uniqueName returns name with as many trailing underscores as it takes to be
// free — PEP 8's escape for a name something else already holds — and records
// the result. The import keeps the name protoc-gen-python gave it.
func uniqueName(taken map[string]bool, name string) string {
	unique := name
	for taken[unique] {
		unique += "_"
	}
	taken[unique] = true
	return unique
}

// pyMessageDoc renders the leading comment and the message-level rules.
func pyMessageDoc(msg parser.MessageMetadata) []string {
	var lines []string
	if msg.Comments != "" {
		lines = append(lines, emit.OneLine(msg.Comments))
	}
	return append(lines, emit.MessageComments(msg)...)
}
