// Code generated by protoc-gen-strict-schema. DO NOT EDIT.
// source: shop/common/v1/common.proto

import labelSetBundle from "../../../jsonschema/shop.common.v1.LabelSet.jsonschema.bundle.json" with { type: "json" };
import moneyBundle from "../../../jsonschema/shop.common.v1.Money.jsonschema.bundle.json" with { type: "json" };
import paginationBundle from "../../../jsonschema/shop.common.v1.Pagination.jsonschema.bundle.json" with { type: "json" };
import timeRangeBundle from "../../../jsonschema/shop.common.v1.TimeRange.jsonschema.bundle.json" with { type: "json" };
import { loosen } from "../../../strict/jsonschema";

/**
 * Money is a fixed-point amount, split into whole units and nanos the way google.type.Money does.
 *
 * JSON Schema 2020-12 for shop.common.v1.Money, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[money.consistent_sign]
 *     this.units == 0 || this.nanos == 0 || (this.units > 0) == (this.nanos > 0)
 *     message: units and nanos must have the same sign
 *   units
 *     int64.gte = -1000000000
 *     int64.lte = 1000000000
 *   nanos
 *     int32.gte = -999999999
 *     int32.lte = 999999999
 *   absent fields
 *     units, nanos: an absent key is the zero value, which the rules still apply to
 */
export const moneyJsonSchema = loosen(moneyBundle);

/**
 * Pagination is the page selector shared by every list request.
 *
 * JSON Schema 2020-12 for shop.common.v1.Pagination, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   page
 *     int32.gte = 1
 *   page_size
 *     int32.gt = 0
 *     int32.lte = 100
 *   absent fields
 *     page, page_size: an absent key is the zero value, which the rules still apply to
 */
export const paginationJsonSchema = loosen(paginationBundle);

/**
 * TimeRange is a half-open interval [start, end).
 *
 * JSON Schema 2020-12 for shop.common.v1.TimeRange, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   cel[time_range.ordered]
 *     !has(this.end) || this.start < this.end
 *     message: end must be strictly after start
 */
export const timeRangeJsonSchema = loosen(timeRangeBundle);

/**
 * LabelSet is a bounded set of user-supplied key/value labels.
 *
 * JSON Schema 2020-12 for shop.common.v1.LabelSet, from protoschema-jsonschema.
 *
 * Left to runtime validation:
 *   labels
 *     map.max_pairs = 32
 *     map.min_pairs = 1
 *     map.keys.string.pattern = ^[a-z][a-z0-9_-]*$
 *   absent fields
 *     labels: an absent key is the zero value, which the rules still apply to
 */
export const labelSetJsonSchema = loosen(labelSetBundle);
